import { expect, test } from '@playwright/test'
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

test('original map tiles, region selection, wiki and return to map work', async ({ page }) => {
  const errors: string[] = []
  const tiles: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('response', response => { if (response.url().includes('aruzahr_files/') && response.ok()) tiles.push(response.url()) })
  await page.goto('/')
  await expect(page.getByTestId('marker-xotar')).toBeVisible()
  await expect.poll(() => tiles.length).toBeGreaterThan(0)
  await page.getByTestId('marker-xotar').click()
  await expect(page.getByTestId('detail-panel')).toContainText('Çölün kalbi')
  await page.getByRole('button', { name: 'Wiki sayfasını aç' }).click()
  await expect(page).toHaveURL(/#\/wiki\/xotar$/)
  await expect(page.getByRole('heading', { name: 'Kumun altında yaşam' })).toBeVisible()
  await page.getByRole('button', { name: 'Haritada göster' }).click()
  await expect(page.getByTestId('detail-panel')).toContainText('Xotar')
  await expect(page.getByTestId('zoom-level')).not.toHaveText('100%')
  expect(errors).toEqual([])
})

test('city search, bookmarks persist and zoom controls change the view', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: 'Atlas ve wiki içinde ara' }).fill('Valdareth')
  await page.locator('.place-search-result').filter({ hasText: 'Valdareth' }).click()
  await expect(page.getByTestId('detail-panel')).toContainText('soylu başkent')
  await page.getByRole('button', { name: 'Valdareth kaydet', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Valdareth kaydını kaldır' })).toBeVisible()
  await expect(page.getByTestId('zoom-level')).not.toHaveText('100%')
  await page.waitForTimeout(1400)
  const before = parseInt((await page.getByTestId('zoom-level').textContent())!)
  await page.getByRole('button', { name: 'Yakınlaştır', exact: true }).click()
  await expect.poll(async () => parseInt((await page.getByTestId('zoom-level').textContent())!)).toBeGreaterThan(before)
  await page.getByRole('button', { name: 'Haritanın tamamını göster' }).click()
  await expect(page.getByTestId('detail-panel')).toHaveCount(0)
  await expect(page.getByTestId('zoom-level')).toHaveText('100%')
  await page.getByRole('button', { name: 'Kaydedilen yerleri göster' }).click()
  await expect(page.locator('.place-search-result')).toContainText('Valdareth')
  await page.goto('/#/wiki/buyuk-kirilma')
  await page.getByRole('button', { name: 'Kaydı kaydet', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Kaydedilen yerleri göster' }).click()
  await expect(page.locator('.place-search-result').filter({ hasText: 'Büyük Kırılma' })).toBeVisible()
})

test('city layer is interactive and permanent wiki links survive reload', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('marker-valdareth')).toBeHidden()
  await page.getByRole('button', { name: 'Yerleşimler', exact: true }).click()
  await expect(page.getByTestId('marker-valdareth')).toBeVisible()
  await page.getByTestId('marker-valdareth').click()
  await expect(page.getByTestId('detail-panel')).toContainText('Valdareth')
  await page.goto('/#/wiki/honud')
  await expect(page.getByRole('heading', { name: 'Honud', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Ruhlar ve sözlü büyü' })).toBeVisible()
  await page.goto('/#/wiki/not-a-location')
  await expect(page.getByRole('heading', { name: 'Kayıt bulunamadı.' })).toBeVisible()
})

test('keyboard search, help, focus view and reduced motion are usable', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.getByTestId('marker-xotar')).toBeVisible()
  await expect(page.locator('.atmosphere')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Atmosfer efektleri' })).toBeDisabled()
  await page.keyboard.press('/')
  await expect(page.getByRole('textbox', { name: 'Atlas ve wiki içinde ara' })).toBeFocused()
  await page.getByRole('textbox', { name: 'Atlas ve wiki içinde ara' }).fill('HONUD')
  await expect(page.locator('.region-list .region-link')).toHaveCount(1)
  await page.getByRole('button', { name: 'Aramayı temizle' }).click()
  await page.getByRole('button', { name: 'Kullanım rehberi' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeHidden()
  await page.getByRole('button', { name: 'Odak moduna geç' }).click()
  await expect(page.locator('.map-shell')).toHaveClass(/focus-mode/)
  await page.getByRole('button', { name: 'Odak modundan çık' }).click()
  await expect(page.locator('.map-shell')).not.toHaveClass(/focus-mode/)
})

test('mobile navigation, map and wiki fit without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByTestId('marker-xotar')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Bölge menüsünü aç' }).click()
  await page.locator('.region-list').getByRole('button', { name: /Honud/ }).click()
  await expect(page.getByTestId('detail-panel')).toContainText('Honud')
  await page.getByRole('button', { name: 'Wiki sayfasını aç' }).click()
  await expect(page.getByRole('heading', { name: 'Honud', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('Danstsud distinguishes its regions from cities and follows Hardlane to Frostbay', async ({ page }) => {
  await page.goto('/#/wiki/danstsud')
  await expect(page.getByRole('heading', { name: 'Taç, lordlar ve vergi' })).toBeVisible()
  await expect(page.locator('.article-period')).toContainText('DARBE ÖNCESİ')
  await expect(page.getByTestId('subregion-links').getByRole('button')).toHaveCount(3)
  const settlements = page.getByTestId('related-locations')
  for (const city of ['Lirendil', 'Dorvenhall', 'Marhalden', 'Valdareth', 'Elorwyn', 'Theramis']) {
    await expect(settlements.getByRole('button', { name: `${city} Başlıca şehir`, exact: true })).toBeVisible()
  }
  await expect(settlements).not.toContainText('Lowvale')
  await expect(settlements).not.toContainText('Hardlane')
  await page.getByTestId('subregion-links').getByRole('button', { name: /^Hardlane/ }).click()
  await expect(page.getByRole('heading', { name: 'Hardlane', exact: true })).toBeVisible()
  await expect(page.locator('.article-content')).toContainText('kâğıt üzerinde')
  await page.getByTestId('related-locations').getByRole('button', { name: 'Frostbay Yerleşim', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Sınırlı hizmet ve tahsilat', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Haritada göster' }).click()
  await expect(page.getByTestId('detail-panel')).toContainText('Frostbay')
  await expect(page.locator('.atmosphere')).toHaveClass(/scene-honud/)
  await expect(page.getByTestId('marker-frostbay')).toHaveClass(/city-pin/)
  await expect(page.getByTestId('marker-hardlane')).toHaveClass(/subregion-pin/)
})

test('specific city articles and old Marahalden links and bookmarks remain usable', async ({ page }) => {
  await page.goto('/#/wiki/lirendil')
  await expect(page.getByRole('heading', { name: 'Körük ve Örs', exact: true })).toBeVisible()
  await expect(page.locator('.article-content')).toContainText('Ghorin')
  await expect(page.locator('.article-content')).toContainText('Zylara')
  await page.goto('/#/wiki/kethra')
  await expect(page.getByRole('heading', { name: 'Paslı Kanca ve antrepolar', exact: true })).toBeVisible()
  await page.evaluate(() => localStorage.setItem('aruzahr-saved', JSON.stringify(['marahalden'])))
  await page.goto('/#/wiki/marahalden')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Marhalden', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Kaydı kaldır', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Haritada göster' }).click()
  await expect(page).toHaveURL(/#\/atlas\/marhalden$/)
  await expect(page.getByTestId('detail-panel')).toContainText('Marhalden')
})

test('court records link from cities, persist as bookmarks and return to a real map location', async ({ page }) => {
  await page.goto('/#/wiki/valdareth')
  await expect(page.getByRole('heading', { name: 'Vaeranth ailesi ve saray', exact: true })).toBeVisible()
  await page.getByTestId('related-locations').getByRole('button', { name: 'Vaeranth Hanedanı Hanedan', exact: true }).click()
  await expect(page).toHaveURL(/#\/wiki\/vaeranth-hanedani$/)
  await expect(page.getByRole('heading', { name: 'Vaeranth Hanedanı', exact: true })).toBeVisible()
  await expect(page.locator('.article-content')).toContainText('Ilyenne')
  await expect(page.locator('.article-content')).toContainText('bilinen bir erkek varisi yoktur')
  await expect(page.locator('.article-content')).not.toContainText('Corven')
  await expect(page.locator('.article-content')).not.toContainText('Ossian')
  await page.getByRole('button', { name: 'Kaydı kaydet', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Kaydı kaldır', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Kaydedilen yerleri göster' }).click()
  await expect(page.locator('.lore-search-result')).toContainText('Vaeranth Hanedanı')
  await page.getByRole('button', { name: 'İlgili yeri haritada göster', exact: true }).click()
  await expect(page).toHaveURL(/#\/atlas\/valdareth$/)
  await expect(page.getByTestId('detail-panel')).toContainText('Valdareth')
  await expect(page.getByTestId('marker-vaeranth-hanedani')).toHaveCount(0)
})

test('old family names are searchable and magic law connects to Theramis', async ({ page }) => {
  await page.goto('/#/wiki')
  await page.getByRole('textbox', { name: 'Atlas ve wiki içinde ara' }).fill('Damian Elorwyn')
  await page.locator('.lore-search-result').filter({ hasText: 'Elorwynder Hanedanı' }).click()
  await expect(page.getByRole('heading', { name: 'Elorwynder Hanedanı', exact: true })).toBeVisible()
  await expect(page.locator('.article-content')).toContainText('hep bu hanedanın yönetiminde')
  await expect(page.locator('.article-content')).toContainText('Damian Elorwynder')
  await page.goto('/#/wiki/buyu-ruhsatlari')
  await expect(page.getByRole('heading', { name: 'Kraliyet Büyü Sicili', exact: true })).toBeVisible()
  await expect(page.locator('.article-lead')).toContainText('okul dışında da yasal hizmet')
  await expect(page.locator('.article-content')).toContainText('ruhsatla da yasal hâle gelmez')
  await page.getByTestId('related-locations').getByRole('button', { name: 'Theramis Başlıca şehir', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Theramis', exact: true })).toBeVisible()
  await expect(page.locator('.article-content')).toContainText('ruhsa')
  await page.getByTestId('related-locations').getByRole('button', { name: 'Büyü Ruhsatları Hukuk', exact: true }).click()
  await expect(page).toHaveURL(/#\/wiki\/buyu-ruhsatlari$/)
})

test('mobile lore pages are discoverable and long titles stay inside the cover', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/wiki')
  await page.getByTestId('wiki-lore-results').getByRole('link', { name: /Vaeranth Hanedanı/ }).click()
  await expect(page.getByRole('heading', { name: 'Vaeranth Hanedanı', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const cover = await page.locator('.article-cover').boundingBox()
  const title = await page.locator('.article-title').boundingBox()
  expect(title!.y).toBeGreaterThanOrEqual(cover!.y)
  await page.getByRole('button', { name: 'Bölge menüsünü aç' }).click()
  await page.getByRole('textbox', { name: 'Atlas ve wiki içinde ara' }).fill('Eryndorn')
  await page.locator('.lore-search-result').filter({ hasText: 'Eryndorn Vaeranth' }).click()
  await expect(page.getByRole('heading', { name: 'Eryndorn Vaeranth', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('published artifacts omit DM secrets and development server blocks raw lore files', async ({ request }) => {
  const secretPhrases = ['Yarethus’un Kutsal İzi', 'Halendar’ın Kızıl Kıvılcımı', 'PROJECT: BROKEN OATH', 'Deli Kral Halendar’ın Ateş Mahkemesi', 'Denge Ritüeli', 'DM NOTU', 'Corven', 'Ossian', 'gayrimeşru']
  function inspect(directory: string) {
    for (const name of readdirSync(directory, { withFileTypes: true })) {
      const file = join(directory, name.name)
      if (name.isDirectory()) inspect(file)
      else {
        expect(file).not.toMatch(/\.(docx|pdf)$/)
        expect(file).not.toMatch(/KAYNAK_METINLERI|CALISMA_DOSYASI|KANON\.md|HANEDANLAR_VE_BUYU_HUKUKU/)
        if (/\.(js|html|json|txt|md)$/.test(file)) {
          const text = readFileSync(file, 'utf8')
          for (const phrase of secretPhrases) expect(text).not.toContain(phrase)
        }
      }
    }
  }
  inspect('dist')
  for (const name of ['Valhunar.pdf', 'Main questler.docx', 'ANA HİKÂYE DOKÜMANI.docx']) {
    const response = await request.get(`/@fs/workspace/2026Aruzahr/${encodeURIComponent(name)}`)
    expect(response.status()).toBe(403)
    expect(response.headers()['content-type'] || '').not.toMatch(/pdf|officedocument/)
  }
  const authorNotes = await request.get('/@fs/workspace/2026Aruzahr/lore/danstsud/KAYNAK_METINLERI.md')
  expect(authorNotes.status()).toBe(403)
  expect(await authorNotes.text()).not.toContain('Yarethus’un Kutsal İzi')
  const familyNotes = await request.get('/@fs/workspace/2026Aruzahr/lore/danstsud/HANEDANLAR_VE_BUYU_HUKUKU.md')
  expect(familyNotes.status()).toBe(403)
  expect(await familyNotes.text()).not.toContain('Corven')
})
