import { expect, test } from '@playwright/test'

test('character collection explains combined influence and varies ornate frames without hiding names', async ({page}) => {
  await page.goto('/#/wiki')
  await page.getByLabel('Karakter adı veya görevi').fill('Eryndorn')
  const king = page.locator('.portrait-grid .character-card')
  await expect(king).toHaveAttribute('data-power-tier','supreme')
  await expect(king.locator('figcaption')).toContainText('Eryndorn Vaeranth')
  await expect.poll(()=>king.locator('img').evaluate((image:HTMLImageElement)=>image.naturalWidth)).toBeGreaterThan(0)
  await page.locator('.character-frame-legend summary').click()
  await expect(page.locator('.character-frame-legend')).toContainText('dövüş, büyü ve siyasi nüfuz')
  await page.getByLabel('Karakter adı veya görevi').fill('Seraphinia')
  await expect(page.locator('.portrait-grid .character-card')).toHaveAttribute('data-power-tier','ordinary')
  await page.locator('.portrait-grid a').click()
  await expect(page.getByRole('heading',{name:'Seraphinia',exact:true})).toBeVisible()
  await expect(page.locator('.hero-portrait-button .character-card')).toHaveAttribute('data-power-tier','ordinary')
})

test('unidentified portraits keep their unknown power in the collection and enlarged card', async ({page}) => {
  await page.goto('/#/wiki')
  await page.getByRole('button',{name:/Bütün karakterler ve portreler/}).click()
  const portrait=page.getByRole('button',{name:/Lysandra Portre galerisi/})
  await expect(portrait.locator('.character-card')).toHaveAttribute('data-power-tier','unknown')
  await portrait.click()
  const dialog=page.getByRole('dialog',{name:'Görsel galerisi'})
  await expect(dialog.locator('.character-card')).toHaveAttribute('data-power-tier','unknown')
  await expect(dialog).toContainText('Gücü bilinmiyor')
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
})

test('a city card and its mobile biography retain the same tier and gallery interactions', async ({page}) => {
  await page.setViewportSize({width:390,height:844})
  await page.goto('/#/wiki/elorwyn')
  const rina=page.locator('.people-grid .character-card[data-character-id="rina"]')
  await expect(rina).toHaveAttribute('data-power-tier','distinguished')
  const action=rina.locator('xpath=ancestor::div[contains(@class,"framed-person")]').getByRole('button',{name:'Tanı',exact:true})
  const frameBox=await rina.boundingBox()
  const actionBox=await action.boundingBox()
  expect(frameBox).not.toBeNull()
  expect(actionBox).not.toBeNull()
  expect(actionBox!.y).toBeGreaterThanOrEqual(frameBox!.y+frameBox!.height)
  await rina.locator('img').click()
  const dialog=page.getByRole('dialog',{name:'Görsel galerisi'})
  await expect(dialog.locator('.character-card')).toHaveAttribute('data-power-tier','distinguished')
  await page.getByRole('button',{name:'Görseli kapat'}).click()
  await page.goto('/#/wiki/rina')
  await expect(page.locator('.hero-portrait-button .character-card')).toHaveAttribute('data-power-tier','distinguished')
  await expect(page.getByTestId('character-passport')).toContainText('Ser Valerius’un yaveri')
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.getByRole('button',{name:'Rina Ironvale portresini büyüt'}).click()
  await expect(dialog.locator('.character-card')).toHaveAttribute('data-power-tier','distinguished')
  await page.keyboard.press('ArrowRight')
  await expect(dialog).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
})
