import { expect, test } from '@playwright/test'

test('the global gallery filters the actual archive and supports the native keyboard viewer', async ({ page }) => {
  await page.goto('/#/gallery')
  await expect(page.getByTestId('gallery-hub')).toBeVisible()
  await page.getByRole('group', { name: 'Galeri kategorileri' }).getByRole('button', { name: /Canlılar/ }).click()
  await page.getByRole('textbox', { name: 'Görsellerde ara' }).fill('Orvak')
  await expect(page.locator('.gallery-collection .gallery-tile').first()).toContainText('Orvak')
  await expect(page.locator('.gallery-collection .gallery-tile-portrait')).toHaveCount(0)
  await page.locator('.gallery-collection .artwork-button').first().click()
  const viewer = page.getByRole('dialog', { name: 'Görsel galerisi' })
  await expect(viewer).toBeVisible()
  await expect(viewer.getByRole('heading')).toContainText('Orvak')
  await page.keyboard.press('Escape')
  await expect(viewer).toBeHidden()
  await page.getByRole('button', { name: 'Galeri aramasını temizle' }).click()
  await page.getByRole('group', { name: 'Galeri kategorileri' }).getByRole('button', { name: /Karakterler/ }).click()
  await page.getByRole('textbox', { name: 'Görsellerde ara' }).fill('Eryndorn')
  await page.locator('.gallery-collection .artwork-button').first().click()
  await expect(viewer).toBeVisible()
  const initial = await viewer.locator('header > span').textContent()
  await page.keyboard.press('ArrowRight')
  await expect(viewer.locator('header > span')).not.toHaveText(initial!)
  await page.keyboard.press('Escape')
  await page.locator('.gallery-tile-footer button').first().click()
  await expect(page).toHaveURL(/#\/wiki\/eryndorn$/)
})

test('book shelves filter distinct volumes and turn their surviving leaves', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/#/books')
  await expect(page.getByTestId('bookshelf')).toBeVisible()
  await expect(page.locator('.world-book-grid > button')).toHaveCount(8)
  await page.getByRole('button', { name: 'Yasaklı kitaplar', exact: false }).click()
  await expect(page.locator('.world-book-grid > button')).toHaveCount(1)
  await page.getByRole('button', { name: 'Kırık Mühür Risalesi kitabını aç', exact: true }).click()
  const desk = page.getByTestId('book-reading-desk')
  await expect(desk).toContainText('Mühür, bir hükmün kimin elinden çıktığını söyler.')
  await expect(page.getByRole('button', { name: 'Önceki kitap yaprağı' })).toBeDisabled()
  await page.getByRole('button', { name: 'Sonraki kitap yaprağı' }).click()
  await expect(desk).toContainText('Bir makamın alınabileceğini herkes bilir.')
  await page.getByRole('button', { name: 'Sonraki kitap yaprağı' }).click()
  await expect(page.getByRole('button', { name: 'Sonraki kitap yaprağı' })).toBeDisabled()
  await page.getByRole('button', { name: 'Bütün kaydı oku' }).click()
  await expect(page).toHaveURL(/#\/wiki\/kitap-kirik-muhur$/)
  await expect(page.getByRole('heading', { name: 'Kırık Mühür Risalesi', exact: true })).toBeVisible()
  await expect(page.locator('.book-lore-chapter')).toHaveCount(2)
})

test('chapter topics keep a complete reading and table of contents restores hidden chapters', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/#/wiki/valdareth')
  const chapters = page.locator('.lore-section-card')
  const count = await chapters.count()
  await page.getByRole('button', { name: /Sokak & yaşam/ }).click()
  await expect(page.locator('.lore-section-card[hidden]')).not.toHaveCount(0)
  await expect(chapters).toHaveCount(count)
  await page.locator('.article-toc').getByRole('button', { name: /Beş surun başkenti/ }).click()
  await expect(page.locator('.lore-section-card[hidden]')).toHaveCount(0)
  await expect(chapters.first().locator('.section-prose')).toBeVisible()
  await expect(chapters.first()).toBeInViewport()
  await expect(chapters.first().locator('.section-opening')).toContainText('Danstsud’un en kalabalık şehridir')
})

test('quiet reading and the parchment desk remain usable on a narrow phone', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 760 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/#/wiki/valdareth')
  await page.getByRole('button', { name: 'Sakin okuma', exact: true }).click()
  await expect(page.locator('.wiki-article')).toHaveClass(/quiet-reading/)
  await expect(page.locator('.people-section')).toBeHidden()
  await expect(page.locator('.section-detail:not([open])')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Kartlar', exact: true }).click()
  await expect(page.locator('.wiki-article')).not.toHaveClass(/quiet-reading/)
  await page.goto('/#/books')
  await page.getByRole('button', { name: /Kayıp yapraklar/ }).click()
  await expect(page.locator('.world-book-grid > button')).toHaveCount(2)
  await page.getByRole('button', { name: 'Sıcak Taşların Yolcusu kitabını aç', exact: true }).click()
  await expect(page.locator('.book-paper-reading p')).toContainText('Taşa avucumu koydum')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('the capital links its twelve knights to a complete distinct roster and individual city records', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/#/wiki/valdareth')
  const institutionLink = page.getByTestId('institution-link-tac-on-iki')
  await expect(institutionLink).toContainText('12 kayıtlı kişi')
  await expect(institutionLink.locator('img')).toHaveCount(3)
  await institutionLink.click()
  await expect(page).toHaveURL(/#\/wiki\/tac-on-iki$/)
  const roster = page.getByTestId('institution-roster')
  await expect(roster).toHaveAttribute('data-roster-id', 'tac-on-iki')
  await expect(roster.locator('.institution-member')).toHaveCount(6)
  await page.getByRole('button', { name: 'Bütün kadroyu göster (12)', exact: true }).click()
  await expect(roster.locator('.institution-member')).toHaveCount(12)
  const names = await roster.locator('.institution-member-info h3').allTextContents()
  expect(new Set(names).size).toBe(12)
  expect(names.every(name => name.trim().length > 3)).toBe(true)
  await expect(roster.locator('.institution-member-portrait')).toHaveCount(12)
  await roster.locator('.institution-member-portrait').first().click()
  const viewer = page.getByRole('dialog', { name: 'Görsel galerisi' })
  await expect(viewer).toBeVisible()
  await expect(viewer.getByRole('heading')).toHaveText(names[0])
  await page.keyboard.press('Escape')
  await roster.locator('.institution-member-info button').first().click()
  await expect(page.getByTestId('character-passport')).toContainText('Valdareth')
  await expect(page.locator('.article-title h1')).toHaveText(names[0])
})
