import type { WorldBook } from './books'
import { originalBooks } from './book-originals'
import { supplements } from './book-supplements'
import { bryndonArticles } from './bryndon'
import { historyArticle } from './history'

const page = (...paragraphs: string[]) => paragraphs.join('\n\n')
const sourceLeaves = (paragraphs: string[]) => {
  const leaves: string[] = []
  let current: string[] = [], count = 0
  for (const paragraph of paragraphs) {
    const words = paragraph.trim().split(/\s+/).length
    if (count + words > 620) break
    current.push(paragraph); count += words
    if (current.join(' ').split(/\s+/).length >= 150) { leaves.push(page(...current)); current = [] }
  }
  if (current.length) leaves.push(page(...current))
  return leaves
}
export const bookExpansions: Record<string, string[]> = Object.fromEntries(originalBooks.filter(book => supplements[book.id]).map(book => [book.id,book.excerpt.map((opening,index) => page(opening,...supplements[book.id][index]))]))
// These two books are excerpts of already-public texts, not a new history or
// fabricated quotation. Full records remain at their existing wiki URLs.
bookExpansions['bryndon-kiyi-defteri'] = sourceLeaves([...originalBooks.find(book => book.id === 'bryndon-kiyi-defteri')!.excerpt,...bryndonArticles[0].sections.flatMap(section => section.paragraphs)])
bookExpansions['buyuk-kirilma'] = sourceLeaves([...originalBooks.find(book => book.id === 'buyuk-kirilma')!.excerpt,...historyArticle.sections.flatMap(section => section.paragraphs)])

export const bookDetails: Record<string, Partial<WorldBook>> = {
  'bryndon-kiyi-defteri': { authorId:'bryndon-kiyi-defteri', placeId:'frostbay', period:'Eryndorn’un saltanatı · saha defterinden seçki', category:'arastirma' },
  'buyuk-kirilma': { placeId:'danstsud', period:'Farklı çağların anlatıları · bugünkü derleme', category:'tanıklık' },
  'kitap-bes-duvar': {authorId:'erhan-telis',placeId:'valdareth',period:'Eryndorn’un saltanatı · ustanın geç dönem defteri',category:'tanıklık',leafTitles:['Fırının eski duvarı','Kiremidin altındaki emek','Kapıların farklı saatleri']},
  'kitap-kirik-muhur': {placeId:'valdareth',period:'Tarihsiz kopya · darbe öncesinde dolaşır',category:'tanıklık',leafTitles:['Hüküm ve hesap','Makam değişince','İsimsiz son yaprak']},
  'kitap-cevherin-hakki': {placeId:'marhalden',period:'Tarihsiz çalışma nüshası · üç çevrenin usulleri',category:'arastirma',leafTitles:['Taşın ve işçinin payı','İki ayrı görev süresi','Eksik kaydın sınırı']},
  'kitap-iki-kiyi': {placeId:'frostbay',period:'Derleme tarihi belirsiz · farklı kıyı tanıklıkları',category:'tanıklık',leafTitles:['Karşı kıyının sözü','Dua ile ağıt','Kayıp bağ yerleri']},
  'kitap-sicak-taslar': {authorId:'ivena-sarell',placeId:'ternhaven',period:'Eryndorn’un saltanatı · yolculuk notları',category:'yolculuk',leafTitles:['Suyun işi','Bugün kullanılan taş','Kâğıttaki yol']},
  'kitap-kisa-pay': {authorId:'sella-vorn',placeId:'frostbay',period:'Son kış hazırlığı · haneler arasında çoğaltılır',category:'tanıklık',leafTitles:['Önce hayvanın payı','Ocağın ortak hesabı','Takvimin boş günleri']},
}

export const researchBooks: WorldBook[] = [
  {
    id:'kitap-yel-degirmeni',title:'Rüzgâra Dönmeyen Değirmen',subtitle:'Frostbay’de yön ve zaman üzerine',author:'Kâtip Bryndon',authorId:'bryndon-kiyi-defteri',place:'Frostbay',placeId:'frostbay',region:'danstsud',period:'Eryndorn’un saltanatı · ikinci saha seçkisi',condition:'eski',category:'arastirma',color:'#657f86',motif:'window',
    note:'Eski bir değirmenin bugünkü rüzgârla uyuşmayan yönü. Taş, kullanım izi ve farklı tanıklıklar aynı soruya bakar.',leafTitles:['Kuzeye bakmayan pencere','Taşın ayrı yaşları','Bir hükmü bekletmek'],marginNotes:['Gözlem ile tarihlendirme ayrı işlerdir.','Yeni derz, eski taşın çağını değiştirmez.','Değirmen tek başına bütün kıyıyı açıklamaz.'],
    excerpt:[
      page('Postahanedeki görevli eski değirmeni gösterdiğinde önce yüksekliğine baktım. Sonra rüzgârın geldiği yöne döndüm. Aynı yapı bugün inşa edilse ustanın kanadı böyle yerleştireceğini sanmıyorum. Bunun ilk sahibinin rüzgârı bilmediğini gösterdiğini söylemek kolay olurdu. Oysa kanadın bulunduğu üst kısmın alt duvarla aynı zamanda yapılmış olduğunu henüz bilmiyordum. Defterimin başına yalnız gördüğümü yazdım: kanat yuvası, bugünkü yaygın kıyı rüzgârına uygun görünmüyor.',
      'Değirmenin yakınında balık kurutan kadın, annesinin bu taşları değirmen diye anmadığını söyledi. Bu söz, yapının başka bir işe ayrılmış olabileceğini düşündürür; kadının annesinin ilk ustayı tanıdığını göstermez. Yaşayan bir kişinin hatırası, önce kendi ömrünün çevresinde ölçülmelidir. Adını izin verirse kayda alacağım. Şimdilik başka hanelerin aynı adı kullanıp kullanmadığını soruyorum. Posta görevlisi yapıyı ölçmeme yardım etti, fakat çalıştığı kapının bütün tarihini bildiğini ileri sürmedi.',
      'Bugünkü rüzgârı anlamak için iki öğleden sonrayı ayırdım. Bir ölçü, mevsimin bütününü temsil etmez. Eski yönün bir zamanlar işe yaramış olması mümkündür; bu ihtimali sınamak için bugünkü havadan daha uzun bir kayıt gerekir. İlk yaprağın yanına pusula çizmek yerine ölçünün saatini yazdım.'),
      page('Alt sıradaki dairetaşların harcı ile üst pencerenin çevresindeki derz aynı renkte değildi. Bunun bir onarımın izi olup olmadığını duvar işçisine sordum. Harcı parmağımla kazımamı istemedi: küçük bir örnek alırken suyun gireceği yeni bir aralık açabilirdim. Eski yapıyı öğrenmek için ona yeni zarar vermek, cevabın bedelini bugün yaşayanlara ödetir. Kömür suretini aldım; örnek işini izin ve doğru alet bulunana kadar bıraktım.',
      'Yel değirmeni denen yapının yanında daha küçük yuvarlak bir taban var. Üzerindeki aşınmanın yönü ilk binanınkiyle uyuşmuyor. İki yapının birlikte çalıştığına dair elimde bir yazı yok. Yine de aralarındaki mesafeyi kaydetmek yararlıdır. Bir parça başka yerden getirilmişse bugünkü konumu bütün eski düzeni açıklamayabilir. Taşın yaşını, taşın burada geçirdiği süreyle karıştırmamak gerekir.',
      'Frostbay’in eski iklimine dair sorum sürüyor. Yerel otlaklar, eski bitki izleri ve bazı yapı biçimleri birlikte araştırılmalıdır. Tek bir kanat yuvası, geçmişin yeşilliğini kanıtlamaz. Farklı izlerin aynı döneme ait olup olmadığı bilinmeden hepsini tek güzel anlatıda birleştirmek istemem. Güzel anlatının araştırmacıya verdiği rahatlık, yanlış tarihi bir sonraki kâtibe bıraktığında biter.'),
      page('İvren Vask eski posta kayıtlarının hangi dolapta tutulduğunu gösterebileceğini söyledi. Nera Veld’den araştırmanın çalışan kapıları kapatmaması için izin istedim. Birinde belge, ötekinde bugünkü kullanımın sorumluluğu bulunuyor. İki kişinin aynı masada çalışmaması, birinin ötekinden bir şey sakladığını kendi başına göstermez. Sorularımı ayrı yapraklara yazdım; her biri bildiği kısmı cevaplasın istiyorum.',
      'Araştırmaya yardım edecek yolculara üç iş bırakıyorum: başka bir eski yapının yönünü aynı usulle ölçmek, değirmenin eski adını birbirinden ayrı hanelerden dinlemek ve taş işçiliğinin değiştiği sınırı yeri bozmadan çizmek. Bir cevabın eksikliği öteki ikisini anlamsız kılmaz. Belgede yapı adı değişmişse bunun hangi kullanım sırasında olduğunu bulmak gerekir. Farklı adların hepsini ayrı bina saymak kadar hepsini tek bina kabul etmek de aceledir.',
      'Bu defterin sonunda kıyıyı değiştiren büyük olaya yeni bir ad vermiyorum. Eldeki izlerin hangi soruya cevap verebileceğini söylüyorum. Değirmenin neden bu yöne baktığı açıklansa bile Frostbay’in bütün geçmişi açıklanmış olmaz. Son satırı bunun için boş bıraktım: bir sonraki ziyaretimde aynı taşı daha iyi bir soruyla görebilmek için.'),
    ],
  },
  {
    id:'kitap-uc-agirlik',title:'Bir Yükün Üç Ağırlığı',subtitle:'Kazı, işleme ve satış kayıtları',author:'Mereth Vann',authorId:'mereth-vann',place:'Marhalden',placeId:'marhalden',region:'danstsud',period:'Eryndorn’un saltanatı · güncel karşılaştırma',condition:'eski',category:'arastirma',color:'#766789',motif:'anvil',
    note:'Aynı sevkiyat için üç başka miktar. Hangi farkın üretimden, hangisinin ayrı bir karardan çıktığı henüz açık değildir.',leafTitles:['Kazı defteri','Örsün kaydı','Satış yaprağı'],marginNotes:['Ölçülen mal aynı aşamada mı?','Cürufun ayrıca kaydı var.','Bir fark, henüz bir suçlu değildir.'],
    excerpt:[
      page('Aynı teslimin üç ağırlığını önümde açık tuttum. Kazı kaydı yirmi dört, işleme kaydı on dokuz, satış kaydı on sekiz buçuk birim gösteriyordu. İlk bakışta beş buçuk birim kayıp vardı. Fakat kazıdan gelen şey hazır metal değildi; taş ve ayrılacak artık da tartıya giriyordu. Bir yükün bütün farkını ilk satırdan suç sayarsam işleme çevresinin yaptığı işi hiç yapılmamış kabul etmiş olurum.',
      'Tervik Hann’dan teslim günü kullanılan ölçünün karşılığını istedim. Aynı işaret bazen ağırlık, bazen önceden belirlenmiş bir yük payını anlatabilir. Bu teslimde ağırlık kullanıldığını söyledi ve tanık listesini gösterdi. Kâtibin adı ile yükü taşıyanın adı ayrıydı. İkisini aynı kişinin ağzından dinlemek yerine taşıyıcıya da gittim. Beni geçide götürecek vakti olmadı; bir sonraki boş dönüşünde tartı yerini gösterebileceğini söyledi.',
      'Bu notlar üç çevrenin eski usullerini kaldıran bir emir değildir. Bugünkü bir hesabın başlangıcıdır. Lordun sekiz yıllık süresiyle baş lonca makamının dört yıllık süresi de tartının sayısını değiştirmez. Bir seçim yaklaşırken kaydın daha dikkatle okunması anlaşılır; bir farkın o seçime göre anlam kazanması ise araştırmacının sakınması gereken başka bir iştir.'),
      page('Nesra Dolm işleme sırasında ayrılan cürufun kaydını açtı. Beş birim, o teslimin yakıt ve yan ürün yapraklarıyla birlikte izlenebiliyordu. Böyle bir eşleşme, bütün işin kusursuz yapıldığını ispat etmez; fakat farkın o kısmı için izlenecek yol artık bellidir. Bir gözlemden sonra başka bir gözlemin gereksiz olduğunu söylemiyorum. Sadece her soruyu doğru masaya götürmeye çalışıyorum.',
      'İşçinin ücreti satılan metalin ağırlığıyla aynı defterde görünmeyebilir. Ocakta geçirilen saat, yeniden işlenen parça ve başka işe ayrılan mal farklı satırlara gider. Ustaların her açıklamasını doğru kabul etmek de her farklı kaydı saklama saymak da hatadır. İşlemeyi yerinde bilen biri hangi parçanın gerçekten ayrıldığını gösterebilir. Kâtip ise bunun teslimde nasıl adlandırıldığını sorar. İki bilgi birbirinin yerine geçmez.',
      'Satışa geçen on dokuz birimi gösteren ara teslimin kenarında bir küçük işaret vardı. Aynı işaretin başka sevkiyatlarda kullanılıp kullanılmadığını öğrenmeden ona anlam vermedim. İşleme kaydının tamamlandığı saatle satışın kabul saati arasındaki boşluk hâlâ araştırılmalı. O boşluğu bir hikâyeyle doldurmak kolaydır; hangi işin hangi saatte yapıldığını öğrenmek daha yavaş ve daha yararlıdır.'),
      page('Karven Oll’un satış yaprağı on sekiz buçuk birimle kapanıyordu. Onun sayısını kazıcının sayısıyla karşılaştırırken aradaki üretim aşamasını artık ayırabiliyoruz. Geriye kalan yarım birimin aynı biçimde açıklanıp açıklanamayacağını bilmiyoruz. Yükün sahibi, borç kaydı ve teslimin kabul şartları birlikte okunmalı. Kâtibin elinde yalnız bir kapanış satırı varsa alıcının hangi koşulla imza attığını kendiliğinden öğrenmiş olmaz.',
      'Vessa Thol’a şimdilik bir suçlama göndermedim. İlk raporda üç kaydı, açıklanmış farkı ve açık kalan soruyu ayrı başlıklarla verdim. Bir taraftan cevap isterken ötekinin tanığını dinlemek, sözü güçsüzleştirmek değildir. İşçilerin ücreti gecikiyorsa araştırmanın süresi de zarar doğurur; bu nedenle tartışmalı kısmı bütün teslimi durduracak biçimde ele almak zorunda olmadığımızı sordum.',
      'Bana yardım edecek olanlar ara teslimin tanığını, kullanılan tartının işaretini ve satış koşulunun saklandığı nüshayı arayabilir. Bir tek büyük sır beklemiyorum. Doğru ölçülerin yanında ayrı kararlar bulunabilir. Bu cilt bir hüküm vermek için değil, hükme giden soruların başka bir kâtibe aynı açıklıkla devredilebilmesi için tutuldu. Son kayıt, hangi cevabın hâlâ eksik olduğunu söyler.'),
    ],
  },
  {
    id:'kitap-yapilmamis-yol',title:'Yolu Olmayan Taşlar',subtitle:'Cevher Çizgisi hazırlık defteri',author:'Ivena Sarell',authorId:'ivena-sarell',place:'Ternhaven · Marhalden',placeId:'ternhaven',region:'danstsud',period:'Eryndorn’un saltanatı · proje sonrası inceleme',condition:'kayip',category:'yolculuk',color:'#75876d',motif:'stone',
    note:'Hazırlanmış yol taşları ve yapılmış ödemeler, tamamlanmamış bir güzergâhın çevresinde farklı beklentiler bırakır.',leafTitles:['İşaret taşı','Harcanmış mevsim','Devredilmemiş güzergâh'],marginNotes:['Yol, haritada planlanan hat olarak kalır.','Ödenmiş taş, yapılmış yol değildir.','Burada tarih taşıyan yaprak eksik.'],
    excerpt:[
      page('Ternhaven’in sıcak su kanallarından uzaklaştığımızda işaret taşları soğuktu. İlk taşın bir yanı düzgün, öteki yanı kaba bırakılmıştı. Selvi Arn, bu yüzün yol toprağına gömüleceğini düşündüğünü söyledi. Düşüncesini ölçüm gibi yazmadım. Taşın yerini, üzerindeki aşınmış işareti ve yanında bir arabanın dönebileceği alanın genişliğini kaydettim. Bir projenin adı bulununca bütün çevresini yapılmış yol saymak, bugün burada çalışan insanı yanıltır.',
      'Cevher Çizgisi için hazırlanmış taşların bir kısmı artık hanelerin duvarlarında kullanılıyor. Yoldan vazgeçilince malzemenin hangi izinle devredildiğini bilmiyorum. Ocağını onarmış bir aileyi ilk soruda hırsız diye gösteremem. Malzemenin hazırlanması, teslim edilmesi ve başka bir işe ayrılması farklı zamanlarda olmuş olabilir. Bir taşı ilk kesen usta ile onu bugün kullanan kişi aynı kararı vermemiştir.',
      'Mera Sorn, yolun açılmasını bekleyenlerin yalnız cevher satıcıları olmadığını anlattı. Daha kısa erzak yolu, kışlık fiyatları ve bakım için gelen ustaların süresini de değiştirecekti. Bu beklentiyi defterimde ayrı tuttum. Bir fırsatın büyüklüğü, yapılmamasının tek bir nedene bağlı olduğunu göstermeye yetmez. Önce hangi hazırlıkların gerçekten tamamlandığını öğrenmek gerekiyor.'),
      page('Bir ücret yaprağında taş kesimi için ödeme görünüyordu. Bir diğerinde aynı yerin yol teslimi boştu. Bu iki kayıt birlikte bir hileyi gösterebilir, tamamlanmış hazırlıkla tamamlanmamış inşaatı da gösterebilir. Tarih taşıyan kenar kopmuş olduğundan ikisinin hangi karardan önce yazıldığını henüz bilemiyorum. Kopyanın eksikliği, işin kendisinin gizli tutulduğunu kanıtlamaz. Aynı ödeme başka bir meclis kaydında karşılık bulabilir.',
      'Marhalden’e ulaşacak hattın kullanılabilmesi için yalnız bu taraftaki taşın hazırlanması yetmez. Geçidin kabulü, bakımın kimde olduğu ve güvenli yükün hangi sırayla geçeceği de konuşulmuş olmalı. Şehir kapılarının mülteci girişine kapanmasıyla yol projesinin her işinin aynı gün durduğunu varsaymadım. İnsanlar büyük olayları hatırlarken küçük işlerin tarihini o günün yanına toplayabilir. Tanıkların ayrı hatıralarını bir çizelgede karşılaştıracağım.',
      'Beklerken hazırlanmış bir yükün geri sökülmesi de masraftır. Bir tüccarın geciken kazancı ile bir işçinin almadığı ücret aynı zarar değildir. Taşların bedelini öğrenirken bekleme günlerini de soruyorum. Defterin bu yaprağında bir yolun yokluğu, boş bir manzara olarak görünmesin istedim. Yokluk bazen yapılmış bir hazırlığın, tutulmuş bir sözün ve ödenmiş bir mevsimin üzerinde durur.'),
      page('Kemiğe Basan Yol uzun ve güvensiz duraklarıyla yürümeye devam ediyor. Onun varlığını Cevher Çizgisi’nin zaten gereksiz olduğunu söylemek için kullanamam. Hangi yükün hangi mevsimde taşındığına bakılmalı. Bir insanın sırtındaki küçük çuval ile cevher arabası aynı geçişi kullanamayabilir. Vyssgard’in güvenliği, Frostbay’de bekleme ve Dranthol’ün denetimi her taşıyıcının hesabında başka ağırlık taşır.',
      'Araştırmaya katılacak yolcuların ilk işi taşları söküp getirmek olmasın. Yerlerini ve işçiliklerini karşılaştırabilir, ödeme kaydının ikinci nüshasını sorabilir, taşı kesen ile teslimi kabul eden kişiyi ayrı dinleyebilirler. Sıcak su ustasının taşla ilgili bilgisi ile geçit görevlisinin kabul kaydı birlikte okunmalıdır. Bunlardan biri eksikse öteki kendiliğinden yalan olmaz.',
      'Son varağın tarih bölümü kayıp. Buraya bir tamamlanma tarihi yazmıyorum. Yol haritada hâlâ projedir; bu sayfalar da onun yerini tutmaz. Bir sonraki yolculuğumda yalnız neden yapılmadığını değil, hangi kısmının bugün başka bir işe yarayabileceğini soracağım. Geçmişin hesabını açmak, bugünün yolcularına tutulamayacak yeni bir söz vermeyi gerektirmez.'),
    ],
  },
  {
    id:'kitap-besinci-duvar',title:'Beşinci Duvarın Dilekçesi',subtitle:'Bir mahalle başvurusunun yolculuğu',author:'Sela Orven',authorId:'sela-orven',place:'Valdareth · Sabançeper',placeId:'valdareth',region:'danstsud',period:'Eryndorn’un saltanatı · güncel yazıcı defteri',condition:'eski',category:'arastirma',color:'#ad825a',motif:'wall',
    note:'Ödemesi yapılmış bir hizmet için iki masadan geri dönen başvuru. Mahalle adları, sınır çizgileri ve bekleyen haneler birbirine bağlanır.',leafTitles:['İmzanın öncesi','İki masanın arasındaki sokak','Başvuru numarası'],marginNotes:['Yazıcı, başvuru sahibinin yerine konuşmaz.','Eski yer adıyla yeni sınır aynı şey değildir.','Bir cevap, hizmetin yerine geçmez.'],
    excerpt:[
      page('Bir kadın makbuzunu tezgâhıma koydu. Sabançeper’deki su oluğu için ödeme yaptıklarını, ama bakım sırasına alınmadıklarını söyledi. İlk işim onun adına daha sert bir suçlama yazmak olmadı. Hangi hizmet için ne zaman ödeme yapıldığını ve makbuzdaki adı sordum. Söylediği mahalle adıyla kâğıtta yazılan küçük alanın adı farklıydı. İkisini aynı dilekçeye açıkça koydum; bir memur yalnız birini görüp başvuruyu başka yere göndermesin istedim.',
      'Metni bitirince kadına okudum. İkinci cümleyi değiştirmemi istedi: bütün sokağın aynı makbuzu taşımadığını söyledi. İlk anlatırken öyle sanmıştım. Yazıcının yanlış genellemesi, haklı bir başvuruyu kolay reddedilecek bir iddiaya çevirebilir. Bir başvuru ne kadar küçük görünürse görünsün, sahibinin sözüyle teslim edilmelidir. Onun yerine gördüğüm dünyayı anlatırsam kendi defterimi yazmış olurum.',
      'Mahalle bir hizmet isterken ilk zararı bazen sıra için dükkân kapatan kişi öder. Bu nedenle başvurunun kaç kez geri geldiğini de tuttum. Yalnız suyun nereden akacağını sormak yetmiyor; hangi masanın cevap vereceğini ve cevap için hangi kaydın gerektiğini öğrenmek gerekiyor. Bu yaprakta bir sonuç yok. İlk sorunun doğru sahibine ulaşması için atılmış küçük adımlar var.'),
      page('Duvar ustası Erhan Telis eski kapının yerini gösterdi. Bakım listesindeki sınırın o kapıya mı, sonraki sokak düzenine mi göre çizildiğini bilmiyordu. Bilmediğini söylemesi işimizi kolaylaştırdı. Çizimi ölçebiliriz; bir zamanın sınırını öteki zamanın adına bağlamak için kayıt gerekir. Eski duvarın hangi taşını gördüğümüzü not ettim. Bir haritada boş görünen aralıkta bugün üç hane ve odun satan bir tezgâh bulunuyordu.',
      'İlk masa verginin başka bir tahsilat alanına ait olduğunu söyledi. İkinci masa bu sokağın bakım listesindeki adını bulamadı. Her görevli kendi önündeki sayfaya bakarken başvuru arada kalıyordu. Bunun iki görevlinin birlikte kurduğu bir oyun olduğunu söylemek için kanıtımız yok. Bir sınır güncellenip ikinci deftere geçirilmemiş olabilir. Yine de hatanın sebebini bilmemek, mahalleyi hizmet almadan bırakmayı haklı çıkarmaz.',
      'Manorveil’in kraliyet tahsilatıyla bir loncanın belirli iş için aldığı ücret aynı kayıt değildir. Makbuzu okuyunca bu ayrımı tekrar sordum. Kralın hazinesine giden para ile yerel bir onarım için ayrılan bedelin birbirine karışması, soruşturmayı yanlış kapıya götürebilir. Ödeyen kişinin bunu önceden bilmemesi anlaşılır; açıklamanın görevi kaydı tutanda olmalıdır. Başvuruya önce makbuzun hangi yetkiyle verildiğini öğrenme isteğini ekledik.'),
      page('Teren Halvek’in çalışma masasından bize bir başvuru numarası geldi. Numara, oluğun açıldığı anlamına gelmiyor; fakat artık yazımızın nerede beklendiğini sorabiliyoruz. İaşe işleri için sokağa gelen arabaların yolu da bu bakımın gecikmesinden etkileniyordu. Sera Neld’in görevlisine bunu ayrı bir teslim sorunu olarak bildirdik. Bir kurumun işini ilgilendiren kısmı anlatmak, o kuruma bütün başvurunun kararını vermek değildir.',
      'Yardım etmek isteyen yolcular üç farklı izden başlayabilir: makbuzun karşılık sayfası, eski sınır çizimi veya bakım yapan ekibin teslim kaydı. Bunlardan birinin bulunamaması başvuruyu bitirmez. Komşuların hangi işi gerçekten gördüklerini dinlemek de kayıtların hangi tarihe ait olduğunu sınayabilir. Yeni bir itiraz yazmadan önce kadının metni tekrar duymasını istiyorum; araştırma ilerledikçe bildiğiyle varsaydığı şeyler değişebilir.',
      'Tezgâhımda bu dosyayı bitmiş işler arasına koymadım. Bir mahallenin sorusunu okunur hale getirmek bazen uzun bir iştir. Başkent beş duvarın içinde büyürken dışarıdaki hanelerin adı defterlerde aynı hızla büyümeyebilir. Son yaprağa verdiğim söz yalnız şudur: biri bize cevap verdiğinde o cevabı da başvuru sahibine okuyacağım. Onarım yapılmadıysa cevabın süslü olması, eksik hizmeti tamamlamaz.'),
    ],
  },
  {
    id:'kitap-muhurlu-ruhsat',title:'Mühürlü Ruhsat, Kapalı Kapı',subtitle:'Merkez sicili ile yerel uygulama',author:'Neral Thes',authorId:'neral-thes',place:'Theramis · Elorwyn',placeId:'elorwyn',region:'danstsud',period:'Eryndorn’un saltanatı · karşılaştırmalı hukuk notları',condition:'eski',category:'arastirma',color:'#797493',motif:'seal',
    note:'Geçerli bir ruhsatın Elorwyn’deki denetim sırasında neyi kanıtladığı, neyi tek başına açıklamadığı üzerine araştırma.',leafTitles:['Üç ayrı belge','Uygulamanın yeri','Kapsamı soran mektup'],marginNotes:['Eğitim, üyelik ve ruhsat ayrı kayıtlardır.','Yerel denetim krallık kanununu kendiliğinden kaldırmaz.','Metin araştırması büyü yapma yetkisi değildir.'],
    excerpt:[
      page('Önüme gelen kopyada bir akademinin adı, bir loncanın işareti ve bir uygulama ruhsatının kaydı birlikte duruyordu. Bunları aynı izin sayan yolcu, hizmet vereceği yerde yanlış anlaşılabilir. Eğitim bir bilgiyi öğrenmiş olduğunu, üyelik bir kuruma bağlılığını, ruhsat ise hangi uygulamayı hangi kapsamda yapabileceğini gösterir. Birindeki eksik, öteki iki belgeyi kendiliğinden sahte yapmaz. Yine de hepsinin bir arada bulunması sınırsız yetki vermez.',
      'Theramis’te Mavena Riel, bir sınavın sonucuyla uygulama kaydının aynı gün tutulmayabileceğini anlattı. Bana örnek usulü gösterdi; onu yaşayan bir kişinin gizli sicili gibi çoğaltmadım. Bu kitap bir büyünün nasıl yapıldığını öğretmiyor. Bir belgeyi okurken hangi soruyu sormamız gerektiğini gösteriyor. Metinleri karşılaştırabiliyor olmam, kendimin o hizmeti yapmaya yetkili olduğum anlamına gelmez.',
      'Krallıkta ruhsatlı büyü hizmetlerinin yasal oluşu, her uygulamanın her yerde soru sorulmadan yapılacağını söylemez. Elorwyn’de yerel denetimin sertliği bilinir. Bu sertliği bütün krallık için yeni bir yasak gibi yazarsam hem merkez kaydını hem yerel uygulamayı yanlış anlatmış olurum. İlk yaprağı bu ayrımı açık tutmak için ayırdım. Şimdi asıl soru, belirli bir olayın hangi uygulama sayıldığıdır.'),
      page('Elorwyn’den gelen mektup bir kişinin denetim için durdurulduğunu söylüyordu. Nerede ve ne yaptığına ilişkin satır kısa bırakılmıştı. Bir şifa hizmetiyle kamuya açık bir alanda izinsiz değiştirilmiş başka bir düzen aynı değerlendirmeyi gerektirmeyebilir. Uygulamanın sonucu, belgenin kapsamı ve yerel görevlinin yetkisi ayrı araştırılmalıdır. Ruhsatın üzerindeki mühür bunların hepsini bir bakışta anlatmaz.',
      'Orena Vel’den denetimde hangi kaydın istendiğini, Seldric Nove’den kullanılan yerel nüshanın tarihini sordum. İkisine aynı suçlamayı göndermedim. Bir görevlinin usulü, başka bir masanın metniyle uyumlu olmayabilir; bunun sebebini bulmadan birini kötü niyetli saymak araştırmayı kapatır. Fakat metnin eskiliği uygulamada verilen zararı görünmez de kılamaz. Bir hizmet durdurulmuşsa buna muhtaç kişinin ne yaşadığı kayda girmelidir.',
      'Sayfa kenarına yazılan teyit sözcüğü üzerinde duruyorum. Bir kopyada asıl hükmün parçası gibi, başka bir kopyada görevlinin notu gibi duruyor. Hangisinin önce olduğunu henüz bilmiyorum. Cilt değişirken bir notun satıra alınması mümkündür. Bu ihtimali baştan doğru ilan etmiyorum; mürekkep, bağ yeri ve ilgili tarih kayıtları birlikte karşılaştırılmalıdır. Bir eski hata, bugün ona dayanan kararın neden verildiğini açıklayabilir.'),
      page('Lethan Orve’nin merkez sicil düzenine başvurarak uygulama kapsamının hangi kayıtla teyit edileceğini soruyorum. Bir merkez cevabı yerel hizmetin bütün sorumluluğunu üstlenmeyebilir. Rahela Dorn’un çevresinde bakım bekleyen kişilerin anlatısı da önemlidir: denetim süresinin insanlar üzerindeki etkisini yalnız belge sayısıyla öğrenemeyiz. Böyle bir incelemede halkın ihtiyacı ve hukukun sınırı aynı masada görünmelidir.',
      'Yardım edecek yolcular nüshanın eski tarihli eşini, ruhsat kapsamının merkez karşılığını veya uygulamayı gören bağımsız tanıkları bulabilir. Tek bir metin eksikse öteki yollar açık kalır. Bir belgenin geçerli olmasıyla yapılan her işin izin içinde kalması arasındaki farkı koruyalım. Aynı şekilde yerel bir görevliden kuşku duymamız, bütün denetimin anlamsız olduğunu göstermez.',
      'Defteri kapatırken ne yeni bir büyü kanunu yazıyorum ne bir lordun hükmünü kendi başıma kaldırıyorum. Bilgi sahibinin yetkisini abartması, okumaya çalıştığı metnin sınırını ilk kendisinin ihlal etmesidir. İlgili masaların hangi cümleyi hangi tarihle kullandığını açık tutabilirsek insanlar bir sonraki kapıda aynı soruyu yeniden kaybetmeyebilir. Bu nüsha bir sonuçtan önce, doğru cevabın kimden isteneceğine ilişkin bir haritadır.'),
    ],
  },
  {
    id:'kitap-donmeyen-devriye',title:'Bineğin Getirdiği Sessizlik',subtitle:'Dorvenhall devriye izleri',author:'Ivena Sarell',authorId:'ivena-sarell',place:'Dorvenhall',placeId:'dorvenhall',region:'danstsud',period:'Eryndorn’un saltanatı · dağ yolculuğu notları',condition:'eski',category:'yolculuk',color:'#61747a',motif:'stone',
    note:'Bir devriyenin bineği sürücüsüz döner. Hayvanın yorgunluğu, yükü ve eyerindeki izler bildirilen rotayla tam uyuşmaz.',leafTitles:['Boş eyer','Hayvanın yol bilgisi','Dönüş kaydını aramak'],marginNotes:['Orvelin dört ayağı ve iki parçalı toynağı vardır.','Bir toynak izi, bütün yolculuk değildir.','Canavar saldırısı henüz doğrulanmadı.'],
    excerpt:[
      page('Orvel kapıya geldiğinde üzerinde kimse yoktu. İlk söylenen söz devriyenin bir saldırıya uğradığıydı. Mümkündü; ama hayvanın geri gelmesi saldırıyı kendi başına göstermiyordu. Eyerin sağ bağı yerinde, sol yük askısı gevşekti. Terbiyeci Sira Norrel önce suyu ve dinlenme yerini hazırladı. İnsanlar hemen hayvanı yeniden yola sürmek istediğinde onları durdurdu. Geri dönen bir canlıyı bütün cevapların hazır taşıyıcısı sanmak, elimizdeki en önemli izi de tehlikeye atabilir.',
      'Devriye kaydı kuzey yamacında kısa bir dönüş gösteriyordu. Hayvanın yorgunluğu bu sürenin tamamını başka bir şey olmadan geçirdiğini düşünmeyi zorlaştırıyordu. Bunun ölçüsünü yalnız bakışımla çıkaramam. Sira, yem ve dinlenme düzenini önceki günlerin teslimiyle karşılaştırdı. Bir yolun uzunluğu kadar hayvanın ne taşıdığı ve ne zaman beslendiği de önemliydi. Aynı yamaçta boş gidenle yükle dönen orvelin gücü aynı görünmez.',
      'Borren Keld’den eksik devriyenin son görüldüğü yere ilişkin açık kayıt istedim. Bir tanığın anlattığını bir görevlinin aktardığıyla birleştirip iki tanık saymayacağım. Aynı haber kapıdan kapıya dolaşınca daha fazla kanıt olmuş gibi görünebilir. Bu defterin ilk işareti, duyduğum her sözün ilk sahibini öğrenmek için bırakıldı.'),
      page('Orvelin geniş iki parçalı toynağı kayalıkta işe yarar; her buzda tutunacağına güvenilemez. Dört ayağının dengesi ağır yükü tehlikesiz yapmaz. Sira’nın incelediği bacaklarda dinlenmeden önce gördüğümüz titreme, uzun hareketten veya yorucu zeminden doğmuş olabilir. Bu durumu hayvanın korkusuna tek başına bağlamadık. Korkunun şekliyle yorgunluğun bedeni bazen aynı duruşta görünür.',
      'Eyerin altında düz bir çizik vardı. Yanında yeni çamur, kayışta ise kuru bitki artığı görülüyordu. Bunların hepsinin son yolculukta oluştuğunu bilmiyorum. Önceki bakım kaydı, eski çizikle yeni hasarı ayırmaya yardım edebilir. Talvena Kord bitkiyi ve taş tozunu bulunduğu yerde karşılaştırmanın daha anlamlı olacağını söyledi. Torbadaki örneğin tek başına hangi yamaçtan geldiğini ilan etmek istemiyorum.',
      'Endrik Vaun’un dönüş çizelgesindeki boşluğu okurken nehrin doğu ve batı tarafını da ayırdım. Dağ sırasını tek yüz gibi anlatan bir yol kaydı hava farkını saklayabilir. Aldara’nın ortak buzul kaynakları iki yöne su verir; bir kıyının erişilebilirliği ötekine taşınmaz. Çok yüksek zirveyi geçmekle korunaklı alt yamaçta dolaşmak da aynı yürüyüş değildir. Devriyenin hangi rakımda kalması beklendiğini öğrenmeliyiz.'),
      page('Dönmeyen insanların adını bu açık nüshaya kayıp ilanı gibi yazmıyorum; ailelere ulaşan haberin hangi kayıttan geldiğini henüz bilmiyoruz. Önce arama için izin ve güvenli bir güzergâh belirlenmeli. Borren’in yetkisi sınır nöbeti içindir, bir araştırmacının merakı adına her işçiyi yerinden alamaz. Yine de bir raporun eksikliği aramayı durdurmamalıdır. Kapı kaydı, bakım defteri ve son bağımsız tanık farklı başlangıçlar verir.',
      'Yolcuların yardım edebileceği iş, bineği zorla iz sürdürmekten önce bu üç başlangıcı karşılaştırmaktır. Gevşek askının hangi yük için kullanıldığını, çizelgede rotanın ne zaman değiştiğini ve kıyıdaki işçilerin devriyeyi hangi yönde gördüğünü sorabilirler. Bir iz bulunamazsa hayvanın yem kaydı başka bir zaman aralığını gösterebilir. Saldırı, kaçakçılık veya yanlış emir ihtimallerinin her biri ayrı kanıt ister.',
      'Bu yaprakta bir canavarın adını vermiyorum. Bazen hayvanın anlattığını düşündüğümüz şey, kendi korkumuzdur. Dorvenhall’in tepelerinde güvenlik, gözlem kadar dönme sınırını bilmeyi de gerektirir. Arayan kişi devriyenin yaptığı hatayı tekrar etmesin. Son satırı yola çıkacaklar için yazdım: nerede geri döneceğinizi, bulmak istediğiniz şey kadar açık söyleyin. Bir insanı ararken başka bir kayıp oluşturmak araştırmanın amacı olamaz.'),
    ],
  },
]
