import type { Section } from '../data';

type Life = { age: string; past: string; goal: string; fear: string; limit: string; encounter: string };
// New public biographical development. Player backgrounds and private identities are untouched.
export const characterLife: Record<string, Life> = {
  eryndorn: { age: '50’li yaşlarının başında', past: 'Caedren’in sarayında çocukken aynı kış için iki hesap görmüştü: ambarın doluluğu ve kapıya gelen aç aileler. İkisinin birlikte doğru olabileceğini fark etmek, onu hazır cevaptan çok kaynağa bağladı. Bugün masasında bir eksik rapor kaldığında dinlenmeyi sonraya iter; bilgi arayışı zihnini keskin tutarken kararlarının insani bedelini dar bir hesapta görmesine de yol açar.', goal: 'Tacın karşı karşıya olduğu tehlikeleri anlayıp yönetimi ayakta tutmak.', fear: 'Bilmediği bir şey yüzünden engellenebilir bir felakete izin vermek.', limit: 'Gerekçesiz karar vermeyeceğini söyler; fakat acil gördüğü ihtiyaçta kendi gerekçesini yeterli sayması çevresini zorlar.', encounter: 'Oyuncular bir keşif veya yerel sorun için doğrudan söz değil, doğrulanabilir bulguyla heyet kabulüne girebilir.' },
  alisande: { age: '40’lı yaşlarının ortasında', past: 'Saray hizmetinde bir kış şöleninin erzağı son anda başka depoya yönlendirilince Alisande ilk kez mutfak kaydını ambar teslimiyle birlikte okudu. Herkes onu geciken sofra yüzünden hatırlarken o yükçünün ödenmemiş gününü not etti. Bu alışkanlık, yardım işlerinde görünmeyen masrafı sormasını sağlar; bazen hızlı bir iyilik isteyen kişiye fazla ayrıntı sorar.', goal: 'Saray yardımını düzenli teslim ve gerçek ihtiyaçla buluşturmak.', fear: 'Yardımın gösteriye dönüşüp ertesi hafta aynı haneyi desteksiz bırakması.', limit: 'Bir teslimi yapılmış gibi göstermeyi kabul etmez; kralın öncelikli araştırması aynı yükü istediğinde pazarlık etmesi gerekir.', encounter: 'Bir yardım konvoyunda eksik kalan malın alıcısını ve teslim saatini arayan heyetle karşılaşırlar.' },
  ilyenne: { age: '20’li yaşlarının başında', past: 'İlk hukuk alıştırmasında aynı dilekçeyi önce yalnız unvanlarıyla, sonra başvuranların işleriyle okudu. Hocalarının kabul ettiği cevabın dış surdaki aileye neye mal olduğunu anlayınca dosyayı tekrar sordu. Merakı ona dikkatli bir öğrenci olmayı öğretir; saraydan çıktığında herkesin aynı açıklıkla konuşmayacağını henüz öğrenmektedir.', goal: 'Bir kararın şehirde nasıl uygulandığını öğrenmek.', fear: 'İnsanların yalnız hanedan adına bakarak ona doğru olmayan şeyler söylemesi.', limit: 'Bilmediği bir konuda hüküm vermemeye çalışır; sarayın ondan kesin konuşmasını beklediği törenlerde zorlanır.', encounter: 'Dilekçe heyetinde tanık veya okulun gözlem gezisinde rehber olabilirler. İlan edilmiş veliaht değildir.' },
  mirelda: { age: '40’lı yaşlarında', past: 'İlk hanedan görüşmelerinden birinde doğru söylenmiş bir emir, yanlış oturma sırası yüzünden hakaret sayıldı. Mirelda o gün çözümün yalnız iyi cümle değil, dinlenen kişinin kendi usulünü tanımak olduğunu öğrendi. Sonraki yıllarda lord ailelerinin kelimelerini kaydetti; bu sabır ona kapı açarken sert kararı geciktirdiği suçlamasını da getirdi.', goal: 'Kraliyet kararlarının lordluklarda uygulanabilir biçimde anlaşılmasını sağlamak.', fear: 'Küçük bir onur kavgasının vergi ve asker yükümlülüğünü kesmesi.', limit: 'Krala verilmemiş bir sözü onun adına vaat etmez; görüşmeyi kurtarmak için belirsiz ifade kullanma baskısı görür.', encounter: 'Bir lordluk heyetinin refakatinde veya beraat kapsamını açıklayan görüşmede bulunabilirler.' },
  'maelis-dervan': { age: '50’li yaşlarında', past: 'Bir zamanlar beklenen vergiye dayanılarak verilen küçük onarım emri, tahsilat gecikince ustaları aylarca ücret bekletti. Maelis sonradan o hesabı kapatırken gerçekleşecek gelirle eldeki parayı ayrı sütunlara aldı. Bu yöntem hazineyi daha okunur kıldı; acil yardım talebinde aynı titizlik merhametsiz görünebilir.', goal: 'Taahhütlerin gerçekten ödenebildiği bir harcama düzeni kurmak.', fear: 'Bugünün görkeminin yarının ödenemeyen ücretine dönüşmesi.', limit: 'İsmi ve teslimi olmayan gideri onaylamaz; acil durumda tanıklı geçici kayıt arar.', encounter: 'Bir köprü, konvoy veya donanma ödemesinin dayanağını getirirlerse masasından yanıt alabilirler.' },
  tharion: { age: '50’li yaşlarının sonunda', past: 'Tharion aile yönetimini öğrenirken bir yerel iznin iki farklı gelenekle yorumlandığı görüşmeye katıldı. Hane adına verilen sözün sokakta aynı anlaşılmadığını gördü; daha sonra denetimi dar ve yazılı tutmayı tercih etti. Bu tercih sadık eski ailelere güven verirken dışarıdan gelen uzmanlara ağır bir kapı oluşturur. Valerius’un yükselişi bu kapının adil olup olmadığını daha görünür kılar.', goal: 'Elorwynder yönetiminin meşruiyetini ve şehrin güvenliğini korumak.', fear: 'Bir yanlış izin yüzünden hem halkın hem eski hanelerin güvenini yitirmek.', limit: 'Yerel usulün incelenmesini ister; ruhsatlı hizmeti bütün krallıkta yasaklama yetkisi yoktur.', encounter: 'İzin itirazı, refakat görevi veya yerel bir hane görüşmesi onun yönetim çevresine götürür.' },
  damian: { age: '40’lı yaşlarının sonunda', past: 'Gençliğinde bir kış yükünün limanda günlerce beklemesinin saray sofrasından önce işçi hanesini etkilediğini gördü. Liman yönetiminde teslimin günü onun için unvan kadar önemlidir. Aveline hane ilişkisini taşırken Damian yük akışını korumaya çalışır; kendi hanesinin önceliği başka teknenin hakkını geride bırakabilir.', goal: 'Kethra limanının güvenilir teslim yeri olarak kalması.', fear: 'Tüccarların güveni azalınca bakım ve ücret düzeninin birlikte çökmesi.', limit: 'Güvenli olmayan tekneyi sırf hane yükü yetişsin diye çıkarmaz; gecikme gelir kaybına dönüştüğünde zorlanır.', encounter: 'Rıhtım sevki, bir kıyı şikâyeti veya Rook’un arazi izni üzerinden hane kabulüne ulaşılır.' },
  aveline: { age: '40’lı yaşlarının ortasında', past: 'Bir fırtına haftasında saray davetlerini erteleyip konuk odalarını bekleyen kıyı heyetine açtırdı. Sonraki gün kimlerin gerçekten geldiğini hizmetkârların kısa notundan öğrenince hane takvimini liman haberine bağladı. İnsanları hatırlaması güçtür; tanıdığı aileye öncelik vermesi yabancının işini zorlaştırabilir.', goal: 'Hane görüşmelerinin kıyıdaki gerçek ihtiyacı kaybetmemesi.', fear: 'Aile ilişkilerinin sözle sürüp gerekli işin hiç yapılmaması.', limit: 'Damian’ın vermediği resmî yetkiyi kendi adına dağıtmaz; konukların ondan hızlı çözüm beklemesi baskı yaratır.', encounter: 'Ticaret veya aile adına gelen ziyaretçiyi ilk dinleyen muhataplardan biridir.' },
  rook: { age: '20’li yaşlarının ortasında', past: 'Arazisine ilk düzenli sınır taşı koydurduğunda ustalar eski duvarı kırmak istedi. Rook çizginin kısa kısmını dolandırmayı seçti; hem masrafı arttı hem eski iz kaldı. Taşın ne anlattığını hâlâ bilmez. Sahiplik belgesinin bilgiye eşit olmadığını bu küçük pahalı karar ona öğretti.', goal: 'Rydorn mülkünde güvenli geçiş ve anlaşılır arazi sınırı oluşturmak.', fear: 'Bir onarım yüzünden geri getirilemeyen kalıntıyı yitirmek.', limit: 'Arazi araştırmasını bütünüyle yasaklamak istemez; izinsiz kazı gördüğünde kapıyı kapatabilir.', encounter: 'Bir rehber, taş ustası veya araştırma heyetinin geçiş izni için konuşurlar.' },
  'rovan-mereth': { age: '50’li yaşlarının başında', past: 'Bir sır mineralinin iyi fiyatla satılması kötü yük paketlemesini gizleyince gelen şikâyet Dorvenhall’ın bütün ustalarına döndü. Rovan teslim zincirini yeniden inceletip ucuz sevkten vazgeçti. Bu karar sonraki siparişleri korudu, kısa vadede bazı taşıyıcıları işsiz bıraktı; onu herkes aynı nedenle desteklemez.', goal: 'Ocak, işleme ve taşıma arasında sürdürülebilir gelir kurmak.', fear: 'Kaynağın ucuz satılıp işçiliğin ve kent itibarının aynı anda aşınması.', limit: 'Emniyetsiz ocağı yalnız sevk sözü için açtırmayacağını söyler; kraliyet çatısı beklediğinde baskı artar.', encounter: 'Yük refakati, ocak emniyeti veya mineral fiyatı görüşmesinde karşılaşırlar.' },
  'averen-dhal': { age: '40’lı yaşlarında', past: 'Lonca görevini şehir emri sanan bir kervan alıcısı zararın tümünü lordlukta arayınca Averen iki kaydın kapsamını ayrı dinledi. Lonca ile idare arasındaki ilişkiyi bu olaydan sonra görev isimleriyle tarif etmeye başladı. Kurumların bağımsızlığını korur; taraflardan biri hızlı müdahale istediğinde yavaş görünür.', goal: 'Lirendil’in lonca, pazar ve sivil yönetiminin birbirini boğmadan çalışması.', fear: 'Özel görev anlaşmasının bütün şehrin hukuku yerine geçmesi.', limit: 'Lonca iç disiplinini keyfi emirle yönetmez; sivil zarar büyürse ortak denetim ister.', encounter: 'Bir kervan sözleşmesinin şehir hizmetiyle kesiştiği itirazı dinler.' },
  'elyas-theren': { age: '40’lı yaşlarının sonunda', past: 'Bir kamu hizmeti için en ünlü ustanın adını yazmak yeterli sanılmış, fakat usta aynı gün dağ bakımında bulunmuştu. Elyas başarısız teslimden sonra yetenek kadar görev takvimini sormaya başladı. Solan’ın uzmanlığına saygı duyar; loncanın bütün kaynaklarını kent adına sahiplenmemeye çalışır.', goal: 'Bilginin güvenli ve zamanında kamu hizmetine dönüşmesi.', fear: 'İtibarın gerçek hizmet kapasitesiyle karıştırılması.', limit: 'Öğrenciyi usta yerine imza vermeye zorlamaz; acil iş için hazır ruhsatlı uzman bulmak bazen daha pahalıdır.', encounter: 'Hizmet takvimi, güvenlik kaydı veya okul ile şehir arasındaki izin sorunu onu ilgilendirir.' },
  'varlen-neth': { age: '40’lı yaşlarının ortasında', past: 'Yeni gelen bir usta eski işini yapabiliyor fakat pazar kaydında adresi olmadığı için tezgâh açamıyordu. Varlen geçici tanıklı kayıt yoluna razı oldu; yerli esnaf bunu yeni rekabet olarak gördü. Brannis’in büyümesini yalnız nüfus değil, her yeni kapının iş ve su ihtiyacı üzerinden okumaya çalışır.', goal: 'Vergi, pazar ve artan barınma ihtiyacını aynı kentte sürdürebilmek.', fear: 'Güven kaybıyla yerli esnafın ve yeni hanelerin karşı karşıya gelmesi.', limit: 'Göçmeni yalnız kökeninden dolayı suç kaydına yazdırmaz; düzen isteyen öfkeli kalabalık onu zorlar.', encounter: 'Pazar yeri, teslim tanıklığı veya yeni bir hanenin geçici kaydı için başvurulur.' },
  'garran-veyl': { age: '40’lı yaşlarının başında', past: 'Kale tamamlandıktan sonra ilk boş dükkânları gördüğünde garnizon başarısının pazar başarısı olmadığını anladı. Korsan akışı azalırken han ve tamirciler eski geliri yitirmişti. Garran güvenliği geri gevşetmek istemez; bakım işlerini yerel ustaya açık teslimle vermek küçük ama uygulanabilir cevabıdır.', goal: 'Güçlü nöbeti sürdürürken kentle iş ilişkisini koparmamak.', fear: 'Ücreti ödenen askerin etrafında yaşayacak esnafın kalmaması.', limit: 'Korsan ticaretini sırf gelir için korumaya almaz; azalan hizmet geliri birlik iaşesini zorlayabilir.', encounter: 'Fener sevki, kale bakımı veya sivil yükün nöbetle çatıştığı işte muhataptır.' },
  'mera-sorn': { age: '40’lı yaşlarında', past: 'Sıcak su oluğunun küçük onarımı bir hanenin avlusunu kestiğinde Mera yalnız ortak yarardan konuşmanın yetmediğini gördü. İş payını ve zararı ayrı saydırdı; göreli sıcaklığın insanlar arasında kendiliğinden adalet kurmadığını öğrendi. Mecliste sözleri sakin, hesabı ayrıntılıdır.', goal: 'Ternhaven’in küçük ortak işlerinin gerçekten bitmesini sağlamak.', fear: 'Büyük yol vaadinin bugünkü bakım emeğini de tüketmesi.', limit: 'Yapılmamış hattı tamamlanmış teslim diye imzalamaz; yatırım bekleyen haneler hız ister.', encounter: 'Kanal bakımı, taş kullanımı veya kıyı ürünlerinin ortak sevkinde bulunur.' },
  'vessa-thol': { age: '40’lı yaşlarının sonunda', past: 'Bir maden teslimini yalnız satış satırından onayladığında kazı vardiyasının ek işi görünmez kalmıştı. Vessa işçi tanıklığını istemeyi o günden sonra usule ekledi. Dört yıllık makamı ona süreli güç verir; kayıt tutmak bu gücün başka kola devredilebilmesini de sağlar.', goal: 'Üç üretim kolunun birbirinin hesabını okuyabildiği bir düzen kurmak.', fear: 'Bir kolun fiyatı, tartıyı ve seçimi aynı elde birleştirmesi.', limit: 'Ücret bekleyen vardiyanın tanıklığını atlamaz; sevkin tutulması başka işçilerin ücretini de geciktirebilir.', encounter: 'Kalite, tartı veya üç kolun karşılıklı teslim anlaşmazlığında çağrılır.' },
  'odran-vehl': { age: '50’li yaşlarında', past: 'Bir liman nöbetini güçlendirmek için dış sokak devriyesini çektiğinde hanelerden iki farklı teşekkür ve şikâyet aldı. İki yerde aynı anda bulunamayacağını o haftanın defterine açık yazdı. Nöbet hesabı iyidir; bunu güvenliğin her yerde eşit olmadığını kabul ederek yapması gerekir.', goal: 'Sınırlı garnizonla en ağır tehlikeleri azaltmak.', fear: 'Kaynak eksiğinin yokmuş gibi raporlanması ve sonraki kaybın erlere yüklenmesi.', limit: 'Kentin tümünü güvenli ilan etmez; vekilin düzen görüntüsü isteğiyle çatışabilir.', encounter: 'Bir arama, posta refakati veya nöbet değişimi için gerçek rota ister.' },
  'nera-veld': { age: '40’lı yaşlarının başında', past: 'Frostbay’e gelen ilk hizmet talebinin bölgenin uzak bir kıyısına ertesi gün ulaşacağını sanmıştı. Haber ancak ikinci tekneyle dönünce bağlılık kaydıyla ulaşılabilir alanı ayrı işaretlemeye başladı. Bu alışkanlık dürüst plan sağlar; merkezde bazıları onu isteksizlik sayar.', goal: 'Yapabileceği hizmeti güvenilir biçimde teslim etmek.', fear: 'Verilmiş sözün insanları daha güvenli bir plan yapmaktan alıkoyması.', limit: 'Ulaşılamayan köye yardım yapılmış gibi kayıt açmaz; kâğıt üzerinde iyi sonuç isteyen merkez baskısı vardır.', encounter: 'Sınırlı sevk, yapı kullanımı ve gümrük-posta ihtiyacının aynı odaya sığması için başvurulur.' },
  'edran-korr': { age: '50’li yaşlarının ortasında', past: 'Kazı çevresinden gelen bir erzak talebini satış geliriyle çözeceğini düşünmüş, taşıma gecikince paranın yiyeceğe eşit olmadığını görmüştü. Sekiz yıllık görevinde kapı ve stok hesabını birlikte takip eder. Mülteci girişini kapatma kararını kaynak korumasıyla savunur; bu karar kapının iki yanında farklı hayatları ağırlaştırır.', goal: 'Geçidi ve kentin erzak dayanıklılığını korumak.', fear: 'Bir kriz sırasında hem kapı hem ambar düzeninin dağılması.', limit: 'Ticaret ve yerleşme iznini aynı saymaz; aileleri ayrılanlar karşısında bu ayrımın bedelini dinlemek zorundadır.', encounter: 'Sevk heyeti, lonca karşı tanıklığı veya giriş başvurusu onun önüne gelir.' },
  'bryndon-kiyi-defteri': { age: '50’li yaşlarının sonunda', past: 'Bir eski yapının işlevini yalnız biçiminden tanımladığı ilk notu, daha sonra farklı bir kullanım iziyle karşılaştırdı. Defterini düzeltip önceki yorumunu da sakladı. Bugün her ölçünün yanına nerede ve hangi yüzeyde alındığını yazar; bu yöntem kesin hikâye isteyen okuyucuya yavaş gelebilir.', goal: 'Frostbay yapılarının karşılaştırılabilir bir kaydını bırakmak.', fear: 'Kendi yorumunun gelecek kâtip için tartışmasız gerçek hâline gelmesi.', limit: 'Görmediği şeyi görmüş gibi yazmaz; halkın bir büyük geçmiş açıklaması beklemesi onu zorlar.', encounter: 'Duvar ölçüsü, değirmen yatağı veya farklı nüshayı karşılaştıracak saha tanığı arar.' },
  vardek: { age: '60’lı yaşlarında', past: 'Vardek için öğretmek, kılıç sallayan kişiyi görevden dönecek insan olarak tanımaktır. Bir grubun acele sevki sırasında bakım ve hazırlığın ayrılamayacağını görmüş, bundan sonra revirin sözünü görev hesabına katmıştır. Babacanlığının içinde sert bir eşik bulunur: üyeyi sever ama hazır olmadığı işe gönüllü olmasını her zaman kabul etmez.', goal: 'Loncanın üyelerini ve verdiği sözlerin güvenilirliğini korumak.', fear: 'İtibar uğruna üyelerinin gereksiz yere kaybedilmesi.', limit: 'Hazır olmayanı büyük sözleşme için öne sürmez; taç talebi ve lonca geliri bunu zorlayabilir.', encounter: 'Bir görev kabulü, eğitim değerlendirmesi veya yaralı bir üyenin dönüşünde konuşurlar.' },
  kaelen: { age: '40’lı yaşlarında', past: 'Kaelen’in dersinde adım bozan yeni üye, bütün sıranın dengesini etkiler. Bunu bir talim kazasından sonra ilk öğrenilecek konuya çevirdi. Tekrarları öğrenciyi yıldırabilir; fakat iyi yetişmiş bir grubun sağ dönmesi onun verdiği dersin gerçek ölçüsüdür.', goal: 'Yeni üyelerin birlikte hareket edebildiği sağlam bir eğitim kurmak.', fear: 'Yetenekli bir kişinin hatasının bütün ekibi tehlikeye atması.', limit: 'Talimde yaralanmayı başarı saymaz; dışarıdan hızlı sonuç isteyen görev baskısı süreyi daraltır.', encounter: 'Göreve hazırlanırken avluda duruş, kalkan ve sıra düzenini denetler.' },
  vaelcor: { age: '50’li yaşlarında', past: 'Vaelcor bir öğrencinin doğru sonuca yanlış sebeple ulaştığını gördüğünde başarılı denemeyi tekrar ettirdi. İkinci deneme farklı sonuç verince dersin amacı alkıştan açıklamaya döndü. Bir ustanın sorusu bazen öğrenciyi utandırır; o bunu güvenli uygulamaya hazırlığın parçası sayar.', goal: 'Öğrencilerin yaptıkları işin sebebini ve sınırını anlayabilmesi.', fear: 'Başarılı görünen ama tekrarlanamayan bir uygulamanın halka hizmete taşınması.', limit: 'Yeterlilik incelemesini itibarlı bir ailenin isteği için atlamaz; akademinin destek ihtiyacı baskı yaratabilir.', encounter: 'Bir bozuk düzenek, ders gözlemi veya uygulama siciline gönderilecek çalışma üzerinden tanışırlar.' },
  rickon: { age: '50’li yaşlarında', past: 'Bir iç kapıda törensel arabayı önce geçirdiğinde dışarıda hasat yükünün kuyruğu bütün sokağı tutmuştu. Rickon sonraki nöbetlerde yalnız kapı önünü değil ardındaki rotayı da dolaştırdı. Kıdemi küçük gecikmenin nerede büyüyeceğini görmesidir; saray refakatine öncelik vermekle kentin akışını tutmak her zaman uyuşmaz.', goal: 'Beş sur arasında işlemesi gereken geçişleri açık tutmak.', fear: 'Kâğıt üzerinde düzgün nöbetin sokakta yangın veya ezilme riskini büyütmesi.', limit: 'Emanet teslimi olmadan tutukluyu devretmez; kalabalık ve vardiya değişimi bunu zorlar.', encounter: 'Kapı tıkanması, gece tanıklığı veya kayıp bir teslim kaydında karşılaşırlar.' },
  varric: { age: '40’lı yaşlarının başında', past: 'Dravenspire’den taşıdığı sert yol alışkanlığı Lirendil’in ilk büyük görevinde yetmedi; eksik erzak ekibi geri çevirdi. Varric sonraki hazırlıklarda kişisel cesareti yük hesabından ayrı tuttu. Gençlerin gözünde yavaş davranabilir; hazır dönülmeyen bir seferi yeniden yaşamak istemez.', goal: 'Kıdemini ekiplerin gerçekten dönebileceği görevlere aktarmak.', fear: 'Yeni bir üyenin deneyim eksikliğinin gururla örtülmesi.', limit: 'Eksik malzemeyi varmış gibi saydırmaz; loncanın büyük sözleşmesini kaçırmak kişisel itibarına zarar verebilir.', encounter: 'Görev öncesi erzak, geri dönüş veya yeni üyelerin sorumluluk paylaşımını konuşur.' },
  'orren-vask': { age: '50’li yaşlarında', past: 'Orren’in eline bir kez imza zamanı belli olmayan iki aynı mühür nüshası geldi. Emri değil işlem sırasını sorarak hangisinin geçerli teslim olduğunu ayırdı. Bugün bir belgenin gücünü süsünden önce sahibinde ve tarihinde arar; sözlü acele emirlere zor ikna olur.', goal: 'Kraliyet kararlarının sahibini, kapsamını ve zamanını anlaşılır tutmak.', fear: 'Belirsiz bir nüshanın iki lordluğa birbirine zıt emir gibi gitmesi.', limit: 'Verilmemiş emri mühürlemez; saray aciliyeti sözlü talebi yazının önüne koyabilir.', encounter: 'Berat refakati, emir nüshası veya tarih uyuşmazlığı için başvururlar.' },
  'teren-halvek': { age: '40’lı yaşlarının sonunda', past: 'Eski bir sokak başvurusunu doğru makama yönlendirdiğini sanmış, haftalar sonra aynı mühürle geri aldığını görmüştü. Teren yönlendirmenin hizmet sayılmadığını bu olayda öğrendi. Ortak masa kurması işi hızlandırır; hangi bütçeden ödeneceğini sorması hanelere yeni bekleyiş gibi gelebilir.', goal: 'Mahalle taleplerinin teslim edilebilir işe dönüşmesi.', fear: 'Dosyanın kapanıp sokaktaki sorunun aynı kalması.', limit: 'Yetkisini aşan sınırsız ödeme sözü vermez; acil ihtiyaç için tutarı belli geçici çözüm arar.', encounter: 'Dilekçenin iki nazır arasında döndüğü veya kapı bakımının sevki durdurduğu yerde muhataptır.' },
  'sera-neld': { age: '40’lı yaşlarında', past: 'Dolu ambarın yanında ekmek kuyruğu gördüğü bir haftada Sera ürün sayımıyla teslim saatini ayrı istemeye başladı. Tahıl vardı, ama değirmen onarımı ve araba bekleyişi sofraya ulaşmasını kesmişti. O günden beri bolluğu yalnız depoyla ölçmez; bazı tüccarlar bu yakın takibi müdahale sayar.', goal: 'Valdareth’in ekmek zincirini sürdürmek.', fear: 'Depo rakamının aç mahalleyi görünmez kılması.', limit: 'Bozuk ürünü ucuz ekmek vaadi için dolaşıma sokmaz; kısa kıtlıkta fiyat ve güven arasında baskı yaşar.', encounter: 'Bir sevkin kaybı, fırın sırası veya ambar-değirmen bağlantısı için yardım ister.' },
  'doran-kest': { age: '50’li yaşlarının başında', past: 'İyi bağlanmış bir yükün yanlış kapıya teslimi günlerce rıhtımı tuttu. Doran bundan sonra yükün varlığından önce hangi masanın onu kabul edeceğini yazdırdı. Limanın akışını koruyan usul, geciken geminin kaptanına gereksiz kâğıt gibi görünebilir.', goal: 'Rıhtım, tartı ve kent kapısının aynı yükü aynı kayıtla tanıması.', fear: 'Bir küçük kabul hatasının liman kuyruğunu bütün şehre taşıması.', limit: 'Donanma adına olmayan yükü askerî sevkmiş gibi işlemez; hane önceliği isteyenler bunu zorlar.', encounter: 'Gümrük tartısı, yanaşma sırası veya hasarlı teslim için görüşülür.' },
  'lethan-orve': { age: '40’lı yaşlarının ortasında', past: 'Bir eğitim belgesinin hizmet ruhsatı sanıldığı başvuruda Lethan aynı mührün üç farklı anlamını karşılaştırdı. Sicilini eğitim, üyelik ve uygulama kapsamı olarak ayırması buradan doğdu. İyi bir uzmanın yanlış evrak yüzünden beklemesi onu da rahatsız eder; bunun için açıklayıcı karşı nüsha üretir.', goal: 'Ruhsat sahibinin hangi işi nerede yapabildiğini görünür tutmak.', fear: 'Belirsizliğin hem tehlikeli uygulamayı hem haksız engeli büyütmesi.', limit: 'İncelemeden kapsam genişletmez; acil bakım ihtiyacı daha hızlı teyit aramaya iter.', encounter: 'Şehirler arası ruhsat uyuşmazlığı veya okul belgesinin hizmet kaydı için başvurulur.' },
  solan: { age: '60’lı yaşlarının başında', past: 'Bir iklim desteğinin işe yaradığı ilk gün kutlandıktan sonra düzenin sürekli bakım istediği unutulmuştu. Solan devam hesabını uygulamanın parçası saymayı o deneyimden öğrendi. Ustalığı güçlüdür; aynı anda Marhalden’e bakım ve Theramis’e ders vaat edemeyeceğini kabul eder.', goal: 'Bilginin öğretilebilir ve sürdürülebilir uygulamaya dönüşmesi.', fear: 'Geçici başarının kalıcı güvence sanılması.', limit: 'Güvenliği denenmemiş işi yalnız unvanıyla onaylamaz; kamusal beklenti ve ustaların zamanı baskı yaratır.', encounter: 'İklim bakım heyeti, ustalık sınavı veya başka şehrin teknik hizmet talebinde karşılaşırlar.' },
  valerius: { age: '20’li yaşlarının sonunda', past: 'Elorwyn’de genç bir şövalyenin başarısının eski ailelerin sözü kadar hızlı kabul görmediğini yaşadı. Valerius görünür hizmetle itibar toplamayı seçti; böylece rekabeti söze değil yapılan işe bağladı. Yükselişi ona destek verirken kendisini sürekli kanıtlama ihtiyacı ölçüsünü zorlar.', goal: 'Elorwyn’de duyulan ve ciddiye alınan bir siyasi ağırlık kazanmak.', fear: 'Başarılarının hanedan alışkanlığı altında görünmez kalması.', limit: 'Yanındaki kişinin yeteneğini kendi ününün süsü saymamaya çalışır; önemli kabulde bütün ışığın kendisinde olmasını isteyebilir.', encounter: 'Refakat, kamuya açık talim veya yerel bir hane görüşmesinde Rina’yla birlikte bulunur.' },
  rina: { age: '20’li yaşlarının ortasında', past: 'Bir refakat işinde gösterişli ilk hareket yerine geri dönüş aralığını tutarak görevin tamamlanmasını sağladı. Rina bundan sonra yalnız ne kadar hızlı olduğunu değil ekibin neye ihtiyaç duyduğunu sormaya başladı. Valerius’a yakın hizmeti ona görünür konum verir; kendi değerinin sadece yaver unvanıyla anlatılmasını sevmez.', goal: 'Verilen görevi ustalıkla ve kendi muhakemesini koruyarak bitirmek.', fear: 'Yeteneklerinin başkasının her görüşüne katıldığı sanılması.', limit: 'Duymadığı emri verilmiş gibi aktarmamaya çalışır; hareket anında hızlı yorum gerekmesi baskı yaratır.', encounter: 'Valerius’un refakat hazırlığında, ekipman kontrolünde veya bir geçişin emniyetini incelerken tanışırlar.' },
};

export const characterLifeSections = (id: string): Section[] => {
  const life = characterLife[id];
  return life ? [
    { title: 'Bir seçimin izi', paragraphs: [`${life.age}. ${life.past}`] },
    { title: 'Bugünkü amacı ve sınırı', paragraphs: [life.goal, `Kaybetmekten korktuğu: ${life.fear}`, life.limit] },
    { title: 'Nerede karşılaşılır?', paragraphs: [life.encounter] },
  ] : [];
};
