import type { LoreArticle } from '../data'
export const lirendilInstitutions: LoreArticle[] = [
  { id: 'celikkalkan-loncasi', name: 'ÇelikKalkan Loncası', kind: 'institution', region: 'danstsud', subtitle: 'Bir kale, bir sofra, bir yemin', mapLocation: 'lirendil',
    summary: 'Lirendil’de yerleşkesi bulunan ÇelikKalkan, eğitim, görev ve dayanışma çevresinde yaşayan bir loncadır. Büyük Üstat Sir Vardek’in yönetimindeki yapı, demirhane ve revirden arşive uzanan ortak bir gündelik hayat barındırır.',
    sources: ['21.11.2025 aruzhar bolum 1.docx · genel lonca yaşamı', 'Karakterler/ · Vardek ve Kaelen notları', '8 Ekim 2026 yazar kişi eşleştirmeleri'],
    related: ['lirendil', 'vardek', 'kaelen', 'varric', 'mrog', 'ghorin', 'zylara', 'ellyn', 'gil', 'jeremiah', 'volomiyr'],
    sections: [
      { title: 'Kapıdan içeri', paragraphs: ['Lonca yerleşkesi, dışarıdan görülen bir askerî yapıdan daha fazlasıdır. Eğitim avlusu, yemek masaları, bakım odaları ve çalışma yerleri aynı insanların gününü farklı saatlerde doldurur. Kılıcın yanında temiz bir yatak, sıcak yemek ve sağlam bir çift çizme de görev hazırlığının parçasıdır.', 'Lirendil lordunun şehir yönetimi ile loncanın kendi iç düzeni ayrı yetki alanlarıdır. Loncanın güçlü olması, kenti yöneten lordun veya şehir kurumlarının ortadan kalktığı anlamına gelmez.'] },
      { title: 'Üstat, yüzbaşı ve kıdemliler', paragraphs: ['Sir Vardek, ÇelikKalkan’ın Büyük Üstadı’dır. Krala yeminli olsa da lonca üyelerini “oğullarım” diye anması, bağlılığının yalnızca saraya değil, yaşayan bir topluluğa yöneldiğini gösterir.', 'Yüzbaşı Kaelen sert eğitimi ve disiplin yaklaşımıyla tanınır. Varric Draven kıdemli rütbeler çevresindedir; Sessiz Mrog muhafız yaşamının daha az konuşan yüzüdür. Birlikte aynı kurumu taşırlar, fakat aynı kişiliğe sahip değildirler.'] },
      { title: 'Bir kılıcın arkasındaki eller', paragraphs: ['Ghorin’in ocağı donanımın işçilik tarafını, Zylara’nın reviri bakım tarafını görünür kılar. Eğitimde yorulan beden, görevde zarar gören zırh ve kayıt altına alınması gereken malzeme aynı gün içinde farklı ustalara gider.', 'Ellyn Marowen’in baş arşivci kimliği, yazılı hafızanın da kentte bir ağırlığı olduğunu gösterir. Bir kurum yalnızca hatırladığı kahramanlarla değil, tuttuğu kayıtlarla da süreklilik kazanır.'] },
      { title: 'Aynı masada üç maceracı', paragraphs: ['Dorvenhallli Gil, zeki ve umursamaz Jeremiah ile Elorwynli paladin Volomiyr, bugün Lirendil’deki aynı lonca çevresindedir. Farklı kökenlerini ortak bir eğitim, sofra ve görev ritmi içinde taşırlar.', 'Bu yakınlık şehirler arasındaki bağı harita çizgisinden çıkarıp insana dönüştürür. Dorvenhall’ın ustalığı, Elorwyn’in katı gelenekleri ve Lakbar’a gitmiş bir gezginin deneyimi, bir yemekhanede karşılaşabilir.'] },
      { title: 'Yemin ve gündelik sorumluluk', paragraphs: ['Lonca onuru yalnızca bir törende söylenen söz değildir. Görev dönüşünde eksik kişiyi sormak, donanımın bakımını yapmak ve yeni gelenin aynı sofrada yer bulmasını sağlamak da bu kurumun görünür hayatıdır.', 'Büyü kullanılan hizmetlerde krallığın ruhsat düzeni geçerlidir. Bir lonca adı, uygulayıcıya sınırsız yetki vermez; eğitim, üyelik ve hukuki izin birbirinin yerine geçmez.'] },
    ] },
  { id: 'lirendil-buyu-akademisi', name: 'Lirendil Büyü Akademisi', kind: 'institution', region: 'danstsud', subtitle: 'Kale şehrinin başka bir ustalığı', mapLocation: 'lirendil',
    summary: 'Lirendil’de büyü eğitiminin verildiği akademi. Magister Vaelcor, ustalarından biridir; şehrin askerî ve zanaat kimliğinin yanında ayrı bir bilgi çevresi oluşturur.',
    sources: ['8 Ekim 2026 yazar kararı · Magister Vaelcor', 'Danstsud büyü ruhsatları · yazar kanonu'], related: ['lirendil', 'vaelcor', 'buyu-ruhsatlari', 'theramis', 'elorwyn'],
    sections: [{ title: 'Ustanın bilgisi', paragraphs: ['Magister Vaelcor’un yer aldığı akademi, büyüyü yalnızca etkisinden ibaret görmeyen bir eğitim çevresidir. Uygulayıcının sınırı, hazırlığı ve gözlemi de öğrenmenin parçasıdır.', 'Askerî eğitimle tanınan bir kentte akademinin bulunması, Lirendil’in yalnızca kılıç üreten bir yer olmadığını gösterir. Aynı şehir bir örs ustasını, bir arşivciyi ve bir büyü ustasını barındırabilir.'] }, { title: 'Okuldan sokağa', paragraphs: ['Eğitim belgesi ile uygulama ruhsatı ayrı kayıtlardır. Akademide öğrenen kişinin şehir dışında hizmet verebilmesi, izin verilen alanla sınırlıdır. Kurban ritüelleri hiçbir okul unvanıyla yasal hâle gelmez.', 'Elorwyn’in sert yerel büyü denetimi ile Lirendil’in akademi hayatı, aynı krallıkta farklı toplumsal yaklaşımların nasıl yan yana yaşadığını gösterir.'] }] },
  { id: 'rydorn-sirti', name: 'Rydorn Sırtı', kind: 'geography', region: 'danstsud', subtitle: 'Kıyı yolları, sıcak su ve eski taşlar', mapLocation: 'rydorn-sirti',
    summary: 'Danstsud kıyı yerleşimlerinin gerisinde uzanan sırt. Ternhaven’in sıcak suları Rydorn çevresiyle ilişkilidir; harabelerin bulunduğu arazinin sahibi Damian’ın oğlu Rook Valdenar’dır.',
    sources: ['Aruzahr 8k (1).jpg · Rydorn Sırtı', 'Hardlane yazar kararları', '8 Ekim 2026 kişi eşleştirmesi · Rook Valdenar'], related: ['kethra', 'ternhaven', 'rook', 'damian'],
    sections: [{ title: 'Sırtın kıyıdaki karşılığı', paragraphs: ['Rydorn adı, haritada kıyı kentlerinin gerisindeki yüksekliklerle birlikte görünür. Deniz yolunun insanı limana taşıdığı yerde kara yolu da bu yükseltilerin çevresini hesaba katmak zorundadır.', 'Ternhaven çevresindeki sıcak sular daha ılıman küçük yaşam alanları oluşturur. Bu yerel avantaj, bütün Hardlane’in ikliminin yumuşadığı anlamına gelmez.'] }, { title: 'Harabeler ve mülkiyet', paragraphs: ['Rook Valdenar, sırt üzerindeki harabelerin bulunduğu arazinin sahibidir. Sahiplik, bütün dağ sırasının veya her sıcak su kaynağının tek kişinin elinde olduğu anlamına gelmez.', 'Eski taşlar bir geçmişin izini, arazi kaydı ise bugünün ilişkisini taşır. Bu iki katmanı birlikte düşünmek, harabeyi yalnızca boş bir eski bina olmaktan çıkarır.'] }] },
]
