import type { Section } from '../data';

export const speciesGuides: Record<string, { habitat: string; behaviour: string; human: string }> = {
  'orvel-kaya-binegi': { habitat: 'Dorvenhall’ın dağ ve tepe otlakları; kaya basamakları ve yem bulunabilen vadiler.', behaviour: 'Otçul küçük sürüler; dikkatli basış, dinlenme durağını öğrenme ve tehlikeli zeminde durma.', human: 'Dengeli hafif binici ve sınırlı yük. Soğuk, buz ve yemsizlikte güvenilirliği azalır.' },
  kumkavis: { habitat: 'Xotar’ın kuru kum ve vaha çevresi.', behaviour: 'Geniş tabanlı sürü otçulu; şafak ve akşam beslenir, sıcak saatte kaya dibinde dinlenir.', human: 'Yıllarca kullanılan patikası geçişi gösterir; bu iz yüklü arabanın da geçebileceğini kanıtlamaz.' },
  'miraz-ipekcisi': { habitat: 'Xotar’ın vaha bitkilerinin nemli kök çevresi ve Miraz su yollarına yakın alt tabaka.', behaviour: 'Larva organik artıkla, ergin bitki salgısıyla beslenir; serin akşamda kısa uçuşlarla kök değiştirir.', human: 'Kum İpeği elde etmek koloninin besinini ve yeniden çoğalmasını korumayı gerektirir.' },
  'yel-kuyruk': { habitat: 'Murgul’un korunaklı kıyı ve nehir ağızları; tatlı ve az tuzlu su yakınındaki kök oyukları.', behaviour: 'Dört ayaklı su memelisi; bıyıklarıyla kabuklu avını bulur, yassı kuyruğuyla yön değiştirir.', human: 'Taş üstünde biriken boş kabuklar dinlenme yerini gösterir. Kirlenen kıyı aile grubunu yerinden eder.' },
  'buzkulak-serdi': { habitat: 'Honud’un besin bulunan soğuk düzlük ve vadi kesimleri.', behaviour: 'Küçük otçul; kısa beslenme çıkışları ve çok çıkışlı kar tünelleriyle enerjisini korur.', human: 'Tomurcuk ve kabukla beslenir. Sert don tünelleri kapatır; açık deniz buzu güvenli sığınağı değildir.' },
  'taskiran-canakgagasi': { habitat: 'Garmirk’in kayalık yamaçları ve korunaklı çıkıntıları.', behaviour: 'Kalın gagalı kuş; salyangoz ve böceğin kabuğunu aynı yassı taşta açar, yavru bunu taklit ederek öğrenir.', human: 'Sofra taşındaki kırık kabuklar insanın alet işi sanılabilir; yuvası yağmur almayan kaya rafındadır.' },
  'golgeli-varnak': { habitat: 'Garmirk’in kuru ve korunaklı mağara oyukları; alacakaranlıkta av bulunabilen çevre.', behaviour: 'Böcekçil mağara memelisi; yankıyla av bulur, soğukta toplu dinlenip yağ rezervini kullanır.', human: 'Dinlenme grubunu uyandırmak sınırlı kış rezervini tüketir; mağara ziyareti sessiz ve seyrek tutulmalıdır.' },
  ruzgaryazari: { habitat: 'Ariki’nin rüzgârlı ada ve kıyıları.', behaviour: 'Uzun dar kanatlı deniz kuşu; yüzeyden balık kapar, kaya rafta az sayıda yavru büyütür.', human: 'Tekne artığı için gemiyi izleyebilir; ağ ve yağlı artık zarar verir. Fırtınayı şaşmaz biçimde haber vermez.' },
  'yariksirt-varsak': { habitat: 'Gurbin’in kayalık ve yarıklı kıyı kesimleri.', behaviour: 'Düşük gövdeli pusu yırtıcısı; güçlü kısa çene kapanışı vardır, uzun kovalamaya uygun değildir.', human: 'Kaya plakaları pusuyu gizler. Soğukta yavaşlar; açık kıyı ile dar av kovuğu aynı riskte değildir.' },
  'koz-sirtli-neral': { habitat: 'Lakbar’ın sıcak kaya ve besin bulunan volkanik alanları.', behaviour: 'Küçük dört ayaklı sürüngen; böcek ve larva yer, sıcak taşla serin çatlak arasında dolaşır.', human: 'Terrakota sırt çizgisi alev değildir. Gaz veya suyun yön değiştirmesi yumurta oyuklarını kullanılamaz kılar.' },
  'kara-yel-arisi': { habitat: 'Lakbar’ın bitki ve korunaklı yuva bulunabilen kesimleri.', behaviour: 'Koyu renkli tozlaştırıcı; çiçek özü ve polen toplar, aşırı sıcaklıkta yuvada hava dolaştırır.', human: 'Reçineli ağacın kesilmesi, duman ve aşırı toplama koloniyi birlikte etkiler; alevde uçan bir arı değildir.' },
  'teyra-tarakbaligi': { habitat: 'Teyra’nın tatlı su ve uygun akıntı kesimleri.', behaviour: 'Duyu bıyıklarıyla taş arasında beslenir, temiz çakılda yumurtlar; kışın derin ve yavaş suya çekilir.', human: 'Su çekimi sığ kollarda balığı sıkıştırır; kıyıyı düzlemek yavrunun korunağını azaltır.' },
};

export const speciesExpansion: Record<string, Section[]> = {
  'orvel-kaya-binegi': [{ title: 'Devriyenin yük ve mevsim hesabı', paragraphs: [
    'Yeni saha taslağında yetişkin orvelin kütlesi yaklaşık 300–430 kg, omuz yüksekliği yaklaşık 1,55 metredir. Dorvenhall bakıcıları olağan devriye için binici ve eşyayı birlikte yaklaşık 70–90 kg aralığında tutar. İyi beslenmiş yetişkin kısa, elverişli hatta yaklaşık 100 kg taşıyabilir; bu değer dar buzlu geçit veya kesintisiz bütün gün tırmanış için izin değildir. Yaş, sağlık ve eyer dengesi sayının önüne geçer.',
    'Yem bulunabilen yaklaşık 1.200–3.500 metre kuşağı çalışma taslağıdır; hayvan Karlan’ın 13.000 metrelik doruğunda sürekli yaşamaz. Korunaklı durak ve kuru yemle olağan soğukta çalışabilir. Yaklaşık −15 °C’nin altında vardiya kısalır; −25 °C’ye yaklaşan açık rüzgârda uzun devriye yerine barınak ve dönüş planı gerekir. Bunlar evrensel biyolojik eşik değil, korucuların ihtiyatlı saha kurallarıdır.',
    'Çözülme mevsimindeki çamurda iki geniş tırnak çifti belirgin çıkar; dar geçitte kısa adım aralıkları görülür. Bir dinlenme noktasında otlama izinin, eyer pedinin sürtünmesinin ve geri dönüş basışının birlikte bulunması yolculuğu anlatır. Yavru ilk yılında annesinin izini öğrenir; yük ve binici eğitimine bedeni olgunlaşmadan başlanmaz. Ucuz binek almak bakım ve yem giderini ortadan kaldırmaz.',
  ] }],
};
