// Extensions to the author's tax catchments. Population figures are fictional
// working estimates, not a census; the authority and production links retain
// the already curated settlement lore.
export const villageLife: Record<string, { population: string; exports: string[]; title: string; scene: string; tension: string; hardlane?: boolean }> = {
  pilorn: { population: '≈ 2.400', exports: ['Tahıl', 'Harman', 'Kuru ambar'], title: 'Harmanın etrafında', scene: 'Pilorn’da günün ilk sesi harmana dönen öküzlerin ve ambar kapısına yanaşan arabaların sesidir. Tahılın kuruması, çuvalın sağlam kalması ve yükün doğru tartılması, hasat kadar önemlidir. Kışa girmeden ayrılan ambar payı, küçük yerleşimin ertesi mevsime hazırlanmasını sağlar.', tension: 'İyi hasat tek başına iyi gelir değildir. Taşıma gecikirse tüccarın fiyatı düşebilir; ambar nemlenirse hem satışa ayrılan ürün hem de aynî vergi kaybı aynı hanelerin üzerine biner.' },
  fehar: { population: '≈ 1.700', exports: ['Süt ürünleri', 'Büyükbaş', 'Deri'], title: 'Sütün yetişmesi gereken sabah', scene: 'Fehar’ın işi otlakla şehir kapısı arasındadır. Sağım sabah erken yapılır; süt, peynir ve hayvan pazarı aynı sürüye farklı değerler verir. Bir hanenin geliri yalnızca kaç hayvanı olduğuna değil, kışlık yemini nasıl hazırladığına da bağlıdır.', tension: 'Kötü yem yılı sürünün geleceğini daraltır. Başkentte et pahalı olduğunda sürüyü satmak kazançlı görünebilir; ertesi yıl süt verecek hayvanın azalması ise daha yavaş görülen bir bedeldir.' },
  gaalmire: { population: '≈ 1.300', exports: ['Han hizmeti', 'Depolama', 'Yük aktarımı'], title: 'Bir gece kalan yükler', scene: 'Gaalmire’de han avlusu bir küçük pazar gibi çalışır. Araba tekeri onarılır, yük kısa süreli ambara alınır, yolcu bir sonraki kapının durumunu öğrenir. Yerleşimin en değerli ürünü bazen satılan bir mal değil, geciken kervanın güvenle bekleyebileceği bir gecedir.', tension: 'Yolun açık olması gelir getirir, fakat aynı avluya çok sayıda yük yığılması kayıp ve anlaşmazlığı da büyütür. Bir tüccarın acele ettiği anda ambar görevlisinin kayıt istemesi, her iki taraf için de somut bir çıkar meselesidir.' },
  naeron: { population: '≈ 1.900', exports: ['Sebze', 'Nehir yükü', 'Mavna emeği'], title: 'Su ile pazarın arasında', scene: 'Naeron’un bahçeleri nehirden gelen suyla yaşar. Sepetler taze ürünü, mavnalar daha ağır yükleri taşır. Toprakta çalışan kişiyle kıyıda ip çeken kişi, aynı ürünün farklı aşamalarını paylaşır.', tension: 'Taşkın bahçeyi besleyebilir, aynı taşkın kıyı iskelesini kullanılamaz hâle de getirebilir. Taze ürün bekleyemez; bir geçişin gecikmesi, kuru tahıl yükünden daha çabuk kayıp yaratır.' },
  fevric: { population: '≈ 1.100', exports: ['Un', 'Arpa', 'Bira hazırlığı'], title: 'Rüzgârın ücret aldığı yer', scene: 'Fevric’in yeldeğirmenleri, tarlanın ürününü başkentin mutfağına yaklaştırır. Değirmenci havayı, çiftçi hasadı, taşıyıcı yolu izler. Arpa işleme ve bira hazırlığı, işçi hanelerinin günlük erzağına uzanan küçük bir üretim zinciri kurar.', tension: 'Rüzgârın uzun süre dinmesi, taşın veya kanadın onarımı, un sırasını uzatır. Aynı gün değirmene gelen her çuval önce öğütülmek ister; bekleme sırası yerel bir düzen meselesidir.' },
  theld: { population: '≈ 2.100', exports: ['Tahıl', 'Bakliyat', 'Mevsimlik emek'], title: 'İki yerde yaşayan haneler', scene: 'Theld’de bazı hanelerin yılı ikiye ayrılır: hasatta tarlada, durgun mevsimde başkentin işlerinde çalışırlar. Bakliyat ve tahıl, ailenin sofrasıyla pazar yükünü aynı toprağa bağlar.', tension: 'Şehirde ücret yükseldiğinde tarla emeğini azaltmak cazip olur; hasat gecikirse bu kez hane ürünü kaybeder. İki gelir kaynağı, her zaman iki güvence anlamına gelmez.' },
  korhenden: { population: '≈ 1.400', exports: ['Araba onarımı', 'Koşum', 'Hayvancılık'], title: 'Kırık tekerin küçük başkenti', scene: 'Korhenden’de iyi bir teker, bir tüccarın düşündüğünden daha fazla emek taşır. Ahşap seçilir, birleşim kontrol edilir, koşum yenilenir. Hayvan ve araba işi aynı yerleşimde buluşur; ürünün ovadan çıkabilmesi bu küçük bakım dünyasına bağlıdır.', tension: 'Onarım ustaları bir büyük sevkiyata yetişmeye çalışırken yerel hanelerin araçları bekleyebilir. Başkentten gelen siparişin bedeli iyi olsa da köyün kendi hasat arabası kırık kalırsa kazancın bir bölümü geri kaybolur.' },
  uldar: { population: '≈ 1.500', exports: ['Hayvan ticareti', 'Erzak', 'Taşıma'], title: 'Geçide hazırlanan pazar', scene: 'Uldar, Karlan’ın doğusunda daha iyi iklimden yararlanan bir erzak yerleşimidir. Hayvan pazarı ve ticaret, Marhalden’in az üretilebilen yiyeceğine karşılık verir. Yola çıkacak yükler yalnızca tartılmaz; soğukta korunacak biçimde hazırlanır.', tension: 'Geçit kenti erzak ister, fakat bütün yolculuklar aynı mevsimde kolay değildir. Taşıyıcının aldığı risk, dağdaki bir sofra için ödenen fiyatın parçasına dönüşür.' },
  tolvur: { population: '≈ 1.200', exports: ['Hayvancılık', 'Yün', 'Erzak sevki'], title: 'Sürünün ve yükün hesabı', scene: 'Tolvur’un doğu yamaçlarında hayvancılık ve yük ticareti birlikte yürür. Evcilleşmiş Orvakların bakımı, kırpımı ve yavru büyütmesi uzmanlık ister. Sürü, yalnızca bir sonraki sevkiyatın gücü değil, hanelerin uzun vadeli geçimidir.', tension: 'Ağır bir kervanı taşımak için fazla hayvan ayırmak, otlak ve yem yükünü artırır. Güçlü bir Orvak da dinlenmeye ve besine ihtiyaç duyar; bir tüccarın acelesi bu ihtiyacı ortadan kaldırmaz.' },
  toran: { population: '≈ 1.000', exports: ['Yem', 'Ticaret', 'Erzak'], title: 'Dağın sofrasına giden çuvallar', scene: 'Toran’da yem ve erzak hazırlığı, kervanın kendisi kadar önemlidir. Kuru mal ayrı, nemden zarar görecek yük ayrı tutulur. Doğudaki daha iyi koşullar, Marhalden’in yüksek rakımlı hayatına somut ürünlerle bağlanır.', tension: 'Bir ambarın iyi görünmesi, içindeki bütün ürünün aynı kalitede olduğu anlamına gelmez. Yükün kaydı ve teslimi arasındaki anlaşmazlık, dağ şehrinin güvenlik kadar erzağa da bağımlı olduğunu gösterir.' },
  harven: { population: '≈ 850', exports: ['Odun', 'Av ürünleri', 'Deri'], title: 'Orman ile nöbetin arasında', hardlane: true, scene: 'Harven’de tarla yerine av izleri ve odun yığınları vardır. Marhalden’den konuşlanan birlik, baskınlara karşı sınırlı fakat önemli koruma sağlar. Bir avın paylaşılmasıyla bir odun yükünün çıkarılması, kışlık hazırlığın iki ayrı yüzüdür.', tension: 'Son dönemde köle ticareti ve yağmada ölenlerin ziynetinden gelir elde edilmesi, yerleşimin geçimine karanlık bir katman eklemiştir. Garnizonun varlığı, bütün ekonomik faaliyetin temiz veya bütün hanelerin aynı işe karıştığı anlamına gelmez.' },
  mavric: { population: '≈ 700', exports: ['Odunculuk', 'Avcılık', 'Post'], title: 'Ateşi söndürmeden yaşamak', hardlane: true, scene: 'Mavric’te kışın işareti yalnızca kar değildir: kurutulan odun, onarılan giysi ve avdan dönecek kişiyi bekleyen ocak da mevsimi gösterir. Tarım yapılmaz. Yerleşimin düzeni, Marhalden bağlantılı birliğin varlığı ve hanelerin kendi hazırlığıyla sürer.', tension: 'Av ve odun gelirinin yanına son zamanlarda köle ticareti ve yağma artığı ziynetler eklenmiştir. Bu karanlık pazar, zor koşulların kendiliğinden herkes için aynı ahlaki seçimlere dönüşmediğini gösterir.' },
}
