import type { LoreArticle, RegionId, Section } from '../data'

export const faunaSource = 'Dünya canlıları · 8 Ekim 2026 yeni yazım; habitat ve insan ilişkileri mevcut halka açık dünya kültürleriyle birlikte geliştirildi'
export const faunaArtMetadata: { id: string; title: string; caption: string }[] = [
  { id: 'orvel-kaya-binegi', title: 'Orvel Kaya Bineği', caption: 'Dorvenhall sınır korucularının dengeli, dört ayaklı dağ bineği' },
  { id: 'kumkavis', title: 'Kumkavis', caption: 'Xotar · geniş tabanlı, uzun kıvrık boynuzlu çöl otçulu' },
  { id: 'miraz-ipekcisi', title: 'Miraz İpekçisi', caption: 'Xotar · Kum İpeği salgılayan küçük vahalık böceği' },
  { id: 'yel-kuyruk', title: 'Yel Kuyruk', caption: 'Murgul · geniş yassı kuyruğuyla yüzen kıyı memelisi' },
  { id: 'buzkulak-serdi', title: 'Buzkulak Serdi', caption: 'Honud · rüzgârdan korunmak için kulaklarını kapatan küçük otçul' },
  { id: 'taskiran-canakgagasi', title: 'Taşkıran Çanakgagası', caption: 'Garmirk · kalın gagasıyla sert kabukları açan kaya kuşu' },
  { id: 'golgeli-varnak', title: 'Gölgeli Varnak', caption: 'Garmirk · geniş kulaklı, böcekçil mağara uçucusu' },
  { id: 'ruzgaryazari', title: 'Rüzgâryazarı', caption: 'Ariki · açık denizde süzülerek küçük balık toplayan deniz kuşu' },
  { id: 'yariksirt-varsak', title: 'Yarıksırt Varşak', caption: 'Gurbin · kayalık kıyı kovuklarında pusu kuran düşük gövdeli yırtıcı' },
  { id: 'koz-sirtli-neral', title: 'Közsırtlı Neral', caption: 'Lakbar · serin kaya oyuklarıyla sıcak yüzey arasında yaşayan küçük sürüngen' },
  { id: 'kara-yel-arisi', title: 'Kara Yel Arısı', caption: 'Lakbar · reçineli ağaçların korunaklı oyuklarında yaşayan tozlaştırıcı' },
  { id: 'teyra-tarakbaligi', title: 'Teyra Tarakbalığı', caption: 'Danstsud · ova nehirlerinde akıntıya karşı duran tarak yüzgeçli balık' },
]

export const faunaBriefs: Record<string, string> = {
  'orvel-kaya-binegi': 'Original fantasy mountain riding herbivore from Dorvenhall. Exactly four legs, barrel chest and strong compact shoulder, long balanced neck shorter than a horse neck, large flexible cloven hooves with broad two-part gripping soles, short backward-curving paired horns, long dark ochre mane over neck and shoulders, slate-brown dense short coat with lighter underside, dark intelligent eyes and small mobile rounded ears. Adult shoulder height about 1.55m, visibly sturdy enough for one light armored ranger and restrained luggage. A wool-padded saddle with low wooden frame and no huge flags. Stands steadily one hoof above another on a broad rocky ledge; misty cool gray mountains and warm paint light. Must not resemble a flying creature or have giant ibex horns. Clearly visible hooves and species anatomy.',
  'kumkavis': 'Original Xotar desert herbivore, an elegant shoulder-high tawny antelope with exactly four slender strong legs, broad two-lobed soft feet for hot sand, a deep barrel ribcage tapering to long legs, two long horns curving outward then backward, not curling as a ram, long low ears with dark tips, closable narrow nostrils, pale cream cheeks and belly against sandy russet upper coat. Slanted dark eyes, no glowing markings. Standing at dusk and turning head toward a young individual off scene, sparse desert scrub and ochre dunes under muted ultramarine shadows. No camel hump.',
  'miraz-ipekcisi': 'Original small desert oasis beetle, body around 3cm long with exactly six jointed legs, oval dull cobalt-brown hard wing cases with a pale ochre rim, two short segmented antennae, tiny head and strong gripping hooked feet. In a magnified painted naturalist composition, show one adult clinging to a root above a sand burrow and one smaller soft pale larva weaving fine cream silk threads around a seed husk. Fine silk is clearly delicate painted thread, no glowing magic; simple dark blue-gray root shadow and soft warm sandy light. No extra limbs or mammalian eyes.',
  'yel-kuyruk': 'Original Murgul coastal aquatic mammal, about 1.1m body length, otter-like narrow chest with strong hind body, four short partly webbed feet, a long horizontally flattened paddle tail broadening toward tip with one darker central ridge, dense chestnut and cream water-resistant coat, short rounded ears and long tactile whiskers. Swimming partly out of teal brackish water beside mangrove-like tree roots, holding a small shell in forepaws, charcoal-violet shadows and gentle ochre reflected light. Tail is not a sail or a wing; no horns.',
  'buzkulak-serdi': 'Original Honud small cold-country herbivore about 45cm long, compact rounded hare-like body but short broad ears that can fold flush along cheeks, thick cream-gray coat with charcoal fur on outer ear margins, short muscular hind legs and wide densely furred feet, tiny round dark eyes, tawny muzzle and a very short tail. One ear slightly raised while other rests along fur as it listens at a snow tunnel mouth. Frozen twig buds and pale lichen at feet, quiet slate-blue snow and warm ivory face light, small-scale tender alertness, not a monster.',
  'taskiran-canakgagasi': 'Original Garmirk cliff bird, stout about 55cm long with a large deep bowl-shaped charcoal beak, dark rust-red throat and mottled slate-cream plumage, thick gripping two-front-two-back toes, strong short wings folded at sides, round dark eyes and a narrow pale brow stripe. Perched on a natural rock anvil holding a small snail shell beneath one foot; a few broken shells around it, wet gray limestone, muted ochre and cool violet-blue side shadows. The beak is biological and not a metal tool; no crest crown.',
  'golgeli-varnak': 'Original Garmirk insect-eating cave flyer, a small mammal with body about 25cm long, leathery wings spanning around 85cm, exactly two arm-wings and two hind legs, unusually broad rounded ridged ears, blunt short muzzle and soft deep charcoal-brown fur with pale whisker area, tiny dark eyes. Resting with wing membranes partly spread near a dry cool cave mouth to show anatomy, warm gray rock and softly painted moth silhouettes in distant air, indigo shadow, subtle warm edge light. No huge fangs, not a vampire demon.',
  'ruzgaryazari': 'Original Ariki ocean bird, 80cm long lean body with narrow long sweeping wings and roughly 1.8m wingspan, deeply forked tail, clean ivory underside, smoky blue-black back and a muted rust patch below beak, long slightly hooked dark bill, dark eyes, small webbed feet folded beneath body. Banking low over blue-green sea in one elegant readable pose, one tiny silver fish beneath bill, softly brushed cloud and warm coral-ochre reflected sunlight. No extra wings or glowing eyes; not a generic huge eagle.',
  'yariksirt-varsak': 'Original Gurbin rock-coast ambush predator, 1.6m body without tail, exactly four short muscular legs with blunt curved claws, low long chest, broad blunt triangular head with biological nostrils and dark amber eyes, smooth dark slate dorsal plates separated by deep flexible russet skin seams, thin broad rudder-like tail, no horns or spikes. Resting half inside a basalt tide crevice with one foreleg on wet stone, mouth closed, quiet threatening weight rather than roaring, muted red-brown and sea-green light with loose indigo-black background. A terrestrial coastal reptilian animal, not a dragon or crocodile copy.',
  'koz-sirtli-neral': 'Original Lakbar small warm-rock reptile about 35cm long, four short splayed legs, slender lizard-like head, long heavy tapering tail storing reserve, matte dark charcoal scales with a broad dull terracotta-orange back stripe, pale ash-gray belly, clear black eyes and round biological pupils, no flaming body. Emerging from a cool shaded fissure beside gently steaming warm basalt, tiny beetle ahead, dry ochre mineral dust and soft plum-gray shadow. The orange stripe is coloration and not molten lava; readable subtle scale planes painted with gouache.',
  'kara-yel-arisi': 'Original Lakbar pollinating bee, small exactly six-legged insect with stout velvety charcoal thorax and dark ochre bands on compact abdomen, two translucent smoky amber wings on each side, short black antennae and small natural compound eyes. Macro-scale hand-painted composition of one bee on a small pale ochre tree flower beside dark sticky resin, a soft second bee near a shaded wood cavity in background. Warm honey-gray painting against deep wine-purple loose shadow, no fantasy glowing sting or human face.',
  'teyra-tarakbaligi': 'Original Danstsud river fish about 40cm long, streamlined silver-gray body with muted olive back, one tall ribbed comb-shaped dorsal fin folding flat, small pectoral fins, muscular forked tail, broad downward-facing mouth with two short sensory barbels, subtle russet fin edges, clear small dark eyes. Shown in three-quarter underwater profile close to rounded river stones with a small larva in riverbed; clear green-blue shallows, soft golden surface light and broad restrained brush shapes. Anatomically one coherent fish, no wings, no duplicate tails.',
}

const chapter = (title: string, ...paragraphs: string[]): Section => ({ title, paragraphs })
const species = (id: string, region: RegionId, mapLocation: string, summary: string, sections: Section[], related: string[] = []): LoreArticle => {
  const art = faunaArtMetadata.find(item => item.id === id)!
  return { id, name: art.title, kind: 'fauna', region, mapLocation, summary, subtitle: art.caption, sources: [faunaSource], sections, related: [...new Set([mapLocation, region, ...related])] }
}

export const newFaunaArticles: LoreArticle[] = [
  species('orvel-kaya-binegi', 'danstsud', 'dorvenhall',
    'Orvel, geniş ve esnek çatallı toynaklarıyla kayaya tutunan, yaklaşık 1,55 metre omuz yüksekliğinde dört ayaklı bir otçuldur. Dorvenhall sınır korucuları onu hızlı hücumdan çok sarp arazide dengeli devriye için yetiştirir.', [
      { ...chapter('Taşa basan ayak',
        'Orvelin gövdesi at kadar uzamaz; derin göğsü ve güçlü omuzları yükü bacaklarına yakın tutar. Her ayaktaki iki geniş tırnak taşın küçük biçim farklarına ayrı ayrı yerleşebilir. Sert dış kenar aşınmaya dayanır, daha esnek iç taban kuru kayaya tutunur. Yeni donmuş yüzeyde bu tutuş azalır: iyi bir orvel, güvenmediği taşa binicisi zorlasa da hemen adım atmaz.',
        'Kısa boynuzları başın gerisine kıvrılır; dar çıkıntıda savrulup kayaya takılacak büyük bir taç oluşturmaz. Sırtı griye çalan kahverengi kısa kürkle, boyun ve omuzları koyu yeleyle örtülüdür. Kalın gövde soğuğa karşı yarar sağlar, fakat yazın uzun tırmanışta su ve dinlenme ihtiyacını artırır.'),
        table: { columns: ['Özellik', 'Gözlem'], rows: [['Yurt', 'Dorvenhall’ın dağ ve tepe otlakları'], ['Beslenme', 'Sert ot, yaprak, az miktarda liken'], ['Beden', 'Dört ayak · yaklaşık 1,55 m omuz'], ['Kullanım', 'Hafif binici, dengeli devriye, sınırlı yük']] } },
      chapter('Sürüde öğrenilen yol',
        'Küçük sürülerde gezer; annesini izleyen yavru taş basışını tekrar ederek öğrenir. Önünü iyi görür, kulaklarını ayrı yönlere çevirerek arkadaki sesi yoklar. Dar çıkıntıda ani bir sese koşarak cevap vermektense başını indirip yerinde kalır. Bu davranış onu çevik olduğu kadar inatçı da gösterir.',
        'Sert ot ve yaprakla beslenir; kıtlıkta liken de alabilir, fakat bütün kışı yalnız çıplak kaya üzerinden geçiremez. Korucuların otlak ile kuru yem hesabı devriye hesabından ayrılmaz. Uzun sıçrayışın yerini dikkatli ayak basma aldığı için orvel, geniş düzlükte iyi bir atın hızına yetişmez.'),
      chapter('Korucunun ikinci eğitimi',
        'Dorvenhall’da genç hayvanlar önce semerin ağırlığına, sonra binicinin denge hareketine alışır. Alçak ahşap semere yün ped koyulur; ağır zırh ve büyük erzak yığını omzu zorlayacağı için tercih edilmez. Gerçek bir dar geçitte hayvan bazen yüksüz geçirilir, binici yükünü kendi taşır.',
        'Yemle verilen ödül işe yarar; ürkütmek ve kırbaçlamak adımı güvenilir kılmaz. Dağ korucusunun itibarı yalnızca silahına değil, bineğini ne zaman geride bırakacağını bilmesine de dayanır. Orvelin burnunu taşa yaklaştırıp beklemesi, efsanelerdeki uçurum sezgisi değil, koku ve zemini birlikte kontrol etmesidir.'),
    ], ['karlan-daglari']),
  species('kumkavis', 'xotar', 'thariz',
    'Kumkavis, uzun geriye açılan boynuzlu ve geniş tabanlı bir çöl otçuludur. Xotar’ın seyrek bitkili kuşaklarında serin saatlerde dolaşır; su tasarrufu uzun süre hiç su içmediği anlamına gelmez.', [
      chapter('Kumda kalan iki iz',
        'Uzaktan ince bacaklarıyla kırılgan görünür, fakat derin göğsünün altında geniş iki parçalı tabanlar taşır. Bu tabanlar yumuşak kumda yüzey alanını artırır; taşlı yamaçta ise daha yavaş yürür. Açık krem yanakları, kum rengi sırtı ve koyu kulak uçları sert ışıkta gövdenin sınırını parçalar.',
        'İki uzun boynuz önce yana, sonra geriye döner. Erkekler birbirini iterek sınar; boynuzun işlevi yalnızca yırtıcıya karşı değildir. Dar çalılıkta takılma riski nedeniyle sürü, sık bitki yerine açık otlak kenarını seçer. Kum fırtınasında ince burun açıklığını daraltabilir, ancak kapalı burunla sürekli koşamaz.'),
      chapter('Serin saatlerin sürüsü',
        'Şafak ve akşamda kısa ot, kuru yaprak ve su tutan bitki sürgünlerini yer. Büyük sıcaklarda gölge oluşturan sığ çukur ve kaya diplerinde dinlenir. Uzun kulaklarıyla sürüdeki uyarı sesini ayırt eder; gelişmiş koku alma yiyeceğe yardım eder, kayıp bir kuyuyu uzaktan bulan mucize değildir.',
        'Yavrular sürünün çevresinde tutulur, yaşlı dişiler tanıdık beslenme duraklarını tekrar kullanır. Aynı patika yıllarca görülebilir. Daren Khoss gibi muhafızlar bu izi zeminin kullanıldığına dair bilgi sayar; hayvanın geçebildiği yolun yüklü arabaya da açık olduğunu varsaymaz.'),
      chapter('Çölle kurulan pazarlık',
        'Kumkavis avı et ve deri sağlar; boynuzlar küçük alet ve süs yapımında kullanılır. Yavaş büyüyen sürünün kurak dönemde fazla avlanması, ertesi mevsim onu geri getirmez. Bazı haneler yavru yetiştirir, fakat tür ağır yük taşımaya uygun bir kervan hayvanı değildir.',
        'Vaha kıyısında ekilmiş sürgünleri yemesi onu çiftçiyle çatıştırır. Gece ışığına ve ani kokuya alışmayan sürü kolay dağılır; kovalanırken yavruların ayrı kalması en büyük kayıptır. Yerel anlatılarda misafirliğe benzetilen bir sabır taşır, gerçek yaşamda ise su ve sessiz otlak arayan hayvandır.'),
    ], ['daren-khoss']),
  species('miraz-ipekcisi', 'xotar', 'sahrim',
    'Miraz İpekçisi, vaha bitkilerinin kök çevresinde yaşayan küçük bir böcektir. Larvasının koruyucu salgısından elde edilen ince lifler, Xotar’ın Kum İpeği işçiliğinde kullanılır.', [
      chapter('Kökün altındaki oda',
        'Ergin böcek yaklaşık üç santimetre uzunluğundadır; mat mavi-kahverengi kanat kapaklarının açık kenarı kumdaki gölgeyi kırar. Altı bacağı kök yüzeyini tutan küçük kancalar taşır. İki kısa antenle nem ve besin izini yoklar; gözleri geniş manzaradan çok yakındaki hareketi algılar.',
        'Yumuşak gövdeli larva köklerin altında küçük bir yuva örer. İnce salgı ipliği kum tanelerini ve kuru kabukları bir arada tutar; bu oda hem nem kaybını azaltır hem küçük avcılara karşı örtü sağlar. İpek, böceğin insan için ürettiği bir mal değil, kendi yaşamını koruyan yapıdır.'),
      chapter('Vahadan uzaklaşmayan yaşam',
        'Larvalar çürümüş bitki parçaları ve kök çevresindeki organik artıklarla, erginler yumuşak bitki salgılarıyla beslenir. Nemli alt tabaka bozulduğunda yumurta ve larvalar yaşayamaz. Miraz su yollarıyla ilişki böceğe bütün çölde serbestçe yaşama gücü vermez.',
        'Erginler kısa mesafede uçup yeni köke geçebilir. En etkin oldukları saat, yüzeyin serinleyip kök çevresindeki nemin hâlâ korunduğu akşamdır. Aşırı sıcak günde saklanmaları ipek üretiminin de mevsime ve bakım koşullarına bağlı kalmasına neden olur.'),
      chapter('İpeğin ince hesabı',
        'Ustalar terk edilmiş yuvalardan lif toplar, yetiştirme yataklarında ise her odanın sökülmesini önlemek için sıra ve süre tutar. Canlı larvanın bütün örtüsünü bir kerede almak kaybı artırır. İyi Kum İpeği, ham lif kadar onu temizleyip eşleyen işçinin bilgisinden doğar.',
        'Rahim Vekk’in satın aldığı ipek işinde en kırılgan halka böcekten önce bazen kök yatağının suyudur. Su payı azaldığında üretim düşer; fiyatın artması yeni larvayı hemen büyütmez. Sahrim ustalarının aletlerini ayrı yerde yıkaması hem küçük canlıyı hem bu geçimi korur.'),
    ], ['rahim-vekk', 'sahira-nemesh']),
  species('yel-kuyruk', 'murgul', 'morihael',
    'Yel Kuyruk, Murgul’un korunaklı kıyı ve nehir ağızlarında yaşayan dört ayaklı bir su memelisidir. Yassı kuyruğuyla yön değiştirir, uzun bıyıklarıyla bulanık suda kabuklu avın yerini bulur.', [
      chapter('Kuyruktaki kürek',
        'Yaklaşık bir metreyi geçen gövdesi ince göğüsten güçlü arka bölüme genişler. Dört kısa ayağın parmakları kısmen perdelidir; yatay yassı kuyruk, kısa itiş ve dönüşte kullanılır. Kuyruk bir yelken gibi sudan kalkmaz. Adını sudan çıkarken rüzgârda açılmış bez gibi göründüğü için almıştır.',
        'Sık kestane renkli dış tüy suyu uzaklaştırır, altındaki daha ince kürk hava tutar. Açık krem boğazı karada tanınmasını sağlar. Uzun bıyıklar taş ve avın yakın hareketini algılar; küçük kulaklar dalışta kapanır. Bu düzen soğuk kısa dalışa yardım etse de hayvanın sonsuz süre su altında kalmasını sağlamaz.'),
      chapter('Kabukların küçük sofrası',
        'Kabuklu canlı, küçük balık ve kıyı böceği yer. Sert kabuğu taş üzerinde tutup ön ayaklarıyla açabilir; aynı düzlükte birikmiş boş kabuklar dinlenme yerini ele verir. Kıyı kökleri ve sığ oyuklar yavrular için korunaklı alan sağlar.',
        'Bir aile küçük kıyı kesimini düzenli kullanır. Gelgit güçlü olduğunda açık denize çıkmak yerine kök aralarında bekler. Tatlı ve az tuzlu suya yakın kalır; bütün gün tuzlu su içerek yaşayamaz. Suyu kirlenen kıyının yerine uygun yeni bölge bulmak her zaman kolay değildir.'),
      chapter('İskeledeki misafir',
        'Morihael’de ağlara yakalanmış avı yemesi balıkçıyı kızdırır, fakat boş bırakılan balık artıklarını temizlemesi de işe yarar. Ağın yanına düzenli yemek bırakmak onu insana yaklaştırıp çatışmayı büyütebilir. Evcil bir tekne maskotu gibi davranması güvenli olduğu anlamına gelmez.',
        'Torren Azhal, yuva yakınındaki eski ağları kaldırır; Ilvara’nın iskele bakımında açık bırakılan kök çevrelerini korumasını destekler. Bu tercih kutsal bir tür ilanı değildir. Aynı kıyıda avın, hayvanın ve insan işinin yerini birbirini tamamen yok etmeden ayırma çabasıdır.'),
    ], ['torren-azhal', 'ilvara-senn']),
  species('buzkulak-serdi', 'honud', 'norrvar',
    'Buzkulak Serdi, geniş tüylü ayakları ve yana yatabilen kısa kulaklarıyla Honud’un kar yüzeyine uyarlanmış küçük bir otçuldur. Sığınakta beklemek ve kısa beslenme çıkışları yapmak, soğuğa dayanmasının temelidir.', [
      chapter('Kapatılan kulak',
        'Gövdesi yaklaşık kırk beş santimetre uzunluğunda, yuvarlak ve yoğun kürklüdür. Krem-gri örtünün iç katmanı ince havayı tutar. Kısa geniş kulakların koyu kenarı, kuytu yerde gün ışığını biraz daha iyi toplar; açık rüzgârda kulaklar yanakların üstüne kapanarak açık yüzeyi azaltır.',
        'Ayak altında da kalın tüy vardır. Geniş arka ayak yumuşak karda derin batışı sınırlar, fakat ince buz üstünde aynı güveni sağlamaz. Küçük gözleri kışın kısa ışığında yakındaki hareketi seçer. Rüzgâr ve avcı sesi için başını sürekli çevirmek yerine bir kulağını kısa süre kaldırır.'),
      chapter('Kışın küçük yiyeceği',
        'Tomurcuk, ince kabuk, liken ve yazdan kalmış bitki parçaları yer. Bu besin az enerji verdiği için uzak yürüyüşü azaltır. Karın altındaki kısa tünelleri birden çok çıkışla açar; sert kabuk oluştuğunda tünel yenilemek hayvana ayrıca emek yükler.',
        'Tek başına beslenebilir, fakat iyi bir sığınakta birkaç birey yan yana dinlenir. Kışı bütünüyle uyuyarak geçirmez. Sert dönem uzarsa zayıf bireylerin kaybı artar; her bir canlının kalın kürkle bütün ayazlara dayanması Honud anlatısının değil, insanın ona yüklediği bir abartıdır.'),
      chapter('Klanın avı, hocanın gözlemi',
        'Küçük av olarak et ve kürk sağlar. Yuvaların bütünüyle boşaltılması sonraki mevsimde çevredeki yiyecek ağını da zayıflatır; yırtıcıların başka av ve hanelere yönelmesi görülebilir. Bazı aileler sığınak çevresini bir mevsim kullanıp başka kesimi dinlendirir.',
        'Haldrun Ylse, tünelin yeni yönünü öğrencilere gösterir. Hayvanın yaptığı değişiklik yakın rüzgârın ve karın durumuyla ilgilidir; gelecek haftanın bütün havasını haber vermez. Buzkulak, insanların dikkat etmeyi öğrendiği küçük bir komşudur, kutsal bir ayaz kehaneti değildir.'),
    ], ['haldrun-ylse']),
  species('taskiran-canakgagasi', 'garmirk', 'stoneclans',
    'Taşkıran Çanakgagası, Garmirk’in taşlık ve nemli yamaçlarında yaşayan kalın gagalı bir kuştur. Yassı taşları sofraya çevirir; kırdığı kabuk ve kemik, yaşadığı çıkıntıyı belli eder.', [
      chapter('Bir gagaya sığan çekiç',
        'Yaklaşık elli beş santimetre uzunluğunda tıknaz bir kuştur. Gagası koyu renkli, yüksek ve derin bir çanak biçimindedir. Alt çenesi kabuğu sabitlemeye, üst bölüm kısa darbeyle açmaya yarar. Boğazındaki pas-kızılı tüyler, gri ve krem taş desenli gövdesinden daha belirgindir.',
        'İki öne, iki arkaya bakan parmağı kayayı kavrar; kalın gagasının ağırlığını dengelemek için başını göğse yakın tutar. Kanatları kısa uçuşta güçlüdür, uzun deniz aşırı süzülüşe uygun değildir. Soğuk ve çok yüksek doruk yerine yiyecek bulabildiği alt yamaçları kullanır.'),
      chapter('Taş sofra',
        'Kara salyangozu, iri böcek, yumurta ve bulduğunda küçük leş parçalarıyla beslenir. Kabuğu düz taşta açmak daha az enerji gerektirdiği için aynı sofra yerini tekrar kullanır. Üzerindeki kırık kabuklar bazen insanların alet çalışmasıyla karıştırılır.',
        'Yuvasını yağmur almayan kaya rafına kurar. Çift, gaga vuruşlarını ve kısa boğuk çağrılarıyla çevresini bildirir. Yavrunun ilk besini kolay açılan küçük avdır; kalın kabuğu parçalamayı yetişkinin hareketini taklit ederek öğrenir.'),
      chapter('Geçitçinin üstünde',
        'Bir yolda kullanılan kaya duvarı sofra seçilirse düşen küçük kabuk ve taşlar geçitçiye zarar verebilir. Keldan Rud’un nöbetçileri yuvaları parçalamak yerine yoğun yürüyüş çizgisindeki gevşek sofraları uzaklaştırır. Bütün kuşlar aynı rafta toplanmadığı için iş tekrar ister.',
        'Garmirk çocukları gaga sesini taş ustasının ritmine benzetir. Bir demirci onu sabrın simgesi yapabilir; gerçek kuş yemin veya üretim öğretisi bilmez. Kendi güçlü gagasının değerini, sert bir avı daha az uğraşla açabilmesinde taşır.'),
    ], ['keldan-rud']),
  species('golgeli-varnak', 'garmirk', 'stoneclans',
    'Gölgeli Varnak, geniş kulaklı ve böcekçil bir mağara memelisidir. Kısa yankı çağrıları karanlıkta yol ve av bulmasını sağlar; soğuk dönemleri korunaklı toplu dinlenmeyle geçirir.', [
      chapter('Karşıdan dönen ses',
        'Yaklaşık yirmi beş santimetrelik gövdenin kanat açıklığı seksen beş santimetreye yaklaşır. İki ön kol ince zar kanada dönüşmüştür, iki arka ayak kaya tutunmasına yarar. Kanat katlandığında uzun parmaklar gövdenin yanına toplanır; dinlenmeye geçen hayvan küçük bir koyu bez gibi görünür.',
        'Geniş yuvarlak kulakların ince kıvrımları geri dönen sesi ayırt etmeye yardım eder. Küçük gözleri vardır; kör değildir. Koyu kahverengi kürk dinlenirken sıcaklığı tutar, fakat zar kanat açıkta hızla ısı kaybeder. Donmuş açık doruklarda bütün gece uçmak türün olağan yaşamı değildir.'),
      chapter('Mağaranın dışındaki yemek',
        'Alacakaranlıkta güve, küçük uçucu böcek ve bazı kaya böceklerini avlar. Çağrısına dönen yankı avın uzaklığını ve hareketini belirtir. Şiddetli yağmurda ya da rüzgârda avlanması zorlaşır; insan kulağına sessiz gelen gece onun için her zaman kolay değildir.',
        'Gündüz kuru ve korunaklı oyuklarda birbirine yakın dinlenir. Soğuk dönemde etkinliğini azaltır, yazdan biriken yağı kullanır. Dinlenme grubunun sık rahatsız edilmesi canlıları uyandırıp bu sınırlı rezervi tüketir. Bir mağarada çok birey görülmesi her yerde aynı sayıda bulunduğu anlamına gelmez.'),
      chapter('Yankının komşuları',
        'Böcek yiyerek çevredeki küçük sürüleri sınırlar; tarımın bütün sorununu tek başına çözmez. Madenciler yeni bir boşluk açtıklarında türün dinlenme alanını da ortaya çıkarabilir. Hava güvenliği ve işe erişim ile canlı yuvasını korumak birlikte düşünülür.',
        'Mirga Senn çocuklara mağara ağzında dinlemeyi öğretir, içeriye bağırıp grubu dağıtmalarını istemez. Varnakların bir yemin şarkısını tekrar ettiğine dair öyküler dolaşır. Gerçekte kendi çağrılarına cevap verirler; duvarda uzayan yankı, karanlıkta bekleyen insana kendi sözünün geri döndüğünü düşündürebilir.'),
    ], ['mirga-senn']),
  species('ruzgaryazari', 'ariki', 'northpact',
    'Rüzgâryazarı, Ariki’nin açık kıyılarında uzun dar kanatlarla süzülen bir deniz kuşudur. Adını hava içindeki kıvrımlı uçuş çizgisinden alır; fırtınayı şaşmaz biçimde önceden bilen bir canlı değildir.', [
      chapter('Gökte ince bir çizgi',
        'Seksen santimetreye yaklaşan gövdenin kanat açıklığı yaklaşık bir metre seksendir. Uzun dar kanatlar ve derin çatallı kuyruk, rüzgâr içinde yön değişimini düşük enerjiyle sürdürür. Üst tarafı isli mavi-siyah, altı açık kremdir; çene altında küçük pas rengi bir alan bulunur.',
        'Kıvrımı az olan uzun gaga yüzeye yakın avı toplar. Küçük perdeli ayak suda kısa dinlenmeye yardım eder; kuş güçlü bir derin dalıcı değildir. Uzun süzülüş için açık hava akımı gerekir, rüzgâr kesildiğinde daha çok kanat çırpıp enerji harcar.'),
      chapter('Balığın üstündeki rüzgâr',
        'Küçük balık, yüzeye çıkmış kabuklu ve fırsat bulduğunda tekne çevresindeki artıklarla beslenir. Avı su üstünden kapar ya da çok kısa yüzey dalışı yapar. Büyük teknenin ardını izlemek yiyecek sağlayabilir, ağ ve yağlı artıkla temas ise zarar verebilir.',
        'Kaya rafta az sayıda yumurtayla yavru büyütür. Çiftler aynı kıyıya dönebilir; taşın çökmesi ya da yoğun ziyaretler yeni yer aramalarını gerektirir. Genç kuşun iyi süzülmesi zaman alır. İlk uçuşun başarısı yalnız kanat biçimine değil, doğru hava ve beslenmeye bağlıdır.'),
      chapter('Kaptanın notu',
        'Yaren Morrik kuşun alçak ve kıyıya yakın uçuşunu nöbet çizelgesinde not eder. Bu davranış rüzgâr veya avın yerini gösterebilir; tek başına her fırtınayı açıklamaz. Denizcinin kendi akıntı, gökyüzü ve tekne gözlemi yerine konulması tehlikelidir.',
        'Ariki’de uzun yolculuk şarkılarında dönüşün simgesidir. Yuvadan genç kuş alınarak bir gemiye bağlanması onu güvenilir rehber yapmaz. Kıyıda yürünen yolun dışında küçük yuva payı bırakılması, özgürlük üzerine söylenen büyük sözün canlıya dokunan küçük karşılığıdır.'),
    ], ['yaren-morrik']),
  species('yariksirt-varsak', 'gurbin', 'hurnreach',
    'Yarıksırt Varşak, Gurbin’in kayalık gelgit kuşaklarında pusu kuran düşük gövdeli bir yırtıcıdır. Koyu sırt plakaları kayanın biçimini andırır; sıcaklık ve su değişimi av saatini sınırlar.', [
      chapter('Kaya gibi duran gövde',
        'Kuyruksuz gövdesi yaklaşık bir metre altmış santimetredir. Dört kısa kaslı bacak geniş göğsü yere yakın taşır. Koyu arduvaz renkli sırt plakaları arasında esnek kızıl-kahverengi deri aralıkları vardır; bu yarık görünümü adını vermiştir.',
        'Baş geniş ve basıktır, gözler koyu kehribardır. Kısa kıvrık pençeler ıslak taşta destek sağlar, ancak düz buz veya kaygan yosunda kusursuz değildir. İnce ve geniş kuyruk sığ suda kısa yön değiştirir. Tür uzun mesafeli açık deniz yüzücüsü değildir.'),
      chapter('Pusunun kısa mesafesi',
        'Kaya kovuğunda saklanıp balık, kıyı kuşu ve küçük memelinin yaklaşmasını bekler. Görüşü hareket seçmede, koku ise yakın leş ve avı bulmada etkilidir. Çenesinin kısa güçlü kapanışı avı tutar; yakalayamadığını kıyı boyunca uzun süre kovalayacak gövdesi yoktur.',
        'Güneşlenen taşla serin kovuk arasında hareket ederek beden sıcaklığını dengeler. Sert soğukta yavaşlar, uzun açlık dönemlerinde etkinliğini azaltır. Yavrular ayrı küçük kovuklara dağıldığından bir yuvanın bulunması yakın her yarıkta aynı tehlikenin olduğu anlamına gelmez.'),
      chapter('Kıyıda karşılaşmak',
        'Balıkçının açık bıraktığı av, hayvanı tekneye yaklaştırabilir. Köşeye sıkışmış birey ya da koruduğu avın yanına girmek en belirgin saldırı koşullarıdır. İnsanların hepsini düzenli avlayan bir ada canavarı olarak sunulmaz.',
        'Vraska Bralk’ın tayfaları dar kovuk önünde yük boşaltmaz ve balık atığını demirleme yerinden uzaklaştırır. Deri ve plaka için avlanır; bütün kıyı yırtıcılarının temizlenmesi küçük avların ve artıkların dengesini de değiştirir. Bir kaptanın varşağa saygısı romantik hayranlıktan çok doğru mesafe bırakmaktır.'),
    ], ['vraska-bralk']),
  species('koz-sirtli-neral', 'lakbar', 'lakbar',
    'Közsırtlı Neral, Lakbar’ın sıcak kaya çevresinde yaşayan küçük, dört ayaklı bir sürüngendir. Terrakota sırt çizgisi alev değildir; sıcak yüzeyden serin çatlağa geçebilmesi yaşamının şartıdır.', [
      chapter('Alev olmayan çizgi',
        'Yaklaşık otuz beş santimetre uzunluğundaki gövde ince başla ağırlaşan kuyruğa uzanır. Dört kısa bacak kayaya yandan basar. Mat kömür renkli pulların üstünde geniş, donuk turuncu bir çizgi vardır; açık kül rengi karın zemine yakın kalır.',
        'Kuyruk yağ rezervi taşır, derinin ince pulları su kaybını sınırlar. Bunun bedeli sıkı sıcaklık aralığıdır. Neral lav içinde yüzmez, kaynar su içmez ve çok sıcak gazdan zarar görür. Serin yarığa geri dönemediğinde ısınan kayanın üstünde kalmak onu öldürebilir.'),
      chapter('Sıcaklığın iki yanı',
        'Küçük böcek, larva ve yumuşak gövdeli kıyı canlılarını yer. Yakın hareketi gözle, zemindeki ince titreşimi ayak ve gövde temasıyla algılar. Sabah ısınan taşta hızlanır, günün fazla sıcak saatinde gölgeye çekilir.',
        'Yumurtalarını sıcak fakat kurumamış oyuklara bırakır. Bir kaya boşluğu gaz veya su yön değiştirdiğinde üreme alanı kaybolabilir. Aynı kıyıda bir yıl bol görülen türün ertesi yıl azalması sadece avlanmayla değil, bu küçük yaşam alanlarının değişmesiyle de ilgilidir.'),
      chapter('Kılavuzun küçük işareti',
        'Seren Azh, neralın kullandığı yarıklara bakarak yerel sığınak koşullarını gözler. Hayvan görmek bütün yolun serin ya da güvenli olduğuna kanıt değildir. Sıcak çevreye uyarlanmış bir canlı da daha tehlikeli bölümden kaçabilir.',
        'Atölye yakınındaki böcekleri yemesi insanlarca hoş karşılanır, fakat hayvanı sıcak gösteri için elde tutmak doğru değildir. Lakbar öykülerinde sabrın ve doğru zamanda geri çekilmenin örneği olur. Gerçek yeteneği ateşi yenmek değil, onun yanındaki daha serin hayatı seçmektir.'),
    ], ['seren-azh', 'orun-vehl']),
  species('kara-yel-arisi', 'lakbar', 'lakbar',
    'Kara Yel Arısı, Lakbar’ın sınırlı reçineli ağaç çevrelerinde yuva kuran koyu renkli bir tozlaştırıcıdır. Isınmış dış ortamdan korunan ahşap oyuk, onun için alev dayanımından daha önemlidir.', [
      chapter('Reçinenin kenarında',
        'İri bir böcek değildir; altı ayağı, iki çift ince kanadı ve kısa antenleri vardır. Göğsü koyu kadifemsi tüylerle, karın bölümü kömür ve oker bantlarla örtülüdür. Dört kanat uçuşta birlikte hareket eder; dinlenirken gövdenin iki yanında üst üste kapanırlar.',
        'Küçük çiçeklerdeki polen bacak ve göğüs tüylerine takılır. Reçineli ağaç oyuklarının dar ağzına tutunabilir. Adını rüzgârda koyu nokta gibi görünen uçuşundan alır; sıcak gazlı havada sınırsız dayanmaz.'),
      chapter('Az çiçekli ülke',
        'Çiçek özü ve polen toplar; sınırlı bitki örtüsünde çiçek açan küçük kuşaklar yaşamını yoğunlaştırır. Her volkan yamacında aynı yuva bulunmaz. Korunaklı ağaç oyuklarıyla yakındaki beslenme alanı birlikte gereklidir.',
        'Dışarıdaki sıcaklık fazla yükselince topluluk yuva içinde hava dolaştırır ve çıkışı azaltır. Bu davranış bir arının ateş içinde uçtuğu efsanelerini doğrulamaz. Ağaç kesimi, duman ve aşırı toplama bütün koloniyi bir arada etkileyebilir.'),
      chapter('Ustanın beklediği kesim',
        'Dessa Koru kesilecek ağacın çevresini önce gözler; yoğun bir yuvaya denk gelirse üretim planını değiştirir ya da uygun aktarım için yerel bilgi arar. Ağaç kıtlığında her zaman kolay seçim yoktur. Bir yuvanın korunması bütün ahşap ihtiyacını ortadan kaldırmaz.',
        'Az miktardaki koyu bal ve mum değerlidir; bütün yuva payını almak sonraki dönemde hem arıyı hem geliri azaltır. Tozlaştırma, özel ağaçların çevresindeki küçük bitkileri de etkiler. Lakbar’da büyük malzemenin altında bu kadar küçük bir çalışanın bulunması, atölye anlatılarının sevdiği ayrıntıdır.'),
    ], ['dessa-koru']),
  species('teyra-tarakbaligi', 'danstsud', 'valdareth',
    'Teyra Tarakbalığı, Valdareth ovasının nehirlerinde taş taban yakınında beslenen orta boy bir balıktır. Katlanabilen sırt yüzgeci ve kısa duyu bıyıkları, akıntıda yer tutmasına ve bulanık suda yiyecek bulmasına yardım eder.', [
      chapter('Suyun altında tarak',
        'Yaklaşık kırk santimetreye erişen gövdesi gümüş-gri, sırtı donuk zeytin rengidir. Uzun ışınları olan sırt yüzgeci açıldığında tarak görünür, hızlı akıntıda geriye katlanır. Çatallı kuyruk kısa güçlü itişlere, göğüs yüzgeçleri tabana yakın dengeye yarar.',
        'Ağız hafif aşağıya yönelir; iki kısa bıyık çakıl çevresindeki yakın besin hareketini ve kokusunu yoklar. Küçük gözleri ışıklı sığlıkta işe yarar, ağır çamurda tek başına yeterli değildir. Bıyığın taş arasındaki teması, görüşün azaldığı suda yiyeceğin bulunduğu küçük boşluğu ayırt etmesine yardım eder.'),
      chapter('Ova nehrinin yemeği',
        'Böcek larvası, küçük kabuklu ve taş arasındaki yumuşak canlıları yer. Temiz çakıllı kesimde yumurtlar; büyümüş bitki kenarında yavrular daha yavaş su bulur. Nehir kıyısının bütünüyle düzlenmesi bu küçük korunakları azaltır.',
        'Soğuk mevsimde derin ve daha yavaş bölüme çekilir. Su çekimi arttığında sığ kollarda sıkışabilir; sıcaklık yükseldikçe canlılığını koruması için iyi su hareketi gerekir. Bereketli ova, nehrin her bölümünün sınırsız av vereceği anlamına gelmez.'),
      chapter('Beş sura gelen balık',
        'Balıkçılar onu taze ya da hafif tuzlanmış olarak şehrin sofrasına taşır. Maden işleme ve yoğun kıyı atıkları temiz çakıl alanını bozduğunda av da azalır. Aldara Gümüşalasıyla aynı tür değildir: daha ılık ova kuşaklarına uygundur ve farklı beslenme noktaları kullanır.',
        'Valdareth’in dış sur haneleri tarak yüzgecinin kurutulmuş biçimini kapı süsü yapabilir. Büyük nüfusu tek başına bu balık doyurmaz; tahıl ve başka ürün akışı sürer. Küçük bir balığın hikâyesi, başkentteki zengin sofrayla temiz su isteyen ova arasındaki görünür bağdır.'),
    ], ['danstsud-ekmek-ve-vergi', 'karlan-canlilari']),
]
