import type { Place, RegionId } from './data'

// Read from the author's original 8192 × 5668 image, never from a generated map.
// A pin describes a visible settlement centre; it is not a surveyed boundary.
export const mapAuditSource = '9 Ekim 2026 · özgün 8K harita konum denetimi'
export const mappedLifeSource = 'Harita Yerleşimleri · yeni kamusal yaşam yazımı'
const pixelPoint = (x: number, y: number): [number, number] => [Number((x / 8192).toFixed(6)), Number((y / 5668).toFixed(6))]

type MapCorrection = { point: [number, number]; positionStatus: 'mapped'; mapLabel?: string }
const corrected: [string, number, number, string?][] = [
  ['zarim-khet', 1450, 660], ['thariz', 340, 1050], ['sahrim', 2790, 970],
  ['qal-nashar', 2500, 1660], ['morihael', 1250, 1880],
  ['skjornhvaldr', 1800, 4070], ['frostheimr', 2800, 4210], ['norrvar', 2780, 3690], ['kaldryss', 2080, 4930],
  ['valdareth', 6200, 4000], ['lirendil', 3260, 2660], ['dorvenhall', 6460, 3240],
  ['marhalden', 4900, 4930], ['elorwyn', 6140, 4980], ['theramis', 7480, 5070],
  ['brannis', 5460, 3200], ['kethra', 4670, 2920], ['myrran', 3560, 2770], ['luthen', 3940, 2790],
  ['frostbay', 3850, 4850], ['ternhaven', 4120, 4040], ['dranthol', 3680, 4460], ['vyssgard', 4250, 4480], ['kaldmere', 3730, 5530],
  ['hurnreach', 5550, 1340], ['kraenfall', 5110, 2230], ['volriks-maw', 6390, 2400],
  ['baldrek', 6470, 420], ['stoneclans', 7870, 1300], ['twinclans', 6810, 1800], ['northpact', 7660, 1880], ['eldrascar', 7770, 2530],
  ['pilorn', 5170, 3450], ['gaalmire', 4992, 3140, 'Galmire'], ['naeron', 5230, 3905],
  ['fevric', 5250, 4180], ['theld', 6510, 4360], ['korhenden', 6925, 3750, 'Korthen'],
  ['uldar', 5250, 4420], ['tolvur', 5420, 5550], ['toran', 5360, 5200, 'Tora'],
  ['harven', 4820, 5520], ['mavric', 4410, 5260],
]
export const mapCorrections: Record<string, MapCorrection> = Object.fromEntries(corrected.map(([id, x, y, mapLabel]) => [id, { point: pixelPoint(x, y), positionStatus: 'mapped', ...(mapLabel ? { mapLabel } : {}) }]))
export const correctedMapPixels = corrected.map(([id, x, y, mapLabel]) => ({ id, x, y, mapLabel }))

type MappedSettlement = {
  id: string; name: string; region: RegionId; x: number; y: number;
  subtitle: string; summary: string;
  scene: string[]; life: string[];
  related?: string[]; readingNote?: string;
}
const settlements: MappedSettlement[] = [
  {
    id: 'orunq', name: 'Orunq', region: 'xotar', x: 2260, y: 180,
    subtitle: 'Kuzey kıyısında suyun ve sözün pazarı',
    summary: 'Orunq’ta bir kervanın karşılanması, mal sayılmadan önce su kaplarının açılmasıyla başlar. Kuzey kıyısındaki kent, denizden gelen yükü çölün ölçülerine çevirir.',
    scene: ['Güneş yükselirken gölgeli avlulara önce su taşıyıcıları girer. Kuyudan çıkan her kova, dükkânın hangi saatte açılacağını da belirler; bir kumaş tüccarı susamış yükçülerle pazarlık yapmanın şehirde uzun süre hatırlandığını bilir.'],
    life: ['Xotar’ın su misafirliği burada liman adabı ile birleşir. Yolcuya ilk tası vermek cömertlik gösterisinden önce bir kabul işaretidir; sonraki tasın fiyatı ise ev sahibi ile konuğun ne konuşacağına bağlıdır.'],
    related: ['xotar', 'zarim-khet'],
  },
  {
    id: 'vaelgrim', name: 'Vaelgrim', region: 'honud', x: 1180, y: 2670,
    subtitle: 'İki karlı kıyı arasında paylaşılan ocaklar',
    summary: 'Vaelgrim’in iki kıyı kümesi aynı rüzgârı alır, fakat kış erzağı her hanenin kapısından ayrı taşınır. Komşuluk burada hangi ocağın yanmaya devam ettiğini bilmekle ölçülür.',
    scene: ['Karlı çatılar arasındaki ilk hareket, sabah ateşinden yükselen dumandır. Kıyının öte yanında duman görünmeyen bir ev için balıkçı teknesinin yönü değişir; bir hanenin sessizliği bütün komşuların işine karışır.'],
    life: ['Honud’un kış stokları, Vaelgrim’de kişisel servet kadar ortak güvenliğin konusudur. Kurutulmuş balık ve ocak odunu ödünç veren hane, borcun hemen değil zor gün geçtikten sonra dönmesini bekler.'],
    related: ['honud', 'dravenspire'],
  },
  {
    id: 'dravenspire', name: 'Dravenspire', region: 'honud', x: 170, y: 2860,
    subtitle: 'Batı uçta kar altındaki uzun evler',
    summary: 'Dravenspire’in kıyısında bir teknenin sağlam dönmesi, evlerdeki bütün hesaplardan önce gelir. Yerleşimin batı kenarı açık rüzgârı ilk karşılayan yerdir.',
    scene: ['Kış sabahında kapıların önündeki karı ilk temizleyenler ağ tamircileridir. Tekne kıyıda bağlıyken bile denizin ağırlığı hissedilir; bir halatın kopması, haftalık iaşenin buzla birlikte sürüklenmesi demektir.'],
    life: ['Bir eve yeni gelenin mahareti çoğu kez büyük bir gösteriyle değil, kopmuş bir bağı nasıl onardığıyla anlaşılır. Buzlu kıyıda yardım istemek utanç değildir; yardım edecek elin boşta bulunması bütün mahallenin hesabıdır.'],
    related: ['honud', 'vaelgrim'],
  },
  {
    id: 'wolfcrag', name: 'Wolfcrag', region: 'honud', x: 705, y: 3220,
    subtitle: 'Kayalıkların gölgesinde yol dinleyen evler',
    summary: 'Wolfcrag’da kayalıkların ardında görünen bir iz, köyün akşam yemeğini de nöbetini de değiştirebilir. Kışın av ile tehlike aynı patikadan yaklaşır.',
    scene: ['Yerleşimin karlı çatısı, dik kayalık ile ağaçların arasına sıkışır. Ocakta yemek beklerken kapının yanında dışarıda kurutulan ipler tutulur; donmuş bir düğümün çözülmesi için içeride zaman harcanır.'],
    life: ['Avcıların bıraktığı işaretler her izleyiciye aynı şeyi söylemez. Taze bir çizik, karın yönü ve rüzgârın kokusu birlikte okunur; büyük bir silah taşımak kayalıkta güvenle yürümeyi öğretmez.'],
    related: ['honud', 'boreals-end'],
  },
  {
    id: 'boreals-end', name: 'Boreal’s End', region: 'honud', x: 1370, y: 3510,
    subtitle: 'Buzlu su üstündeki son bağlar',
    summary: 'Boreal’s End’de bir köprünün tamiri, iki hanenin anlaşmazlığından daha uzun sürmemelidir. Kıyıdaki uzun evler, kar kapanmadan birbirine ulaşabilmek için çalışır.',
    scene: ['Köprü başında bekleyen biri, ayak sesinden önce tahtanın titreşimini duyar. Yük taşıyan kızaklar sırayla geçer; acele eden bir tüccar bütün pazarın uğrayacağı zararı kendi kazancıyla tartmak zorundadır.'],
    life: ['Geçişi açık tutmanın masrafı yalnız tahtanın fiyatı değildir. İşinden ayrılan tamirciye erzak, onun evine odun ve nöbet tutana sıcak bir yemek gerekir.'],
    related: ['honud', 'wolfcrag'],
  },
  {
    id: 'deadveil', name: 'Deadveil', region: 'honud', x: 1840, y: 3170,
    subtitle: 'Kırık kulelerin unutulmayan adı',
    summary: 'Deadveil haritada yıkık kulelerle gösterilir. Oraya yaklaşanlar yaşayan bir şehirden önce kar altında kalan eşikleri ve dönmeye yetecek zamanı düşünür.',
    scene: ['Kar, duvarların açık taş derzlerine dolmuştur. Bir zamanlar içeriyi dışarıdan ayıran kapı bugün rüzgârı kesmez; ayakta kalan kule uzaktan sağlam görünse de yakınında düşmüş taşların yaşı anlaşılır.'],
    life: ['Eski taşın içindeki boşluk, yeni gelenin barınağı olabilir; aynı boşlukta bir önceki kıştan kalan kar da durabilir. Bir rehberin en değerli uyarısı hangi kuleye çıkılmayacağıdır.'],
    related: ['honud', 'whisperhold'],
  },
  {
    id: 'silent-cairn', name: 'Silent Cairn', region: 'honud', x: 750, y: 3630,
    subtitle: 'Sessiz taşın yanında küçük ocaklar',
    summary: 'Silent Cairn’in taş ve buz arasındaki küçük evleri, büyük bir şehrin güvenine sahip değildir. Burada sessizlik bazen huzur, bazen yardım istenemediği anlamına gelir.',
    scene: ['Kırağı kapı mandalını tuttuğunda, içerideki ateşin sesi dışarıdaki rüzgâra karışır. Yolcunun kapıya vurması, ev sahibine adını söylemesinden önce duyurur ne kadar üşüdüğünü.'],
    life: ['Küçük bir ocakta misafir ağırlamak, aile stokundan pay ayırmaktır. Bu yüzden verilen yemekle birlikte gidilecek yön ve havanın değişeceği saat de anlatılır.'],
    related: ['honud', 'ashfrost'],
  },
  {
    id: 'skeldrun', name: 'Skeldrun', region: 'honud', x: 2240, y: 3000,
    subtitle: 'Kuzey kıyısındaki kar örtülü çatı kümesi',
    summary: 'Skeldrun’da kıyıya bırakılmış bir tekne, birinin geri dönme niyetidir. Yolculuklar buzun uygunluğu kadar eve bırakılan erzağa da bağlıdır.',
    scene: ['Kar altındaki çatılar aynı renge bürünse de hangi ocakta kimin kaldığı kıyıda bilinir. Bir teknenin yeni bağlanmış halatı, konuşmaya fırsat bulamamış yolcunun haberini verir.'],
    life: ['Ağ örme ve yiyecek saklama birbirinden ayrı işler değildir. Balığın ne kadarının şimdi yenileceği, bir sonraki denemede kıyının ne zaman açılacağıyla birlikte kararlaştırılır.'],
    related: ['honud', 'hjorthal'],
  },
  {
    id: 'hjorthal', name: 'Hjorthal', region: 'honud', x: 2480, y: 3270,
    subtitle: 'Evlerin birbirine baktığı karlı kıyı',
    summary: 'Hjorthal’ın dar kıyısında yanan bir pencere, gece dönen avcı için yol işaretidir. Buzlu suyun kenarında güven, birbirini tanıyan evlerde başlar.',
    scene: ['Önce çatılardan kayan kar, sonra kapıların önüne yığılan yük kaldırılır. Kıyıda bir tekne onarılırken evlerdeki konuşma bitmez; yapılan işin sonucu aynı sofralara ulaşacaktır.'],
    life: ['Kıyıya yeni gelen biri için en zor alışkanlık her yardımın hemen para ile ölçülmemesidir. Ağ onarmak, çocuğa göz kulak olmak ve sonraki avdan pay vermek aynı uzun hesabın farklı satırlarıdır.'],
    related: ['honud', 'skeldrun'],
  },
  {
    id: 'winterhavn', name: 'Winterhavn', region: 'honud', x: 1880, y: 3630,
    subtitle: 'Karlı rıhtımda mevsim bekleyen evler',
    summary: 'Winterhavn’ın kıyı evleri denize yakın, açık suya ise her gün yakın değildir. Bir ambarın doluluğu, yolcunun kaç gün kalacağını belirleyebilir.',
    scene: ['İskele kenarında biriken kar kürekle temizlenirken teknenin altı yoklanır. Görünürde sağlam bir bağ, gecenin buz hareketinden sonra yeniden kontrol edilir.'],
    life: ['Kış sığınağı olmak, gelen herkes için sınırsız yiyecek bulundurmak değildir. Ev sahipleri misafirin çalışabilecek ellerini, yanında taşıdığı yük kadar dikkatle değerlendirir.'],
    related: ['honud', 'norrvar'],
  },
  {
    id: 'ashfrost', name: 'Ashfrost', region: 'honud', x: 160, y: 3730,
    subtitle: 'Yıkık taşların yanında sönmeyen küçük ateş',
    summary: 'Ashfrost’ta ayakta duran evler ile terk edilmiş taş aynı görüş alanına girer. Bir ocakta kalan közün değeri, adının şiirinden daha somuttur.',
    scene: ['Eski duvarın yanında bir evin bacası tüter. Kar çizginin bir tarafında yeni izi, öte yanında yıllardır değişmeyen kırık eşiği saklar; yolcu hangisinin barınak olduğunu yakınlaşınca anlar.'],
    life: ['Ocağı yeniden yakmak için saklanan kuru çıra, günlük tüketimden ayrı tutulur. Bu küçük alışkanlık, ateş söndüğünde bütün evin tehlikeye girmesini önler.'],
    related: ['honud', 'silent-cairn'],
  },
  {
    id: 'white-woe', name: 'White Woe', region: 'honud', x: 210, y: 4480,
    subtitle: 'Buzlu mimarinin çevresindeki yıkık eşikler',
    summary: 'White Woe’da mavi buz mimarisi kırık taşların arasından yükselir. Atlas burayı yaşayan bir metropol olarak değil, Honud’un belleğinde yeri olan eski bir alan olarak açar.',
    scene: ['Açık kar üzerinde duran buz biçimleri, gün ışığı değişince başka bir derinlik kazanır. Taş basamakların çoğu yerinden oynamıştır; bir yapının çizgisi uzaktan hâlâ bütün görünür.'],
    life: ['Eski bir eşikten geçmek, onun hikâyesini bilmekle aynı şey değildir. Yerel anlatılar burada durup söz söylemeyi öğretebilir, fakat birbirinden farklı anlatılar tek bir kuruluş efsanesine zorlanmaz.'],
    related: ['honud', 'whisperhold'],
  },
  {
    id: 'whisperhold', name: 'Whisperhold', region: 'honud', x: 240, y: 5500,
    subtitle: 'Buz ve yıkık taş arasında hafıza durağı',
    summary: 'Whisperhold’da eski taşların arasındaki buz biçimleri güneşin kısa saatlerini toplar. Yerin sessizliği, kaynağı bilinmeyen bir büyünün kesin kanıtı sayılmaz.',
    scene: ['Rüzgâr boş pencerelerden geçerken açık zeminin sesi değişir. Bir yolcunun adımı buzun üstünde duyulur, karın üstünde kaybolur; alanı tanımak hangi yüzeyde yürüdüğünü bilmekle başlar.'],
    life: ['Honud’un sözlü hafızası, yıkık yapıları yalnız eski mimari olarak hatırlamaz. Ailelerin burada anlattığı sözler ziyaretçinin davranışını etkiler; birinin adak dediğini diğeri anma sayabilir.'],
    related: ['honud', 'white-woe'],
  },
  {
    id: 'frostgrave', name: 'Frostgrave', region: 'honud', x: 1630, y: 5460,
    subtitle: 'Güneyde kar altında kalan küçük evler',
    summary: 'Frostgrave’in adını duyan bir yabancı, yaşamın bittiğini sanabilir. Haritada kar altındaki küçük yapılar, adın taşıdığı korkudan daha gündelik bir hayatı işaret eder.',
    scene: ['Kapının önünde yarılmış odun durur; onu örten kar hemen temizlenmezse içerideki ateş de bundan etkilenir. Küçük evlerin ihtiyacı, yakınındaki büyük dağın manzarasından bağımsız değildir.'],
    life: ['Bir evin kışa hazırlanması dükkânın rafını doldurmaya benzemez. Kuru odun, tamir edilmiş çatı ve bozulmayan yemek birbirinin yerine geçemeyen üç ayrı güvencedir.'],
    related: ['honud', 'kaldryss'],
  },
  {
    id: 'yatesh', name: 'Yatesh', region: 'honud', x: 2280, y: 4040,
    subtitle: 'İnce kıyı geçişinde küçük bir kış topluluğu',
    summary: 'Yatesh’in evleri su ile ağaç arasına yerleşir. Burada bir yolcunun taşıdığı haber, getirdiği yük kadar dikkatle paylaşılır.',
    scene: ['Kıyı yapısının altına dolan buz gün boyunca değişir. Kapıyı açan biri önce gökyüzüne, sonra suyun kenarına bakar; günlük işin hangi sırayla yapılacağına bu iki bakış karar verir.'],
    life: ['Yolculuk haberi burada bir söylentiden ibaret değildir. Karın nerede kapıyı örttüğünü bilen biri, akşam yola çıkacak başka bir ailenin kararını değiştirebilir.'],
    related: ['honud', 'norrvar'],
  },
  {
    id: 'bleakmoor', name: 'Bleakmoor', region: 'honud', x: 2520, y: 4440,
    subtitle: 'Ağaçlarla çevrili karlı evler',
    summary: 'Bleakmoor’da orman yakındır, fakat odunu eve getirmek hâlâ bir günlük iştir. Evlerin birbirine bakması kışın küçük arızaları ortak bir soruna dönüştürür.',
    scene: ['Ağaçtan düşen kar, taşınan odunun üzerine yeniden dolar. Kızak kapıya kadar getirildiğinde asıl mesele işin bitmesi değil, içeri alınacak yığının kurutulacak yer bulmasıdır.'],
    life: ['Ormanlık bir yerde yaşamak, sınırsız yakacak elde etmek anlamına gelmez. Kesme, taşıma ve kurutma mevsimin ayrı emekleridir; bir hane bu üç işten birini aksatınca komşudan yardım ister.'],
    related: ['honud', 'frostheimr'],
  },
  {
    id: 'isenreach', name: 'Isenreach', region: 'honud', x: 3170, y: 4710,
    subtitle: 'Doğu kıyısında karla örtülü son evler',
    summary: 'Isenreach’te karşı kıyı bazen görünür, güvenli geçiş ise görünmez. Kıyı insanları iki mesafeyi aynı saymamayı öğrenir.',
    scene: ['Bir tekne, karlı evlerin önünde uygun suyu bekler. Uzakta görünen başka bir ışık buraya yakın bir liman vaat etmez; hareketli buz ve rüzgâr aradaki mesafeyi gün boyunca yeniden kurar.'],
    life: ['Kıyıdaki bir pazarlık, malın bedeli kadar teslim edilebileceği günü tartışır. Beklemek pahalıdır; acele etmek ise hem tekneyi hem evdeki erzağı kaybettirebilir.'],
    related: ['honud', 'kiragi-denizi'],
  },
  {
    id: 'eirhollow', name: 'Eirhollow', region: 'honud', x: 2430, y: 5400,
    subtitle: 'Karlı güney kıyısında bir arada duran evler',
    summary: 'Eirhollow’un evleri ağaçların ve çıplak suyun sınırında durur. Kışın başka bir eve ulaşabilmek, dışarıdaki işten daha önemli hâle gelebilir.',
    scene: ['Kıyıya yakın bir uzun evde içeri alınan yükler önce duvardan uzak tutulur. Çatıdan sızan nem, kuru erzağı dışarıdaki soğuktan daha sessiz biçimde bozar.'],
    life: ['Birlikte yaşamak yükü bölüştürür, fakat küçük anlaşmazlıkları da yakın tutar. Eirhollow’un yeni anlatısı, paylaşılan ocakta kimlerin ilk odunu getirdiği üzerinden güven ve alınganlığı bir araya getirir.'],
    related: ['honud', 'kaldryss'],
  },
  {
    id: 'varnskuld', name: 'Varnskuld', region: 'honud', x: 3330, y: 5360,
    subtitle: 'Donmuş kıyıda yük ve bekleyiş',
    summary: 'Varnskuld’da açıkta bekleyen bir tekne ile içeride bekleyen bir aile aynı hava haberine bağlıdır. Kıyının öte yanındaki Hardlane, yakın görünmesiyle güvenli hâle gelmez.',
    scene: ['Karlı evlerin yanında taşınan balık kasaları teknenin yükünden ayrılır. Bir kısmı şimdi tüketilir, bir kısmı ne zaman gelecek belli olmayan yolcu için saklanır.'],
    life: ['Kışın bir pazarı açık tutmak, her gün mal gelmesiyle mümkün değildir. Saklanan yiyecek ve onarılan ağ, satılan yük kadar önemli bir ticari emektir.'],
    related: ['honud', 'kiragi-denizi', 'nivor'],
  },
  {
    id: 'nivor', name: 'Nivor', region: 'honud', x: 2900, y: 5540,
    subtitle: 'Güney ucunda kışa tutunan evler',
    summary: 'Nivor’un karlı evlerinde günlük hayat, gecenin ne kadar süreceğini bilerek yürür. Uzak kıyıların haberleri ocağın başında bir sonraki yolculuğa çevrilir.',
    scene: ['Bir evin önündeki açık yere yeni iz düşmesi kolay fark edilir. Kar her şeyi tek renge indirdiğinde, bir misafirin gelişini kıyafetinden önce yürüyüşünün yorgunluğu anlatır.'],
    life: ['Yolculuk öncesi hazırlık, yiyecek toplamaktan fazlasıdır. Dönecek kişinin ocağını kimin yakacağı ve geride kalanlara kimin haber vereceği de konuşulur.'],
    related: ['honud', 'varnskuld'],
  },
  {
    id: 'aelmar', name: 'Aelmar', region: 'danstsud', x: 3300, y: 3070,
    subtitle: 'Lirendil’in güneyinde küçük kıyı kenti',
    summary: 'Aelmar’da bir yükün hikâyesi bazen Lirendil’deki büyük sözleşmeden daha uzun sürer. Küçük kıyı kentinin evleri, denizden gelenleri kapı kapı tanır.',
    scene: ['Kıyıdan gelen bir yük, ilk olarak ıslanıp ıslanmadığına bakılarak karşılanır. Satışın hesabı sonra gelir; kumaş kuruyacak yer bulamazsa imza onu kurtarmaz.'],
    life: ['Küçük bir kentte depolama ile misafir ağırlamak sık sık aynı eve düşer. Yük sahipleri hancının boş odasını isterken, uzun yoldan gelen biri aynı odada yalnız uyumayı düşünür.'],
    related: ['danstsud', 'lirendil', 'thessar'],
  },
  {
    id: 'thessar', name: 'Thessar', region: 'danstsud', x: 3730, y: 3280,
    subtitle: 'Kıyıda kulelerin ve küçük pazarlığın şehri',
    summary: 'Thessar’ın kıyı evleri, büyük kentlerin yükü arasındaki küçük işleri toplar. Yolcunun acele etmesi, kentteki ustanın işini acele bitireceği anlamına gelmez.',
    scene: ['Bir teknenin yıpranmış bağı, çarşıdaki fiyat konuşmasını keser. Kıyı işçisi aynı işi iki kez yapmak istemediğinde tüccarın beklemekten başka şansı kalmaz.'],
    life: ['Deniz yolunun küçük tamirleri kentte ciddi bir geçim oluşturabilir. İyi halat, sağlam sandık ve kuru ambar bir büyük seferin görünen kahramanları değildir; yoklukları ise herkesi durdurur.'],
    related: ['danstsud', 'aelmar', 'kethra'],
  },
  {
    id: 'morvail', name: 'Morvail', region: 'danstsud', x: 4260, y: 2820,
    subtitle: 'Kuzey kıyı yolunda kapı ve konak',
    summary: 'Morvail’de kıyı yolunun sesi sabah çarşısından önce gelir. Bir kervanın yükü kadar, burada durmaya ne kadar niyetli olduğu da pazarlık konusudur.',
    scene: ['Kulelerin yanından geçen yüklü hayvanlar dar yolda sıraya girer. Ev sahipleri yolcunun aynı gece devam edip etmeyeceğini sorar; hazırlanan sıcak yemek ile tutulan oda aynı kararın sonucudur.'],
    life: ['Bir konak durağı için iyi iş, her gelenin kentte bir gün kalması değildir. Kimi yükün hızla geçmesi, ardından daha büyük bir kervanın gelmesini sağlar; küçük tüccarlar bu dengeyi konuşarak kurar.'],
    related: ['danstsud', 'kethra', 'luthen'],
  },
  {
    id: 'yornhal', name: 'Yornhal', region: 'danstsud', x: 4240, y: 3240,
    subtitle: 'Rydorn çevresinde küçük evler ve yol',
    summary: 'Yornhal’da küçük evlerin önünden geçen yol, uzak kentlerin işini buraya taşır. Bir hanenin hazırladığı yiyecek bazen bütün kervanın akşamını kurtarır.',
    scene: ['Kıyıya yakın yolun kenarında bir kazan kaynar. İçinden ne çıkacağını öğrenmek isteyen yolcu önce hangi yükün beklediğini anlatır; ev sahibi günlük ihtiyacın üstüne kaç kişiyi ağırlayacağını böyle hesaplar.'],
    life: ['Bir yol kenarı yerleşiminin geçimi, geçen herkesin altın taşımasına dayanmaz. Hayvan bakımı, basit tamir ve yiyecek takası kentteki küçük hanelerin birbirine bağlanmasına katkı sağlar.'],
    related: ['danstsud', 'rydorn-sirti', 'vornic'],
  },
  {
    id: 'vornic', name: 'Vornic', region: 'danstsud', x: 4520, y: 3290,
    subtitle: 'Kıyı yolunda kulelerin gölgesindeki çarşı',
    summary: 'Vornic’te iki şehir arasında taşınan malın durduğu yer, çoğu zaman sahibinin planını değiştirir. Kentin küçük çarşısı bekleyen yükten de geçim çıkarır.',
    scene: ['Bir sandığın kırık menteşesi, yolcuyu dükkânın önünde tutar. Tamir biterken yanında taşınan un, başka bir ailenin akşam yemeğinin hesabına girer; yolculuk işi yerel hayata karışır.'],
    life: ['Kentte iyi bir zanaatkârın itibarı fiyatından daha uzağa gider. İşinin iki durak sonra bozulması, geri dönülmese bile başka yolcuların anlattığı bir haber olur.'],
    related: ['danstsud', 'yornhal', 'kethra'],
  },
  {
    id: 'frethar', name: 'Frethar', region: 'danstsud', x: 4860, y: 3370,
    subtitle: 'Kıyı yolunun güneyinde küçük yerleşim',
    summary: 'Frethar’ın küçük çatılarında yolculuk yükü ile ev ihtiyaçları birbirine değinir. Haritada görülen bu ad, lore’daki Fehar ile otomatik birleştirilmemiştir.',
    scene: ['Kızıl çatılı evlerin önünden geçen yolun üstünde yükün ağırlığı hemen fark edilir. Hayvanın soluklanmasına ayrılan zaman, yakındaki ailenin yiyecek hazırlamasına da fırsat verir.'],
    life: ['Küçük bir yerleşim, büyük kentlere götürülen yükün her zaman sahibi değildir. Yolcuya verilen hizmetler ile hanelerin kendi üretimi birlikte düşünülür; kazanç geçişin durduğu günlerde azalabilir.'],
    related: ['danstsud', 'fehar', 'vornic'],
  },
  {
    id: 'tyelmar', name: 'Tyelmar', region: 'danstsud', x: 4490, y: 3600,
    subtitle: 'Kıyı ve ağaçlar arasında küçük kule kenti',
    summary: 'Tyelmar’ın mor çatılı evleri açık suya bakar. Kıyıda bekleyen yük ile içteki hanelerin iaşesi, aynı küçük pazarda karşılaşır.',
    scene: ['Kulenin altında bağlanan yükler gölgeye alınır. Ağaçların arasında görülen kıyı, rüzgârın her an aynı yönden gelmediğini hatırlatır; ev sahibinin iyi konak tarifi de bu bilgiye dayanır.'],
    life: ['Bir pazarın canlılığı yalnız büyük gemi beklemesiyle ölçülmez. Küçük tekne, yol kenarı ustası ve yiyecek satan aile birbirinin boş kaldığı saati tamamlar.'],
    related: ['danstsud', 'arden', 'velthar'],
  },
  {
    id: 'arden', name: 'Arden', region: 'danstsud', x: 4850, y: 3760,
    subtitle: 'Ova kıyısındaki ambarların yerleşimi',
    summary: 'Arden’de bir ambarın kapısı kapanınca pazarın sesi bitmez. Topraktan gelen yükün kuruması, taşınması ve paylaşılması kenti mevsime bağlar.',
    scene: ['Yel değirmeni ile ambarların yakınındaki yol sabah yük alır. Bir çuvalın yere bırakılması, onu kimin taşıdığı kadar nerede bekleteceğiyle de ilgilidir; nem, aceleci pazarlığın en sessiz tarafıdır.'],
    life: ['Verimli ova, kendiliğinden dolu sofra demek değildir. Hasadın taşınması, ambarın kuru tutulması ve borcun hangi mevsimde ödeneceği kentte ayrı ayrı pazarlık konusu olur.'],
    related: ['danstsud', 'valdareth', 'tyelmar'],
  },
  {
    id: 'nuvik', name: 'Nuvik', region: 'danstsud', x: 5750, y: 3200,
    subtitle: 'Dorvenhall’a uzanan yolun küçük durağı',
    summary: 'Nuvik’te bir kervanın son gecesi büyük kente hazırlıkla geçer. Kentin kapısından girmeden önce düzeltilen bir hesap, sabah çarşıda kavga çıkmasını önleyebilir.',
    scene: ['Küçük kızıl çatılı evlerde ışık erken yanar. Yolcular şehirde hangi dükkâna gideceklerini sorarken ev sahipleri yüklerin sıra sıra sayılmasını izler; büyük pazardan önce küçük eksikler burada bulunur.'],
    life: ['Bir yol durağının geçimi, aynı işi ikinci kez kontrol etmeyi bilen insanlara da dayanır. Çuvalın ağzı, hayvanın ayağı ve satıcının defteri yolun son gecesinde aynı önem kazanır.'],
    related: ['danstsud', 'dorvenhall', 'brannis'],
  },
  {
    id: 'telvai', name: 'Telvai', region: 'danstsud', x: 5700, y: 3380,
    subtitle: 'Yol ile ambarların buluştuğu küçük ova durağı',
    summary: 'Telvai’nin ambarları ana yolun yanında görünür. Burada saklanan yük, kentte hemen satılmayan malın da bir sahibi ve hikâyesi olduğunu hatırlatır.',
    scene: ['Yoldan geçen biri yapıların tekdüze çatısını görür; içeride çalışan biri ise hangi duvarın nemi tuttuğunu bilir. Bir malı bir gün daha saklamak bazen iyi kazanç, bazen bütün kaybın başlangıcıdır.'],
    life: ['Ambar işi yalnız kapı kilitlemekten ibaret değildir. Sayım, havalandırma ve taşıyıcının yükü zamanında bulması birlikte yürür; kâğıtta var olan malın rafta bulunması ayrı bir iştir.'],
    related: ['danstsud', 'dorvenhall', 'nuvik'], readingNote: 'Yerleşim ve merkezi görünür; adın bazı çizgileri ağaç altında. Telvai okuması editoryal ve değiştirilebilir.',
  },
  {
    id: 'velthar', name: 'Velthar', region: 'danstsud', x: 4560, y: 3910,
    subtitle: 'Karlan’ın kuzey yaklaşımında kule kenti',
    summary: 'Velthar’da sabahın dağ gölgesi çarşıya kadar uzanır. Ova işiyle yüksekliğin şartlarını birlikte bilenler, yolcuların ihtiyacını herkesten önce fark eder.',
    scene: ['Kulenin yanındaki pazarda bir çift kalın eldiven, parlak bir kemer tokasından daha kolay alıcı bulur. Dağa bakarak yola çıkan biri aşağıdaki havanın ona bütün yolu anlatmadığını öğrenir.'],
    life: ['Dağ çevresinde geçim, her yolcuya aynı malı satmak değildir. Mevsime ve taşınacak yüke göre ip, ayakkabı veya erzak daha kıymetli olabilir; yanlış hazırlığın bedeli yolda çıkar.'],
    related: ['danstsud', 'karlan-daglari', 'brolin'],
  },
  {
    id: 'brolin', name: 'Brolin', region: 'danstsud', x: 4890, y: 3990,
    subtitle: 'Kuzey dağ yaklaşımının ambar ve yol durağı',
    summary: 'Brolin’de tarladan gelen yük ile dağa hazırlanmış yük farklı bekletilir. Aynı ambarın çatısı altında, ovaya ve yüksekliğe bakan iki hesap tutulur.',
    scene: ['Küçük yapı grubunun önündeki yol gün içinde el değiştirir: sabah erzak taşıyanların, akşam geri dönenlerin izleri aynı toprakta üst üste gelir. Bir boş sandık da sahibinin yaklaşan işini haber verir.'],
    life: ['Brolin’in yeni gündeliğinde depolama bir bekleme sanatı hâline gelir. Dağdan haber gelmeden çıkmak istemeyen yük sahibi ile ambarı boşaltmak isteyen işçi aynı saate farklı değer verir.'],
    related: ['danstsud', 'velthar', 'karlan-daglari'],
  },
  {
    id: 'othmar', name: 'Othmar', region: 'danstsud', x: 7100, y: 3260,
    subtitle: 'Dorvenhall’ın doğusundaki kule ve yol kenti',
    summary: 'Othmar’ın evlerine büyük üretim kentinin haberleri hızla ulaşır. Yolun getirdiği mal ile hanelerin aradığı iş aynı küçük pazarda karşılaşır.',
    scene: ['Kent yolundaki bir araba önce kulelerin gölgesinde durur. Yükün ağır görünmesi her ustaya iyi kazanç vaat etmez; kırılmış kasa ve eksik ödeme aynı arabayla gelebilir.'],
    life: ['Büyük bir komşuya yakın yaşamak fırsat ve kırılganlığı birlikte getirir. Dorvenhall’da duran bir sipariş, Othmar’daki taşıyıcıyı ve yiyecek satıcısını da bekletebilir.'],
    related: ['danstsud', 'dorvenhall', 'eldwen'],
  },
  {
    id: 'eldwen', name: 'Eldwen', region: 'danstsud', x: 7500, y: 3270,
    subtitle: 'Doğu yolunda mor çatılı küçük kent',
    summary: 'Eldwen’de yolcuların durduğu meydan, hanelerin gündelik işini kesmeden paylaşılır. Kimin önce geçeceği, her zaman kimin daha zengin olduğuna bağlı değildir.',
    scene: ['Bir arabanın dönüşü için bırakılan boş alan, öğleden sonra dükkân önündeki pazara dönüşür. Sabah yükün sahibi olan kişi akşam aynı yerde yemek satın almak için sıraya girer.'],
    life: ['Küçük kentte işleyen anlaşma, herkesin aynı saatte aynı alanı kullanmamasına dayanır. Büyük bir yük geçerken dükkânın kapanması, sahibinin kazancından verilen geçici bir paydır.'],
    related: ['danstsud', 'othmar', 'thandor'],
  },
  {
    id: 'thandor', name: 'Thandor', region: 'danstsud', x: 7770, y: 3290,
    subtitle: 'Doğu kıyı yolunda küçük çatılar',
    summary: 'Thandor’da yol kenarındaki küçük evlerin tezgâhı dışarıdan gelen iş kadar kendi hanelerinin ihtiyacını da karşılar. Bir pazar günü, başka birinin tamir günü olabilir.',
    scene: ['Kızıl çatılı evin önünde satılan ip, yanındaki arabanın tekeri için tutulur. Satıcı kendi ihtiyacıyla müşterinin aceleciliğini tartar; alınan para ertesi iş için malzemeye dönecektir.'],
    life: ['Küçük yerleşimde ustalık sık sık bir kişinin birkaç işi yapabilmesidir. Aynı el sabah kapı tamir eder, akşam taşıyıcıya bağ örer; kazanç farklı ihtiyaçları birbirine bağlar.'],
    related: ['danstsud', 'eldwen', 'cevan'],
  },
  {
    id: 'cevan', name: 'Cevan', region: 'danstsud', x: 8090, y: 3330,
    subtitle: 'Doğu ucunda kıyıya bakan kule kenti',
    summary: 'Cevan’ın evleri haritanın doğu ucunda denize bakar. Uzak bir yelken burada önce haber, sonra yük, en son kazanç ihtimali olur.',
    scene: ['Kıyıya yaklaşan bir tekne görünürken pazarın işi devam eder. Bir aile dışarıdan gelecek tuzu düşünür, bir başka hane geri gelmesi beklenen akrabasını; aynı yelken herkese başka şey anlatır.'],
    life: ['Kıyı kentinin geçimi, deniz hareketi kadar açıkta kalacak işlerin hazırlığına bağlıdır. Beklerken ağ onarmak, ambarı temizlemek ve kuru yiyecek ayırmak, sefere çıkmak kadar gündeliktir.'],
    related: ['danstsud', 'thandor', 'orinhal'],
  },
  {
    id: 'velyra', name: 'Velyra', region: 'danstsud', x: 6250, y: 3560,
    subtitle: 'Dorvenhall’ın güneyinde ova ve ambar',
    summary: 'Velyra’da bir çuvalın fiyatı tarladan çıktığı günle ambarın açıldığı gün arasında değişir. Küçük yerleşim, üretim kadar bekletmenin de hesabını tutar.',
    scene: ['Ambar önünde duran yükler sayılmadan önce kuru zemine alınır. Taşıyıcı yoldan gelen nemi unutur gibi olsa da içeride çalışan biri çuvalın altına dokunarak bunu yeniden hatırlatır.'],
    life: ['Büyük şehrin ihtiyacı küçük yerleşimin bütün malını aynı anda çekebilir. Velyra’daki bir hane satmayı ertelerken yalnız fiyatı değil, kendi kış erzağını da düşünür.'],
    related: ['danstsud', 'dorvenhall', 'danstsud-ekmek-ve-vergi'],
  },
  {
    id: 'rymar', name: 'Rymar', region: 'danstsud', x: 7220, y: 3470,
    subtitle: 'Yol ve su yakınında küçük ova yerleşimi',
    summary: 'Rymar’ın evleri büyük kentlerin arasında görünmeden çalışır. Bir arabanın bozulması, bir tarlanın su sırası kadar hızlı biçimde herkesin işine karışabilir.',
    scene: ['Kızıl çatılı küçük evlerde günlük iş yol sesine göre bölünür. Taşıyıcıların geçtiği saatten sonra dışarı bırakılan mal, satılacak yükten çok hanelerin kendi ihtiyacıdır.'],
    life: ['Geçim bir tek ürüne bağlanmadığında haneler birbirinin yoğun zamanını tamamlar. Tarlada gerekli olan el, ertesi gün hayvan bakımında veya bir taşıma işinde aranabilir.'],
    related: ['danstsud', 'lysmar', 'othmar'],
  },
  {
    id: 'lysmar', name: 'Lysmar', region: 'danstsud', x: 7420, y: 3590,
    subtitle: 'Ova suyunun kıyısında ambar ve köprü',
    summary: 'Lysmar’da suyun yakını bir kolaylık olduğu kadar bakım işidir. Kuru ambarın değeri, dışarıdan bakıldığında anlaşılmayan küçük alışkanlıklarda korunur.',
    scene: ['Köprüye yakın yapıların içindeki yükler duvardan uzak tutulur. İyi havada açılan bir kapı, içerideki işçiye dışarıdan gelen müşteriden daha çok yarar sağlayabilir.'],
    life: ['Bir çuvalın korunması tek bir kilitle sağlanmaz. Yerleşimde kuru tutma, sayma ve taşımayı aynı işin parçaları bilenler daha güvenilir bulunur.'],
    related: ['danstsud', 'rymar', 'lurnvalf'],
  },
  {
    id: 'lurnvalf', name: 'Lurnvalf', region: 'danstsud', x: 7740, y: 3790,
    subtitle: 'Lowvale yazısı altında yol ve ambar kümesi',
    summary: 'Lurnvalf’in küçük ambarları, yolun yalnız üstünden geçilmediğini gösterir. Burada malın bir sonraki durağa hazır olması için görünmeyen işler yapılır.',
    scene: ['Yoldan gelen çuvalın ağzı yeniden bağlanır. İçeride çalışana küçük görünen bir düzeltme, bir sonraki arabada bütün yükün dağılmasını önleyebilir.'],
    life: ['Taşıma işinin değeri, bazen hiçbir şeyin bozulmamasıdır. Lurnvalf’te yükü eksiksiz teslim eden kişinin adı, parlak bir dükkân tabelasından daha kalıcı biçimde dolaşır.'],
    related: ['danstsud', 'lysmar', 'jathra'],
  },
  {
    id: 'jathra', name: 'Jathra', region: 'danstsud', x: 8040, y: 3610,
    subtitle: 'Doğu ova kıyısındaki yapı ve ambarlar',
    summary: 'Jathra’da karadan gelen yükün beklediği yer ile suya bakan evler aynı çevrede durur. Bir sandığın güneşten korunması küçük fakat ortak bir sorumluluktur.',
    scene: ['Gölgelik arayan taşıyıcı, ambarı yöneten kişinin eliyle gösterdiği yere yükünü bırakır. Aceleyle yanlış yerde bekletilen bir mal için havayı suçlamak sonraki pazarlığı kurtarmaz.'],
    life: ['Bir yerleşimin refahı her zaman büyük bir pazara sahip olmasıyla oluşmaz. Yükün bekleyebildiği güvenilir yer, küçük hanelerin sürekli işe ulaşmasına da katkı sağlar.'],
    related: ['danstsud', 'lurnvalf', 'orinhal'],
  },
  {
    id: 'melthir', name: 'Melthir', region: 'danstsud', x: 7500, y: 4020,
    subtitle: 'Serenith çevresinde değirmen ve tarla hayatı',
    summary: 'Melthir’de yel değirmeninin dönüşü ile evlerdeki sofra aynı günün hesabına girer. Verimli ova, burada insan eliyle un ve erzağa dönüşür.',
    scene: ['Değirmenin yakınında bekleyen çuvallar sahiplerine göre sıralanır. Rüzgâr döndüğünde bir aile işini erken bitirebilir; durduğunda aynı aile ertesi günü yeniden planlar.'],
    life: ['Un üretimi yalnız ürünü öğütmek değildir. Sıra tutmak, kuru depolamak ve yolcunun yükünü zamanında teslim etmek birbirini izler; bir işin gecikmesi diğerinin kazancını azaltır.'],
    related: ['danstsud', 'valdareth', 'danstsud-ekmek-ve-vergi'],
  },
  {
    id: 'orinhal', name: 'Orinhal', region: 'danstsud', x: 8050, y: 4030,
    subtitle: 'Doğu su kenarında mor çatılı kent',
    summary: 'Orinhal’ın kuleleri tarlaya ve suya aynı anda bakar. Yolun taşıdığı yük ile kıyının beklediği haber, kentte birbirinden ayrı tutulamaz.',
    scene: ['Kıyıya inen yolun üstünde bir yük bırakılırken kentteki alışveriş devam eder. Taşıyıcı dönmeden önce sıcak yemek arar, dükkân sahibi gelecek malın miktarını öğrenmek ister.'],
    life: ['Kentte deniz ve kara hizmetleri birlikte yaşar. İyi ambar bulmak kadar yıpranmış taşıma bağını yenilemek de bir yolcunun burada kalmasına sebep olabilir.'],
    related: ['danstsud', 'cevan', 'cylwen'],
  },
  {
    id: 'oren', name: 'Oren', region: 'danstsud', x: 7090, y: 4270,
    subtitle: 'Serenith kıyısında küçük ova yapı kümesi',
    summary: 'Oren’de suya yakın evlerin günlük işi, kıyının bakımını da içerir. Bir taşıyıcının yükü kuru teslim alması, arkada yapılan küçük onarımlara bağlıdır.',
    scene: ['Köprüye yaklaşan biri evlerin gölgesine bakarak duracak yer seçer. İçeride çalışan bir hane ise aynı gölgeyi nem tutup tutmadığıyla değerlendirir; aynı manzara farklı ihtiyaçlara cevap verir.'],
    life: ['Su kenarında üretim ile bakım aynı iş gününe sığar. Bir hane yük hazırlarken komşu, geçişi açık tutacak basit bir tamire el verebilir; kazanç böyle küçük yardımlarla devam eder.'],
    related: ['danstsud', 'valdareth', 'runeth'],
  },
  {
    id: 'cylwen', name: 'Cylwen', region: 'danstsud', x: 7820, y: 4310,
    subtitle: 'Değirmenlerin yakınında ova ve ambar',
    summary: 'Cylwen’de rüzgârın getirdiği iş, ambarların kuru tutulduğu ölçüde kazanca dönüşür. Aynı günün hasadı başka bir ailenin ekmeğini belirleyebilir.',
    scene: ['Bir değirmenin sesi durduğunda yol üstündeki sohbet uzar. Bekleyenler yalnız kendi sırasını değil, akşam yemeğinin hangi saatte hazırlanacağını da hesaplar.'],
    life: ['Bir ürünü yetiştirmekle onu yenebilir hâle getirmek arasında ayrı emekler bulunur. Cylwen’de un, taşıma ve depolama aynı pazarın birbirinden ayrı hesaplarıdır.'],
    related: ['danstsud', 'melthir', 'halden'],
  },
  {
    id: 'halden', name: 'Halden', region: 'danstsud', x: 7700, y: 4540,
    subtitle: 'Ova yollarının kesiştiği ambar yerleşimi',
    summary: 'Halden’in ambarları yolları birbirine bağlayan gündelik işlerden geçim çıkarır. Hangi yükün önce çıkarılacağı bazen en büyük pazarlıktır.',
    scene: ['Kapının önünde bir araba boşaltılırken öteki bekler. Çalışanların aynı yükü iki kez taşımamak için verdiği küçük karar, kervanın o gün yetişip yetişmeyeceğini belirleyebilir.'],
    life: ['Yol kesişimi kendiliğinden düzen getirmez. Hangi alanın yük için boş tutulacağı ve bir anlaşmazlıkta kimin sözüne güvenileceği kentte gündelik konuşmalarla oluşur.'],
    related: ['danstsud', 'cylwen', 'teyla'],
  },
  {
    id: 'lamden', name: 'Lamden', region: 'danstsud', x: 6600, y: 4640,
    subtitle: 'Pembe ağaçlar arasında ova ve ambar',
    summary: 'Lamden’de güzel görünen tarla kenarı, taşıyıcı için dar bir dönüş alanı da olabilir. Kentin gündelik düzeni manzarayı işe uygun tutmakla kurulur.',
    scene: ['Ağaçların altındaki yükler önce gölgeye, sonra çıkacak arabanın yönüne göre dizilir. Bir aile kendi kapısının önünü açık isterken taşıyıcı aynı alanı kısa süreli depolama olarak görür.'],
    life: ['Bereketli çevre, hanelerin birbirine engel olmadan çalışmasını gerektirir. Lamden’in yeni kesitinde küçük alan paylaşımı, büyük bir siyasi çatışmaya gerek kalmadan hikâye üretir.'],
    related: ['danstsud', 'elorwyn', 'vossir'],
  },
  {
    id: 'vossir', name: 'Vossir', region: 'danstsud', x: 6930, y: 4660,
    subtitle: 'Teyra yakınındaki yük ve ambar durağı',
    summary: 'Vossir’de yük sahipleri suya yakınlığın kolaylığını, ambar işçileri onun nemini konuşur. Aynı kentin zenginliği iki farklı hesapta görünür.',
    scene: ['Bir çuval kıyıya yakın duvara bırakılınca hemen geri alınır. Yolcu küçük uyarıya şaşırabilir; içerideki işçi geçtiğimiz haftanın kaybını hatırlayarak konuşur.'],
    life: ['Kentte iyi depolama, bir sözleşmenin sessiz şartıdır. Malın tam gelmesi ile sağlam kalması birbirini izler; biri eksik olunca diğerinin hesabı bozulur.'],
    related: ['danstsud', 'runeth', 'lamden'],
  },
  {
    id: 'runeth', name: 'Runeth', region: 'danstsud', x: 7260, y: 4660,
    subtitle: 'Ova suyu ve köprü yakınındaki yerleşim',
    summary: 'Runeth’te bir köprünün açık kalması, hanelerin işine doğrudan dokunur. Suya bakan evlerle yoldan gelen yükler aynı günlük ritmi paylaşır.',
    scene: ['Köprü başında yükler sıraya alındığında dükkân sahipleri bekleyenlere yiyecek sunar. Bir gecikme başka birinin kazancı olabilir; kentte bunun ne kadarının makul olduğu da konuşulur.'],
    life: ['Geçiş hizmeti ile yerel üretim birbirinin yerine geçmez. Runeth’te yolu açık tutan işçiler kadar hanelerin kendi küçük üretimi de şehrin beklemeye dayanmasını sağlar.'],
    related: ['danstsud', 'oren', 'vossir'],
  },
  {
    id: 'teyla', name: 'Teyla', region: 'danstsud', x: 8080, y: 4720,
    subtitle: 'Doğu ovada ev, değirmen ve ambar',
    summary: 'Teyla’da tarlanın ürünü, değirmen ve ambar arasında birkaç kez el değiştirir. Küçük yerleşimin hikâyesi bu geçişlerde kimin emeğinin hatırlandığıyla büyür.',
    scene: ['Bir arabadan indirilen son çuval akşam ışığında yeniden sayılır. Hatanın sabaha kalması, yalnız yük sahibini değil ertesi iş için bekleyen başka aileyi de etkiler.'],
    life: ['İyi bir mevsimin kazancı işlerin sırasıyla tamamlanmasına bağlıdır. Teyla’da hasat, öğütme ve taşıma aynı ailede buluşabilir; biri gecikince ötekinin planı değişir.'],
    related: ['danstsud', 'halden', 'theramis'],
  },
  {
    id: 'eroth', name: 'Eroth', region: 'danstsud', x: 6870, y: 4910,
    subtitle: 'Elorwyn ile Theramis çevresindeki ova durağı',
    summary: 'Eroth’ta büyük kentlere gidecek yük, küçük ambarların günlük işinden geçer. Bir gecelik bekleme, sahibinin başka bir kentteki bütün hesabını değiştirebilir.',
    scene: ['Ağaç gölgesindeki yapı grubunda mallar çıkacak yola göre ayrılır. Bir yolcu beklemenin maliyetini anlatırken içerideki işçi yükün yanlış arabaya konmamasını düşünür.'],
    life: ['Küçük bir durağın güvenilirliği bazen fiyatından daha önemlidir. Malını burada bırakmış biri başka işini yapabilir; döndüğünde aynı yükü bulması, yerleşimin bütün ticari itibarına katkı sağlar.'],
    related: ['danstsud', 'elorwyn', 'theramis'],
  },
  {
    id: 'janvar', name: 'Janvar', region: 'danstsud', x: 7000, y: 5450,
    subtitle: 'Güney kıyıda yolun son küçük ambarları',
    summary: 'Janvar’ın kıyıdaki küçük ambarları, büyük şehirlerin gölgesinde kalan son işleri toplar. Bir yolcunun vardığını haber veren şey bazen yalnız kapı önündeki yeni yük olur.',
    scene: ['Theramis yakınındaki kıyıda yapıların önü kısa süreli bekleyen mallarla dolar. Gelen biri kentteki büyük pazara gitmeden önce yükünü burada düzeltmek isteyebilir.'],
    life: ['Büyük bir şehrin yakınında küçük bir işin değeri kaybolmaz. Sandığı yeniden bağlayan el, şehirde imzalanacak sözleşmenin yerine gelmesine katkı yapar; bunun karşılığı günlük kazanca dönüşür.'],
    related: ['danstsud', 'theramis', 'eroth'],
  },
]

export const newlyMappedPlaces: Place[] = settlements.map(entry => ({
  id: entry.id, name: entry.name, region: entry.region, kind: 'settlement',
  point: pixelPoint(entry.x, entry.y), positionStatus: 'mapped',
  subtitle: entry.subtitle, summary: entry.summary,
  sources: ['Aruzahr 8k (1).jpg', mapAuditSource, mappedLifeSource],
  related: entry.related || [entry.region],
  sections: [
    { title: 'Sokaktan bir sahne', scene: true, paragraphs: entry.scene },
    { title: 'Geçim, bağlar ve küçük anlaşmazlıklar', paragraphs: entry.life },
  ],
}))
export const newMapPixels = settlements.map(({ id, name, region, x, y, readingNote }) => ({ id, name, region, x, y, readingNote }))
