export type Artwork = { id: string; src: string; title: string; caption: string; origin: 'author' | 'generated' | 'map' | 'adapted'; portrait?: boolean }
const picture = (id: string, title: string, caption: string, origin: Artwork['origin'] = 'generated', portrait = false): Artwork => ({ id, src: `/illustrations/${id}.webp`, title, caption, origin, portrait })
export const regionNames: Record<string, string> = { xotar: 'Xotar', murgul: 'Murgul', honud: 'Honud', danstsud: 'Danstsud', garmirk: 'Garmirk', ariki: 'Ariki', gurbin: 'Gurbin', lakbar: 'Lakbar' }
const regionCaptions = ['Su, kum ve kervanların buluştuğu vahalar', 'Ada limanları ve Azja mirası', 'Klan evleri, atalar ve soğuk kıyılar', 'Mor çatılar, beş sur ve bereketli ova', 'Taş, demircilik ve klan hafızası', 'Deniz sunakları ve özgür ada klanları', 'Kayalık limanlar ve bağımsızlık', 'Basalt, sıcak sular ve volkan ustalığı']
export const countryArt = Object.fromEntries(Object.keys(regionNames).map((id, i) => [id, picture(`region-${id}`, regionNames[id], regionCaptions[i])]))
const settlementRows = [
  ['valdareth', 'Valdareth', 'Beş surun içindeki başkent'], ['dorvenhall', 'Dorvenhall', 'Maden ve menekşespatı ustalığı'], ['lirendil', 'Lirendil', 'ÇelikKalkan’ın kale şehri'], ['elorwyn', 'Elorwyn', 'Elorwynder hanedanının surları'], ['theramis', 'Theramis', 'Ruhsatlı büyü ve kâtiplik'], ['marhalden', 'Marhalden', 'Aldara’nın iki kıyısındaki geçit kenti'], ['frostbay', 'Frostbay', 'Eski taşların arasında yeni hayat'], ['dranthol', 'Dranthol', 'Ocak Kalesi ve soğuk liman'], ['ternhaven', 'Ternhaven', 'Rydorn’un sıcak sularında yaşam'], ['vyssgard', 'Vyssgard', 'Beş İskele’nin karanlık kıyısı'], ['kaldmere', 'Kaldmere', 'Son Umut’un derme çatma limanı'], ['brannis', 'Brannis', 'Lowvale pazarı ve yerel lordluk'], ['luthen', 'Luthen', 'Kıyı yolunun küçük karakolu'], ['myrran', 'Myrran', 'İskele, kervan ve kıyı ticareti'], ['kethra', 'Kethra', 'Lord Damian’ın liman şehri'],
  ['pilorn', 'Pilorn', 'Başkentin tahıl ve yük havzası'], ['fehar', 'Fehar', 'Ova otlakları ve süt haneleri'], ['gaalmire', 'Gaalmire', 'Yol hanları ve yük ambarları'], ['naeron', 'Naeron', 'Nehir bahçeleri ve sebze yükleri'], ['fevric', 'Fevric', 'Yeldeğirmenleri ve arpa'], ['theld', 'Theld', 'Tahıl, bakliyat ve hasat emeği'], ['korhenden', 'Korhenden', 'Arabacılar, sığırlar ve ahşap işleri'], ['uldar', 'Uldar', 'Doğunun hayvan ve erzak pazarı'], ['tolvur', 'Tolvur', 'Doğu yamaçlarında sürüler'], ['toran', 'Toran', 'Geçide giden yem ve yük'], ['harven', 'Harven', 'Hardlane’in av ve odun yerleşimi'], ['mavric', 'Mavric', 'Orman kıyısındaki korunan av köyü'],
]
const portraits = [
  ['orren-vask', 'Orren Vask', 'Başmühürdar', 'generated'], ['teren-halvek', 'Teren Halvek', 'Başkent vekili', 'generated'], ['sera-neld', 'Sera Neld', 'İaşe nazırı', 'generated'], ['doran-kest', 'Doran Kest', 'Liman nazırı', 'generated'], ['lethan-orve', 'Lethan Orve', 'Sicil nazırı', 'generated'], ['solan', 'Başbüyücü Solan', 'Theramis · Altın Yılan', 'generated'],

  ['eryndorn', 'Eryndorn Vaeranth', 'Danstsud kralı', 'author'], ['alisande', 'Kraliçe Alisande Vaeranth', 'Saray iaşesi ve yardım düzeni', 'generated'], ['ilyenne', 'Prenses Ilyenne Vaeranth', 'Hukuk ve yönetim öğrenen kraliyet kızı', 'generated'], ['mirelda', 'Leydi Mirelda Vaeranth', 'Kraliyet ailesinin diplomatik temsilcisi', 'generated'], ['maelis-dervan', 'Maelis Dervan', 'Kraliyet hazinedarı', 'generated'],
  ['tharion', 'Lord Tharion Elorwynder', 'Elorwyn yöneticisi', 'adapted'], ['damian', 'Lord Damian Elorwynder', 'Kethra lordu', 'adapted'], ['aveline', 'Leydi Aveline Elorwynder', 'Damian’ın eşi', 'adapted'], ['rook', 'Ser Rook Valdenar', 'Rydorn Sırtı arazilerinin sahibi', 'author'],
  ['nera-veld', 'Nera Veld', 'Frostbay kraliyet vekili', 'generated'], ['edran-korr', 'Edran Korr', 'Marhalden lordu', 'generated'], ['bryndon', 'Kâtip Bryndon', 'Theramisli kıyı araştırmacısı', 'generated'], ['rovan-mereth', 'Rovan Mereth', 'Dorvenhall lordu', 'generated'], ['averen-dhal', 'Averen Dhal', 'Lirendil lordu', 'generated'], ['elyas-theren', 'Elyas Theren', 'Theramis lordu', 'generated'], ['varlen-neth', 'Varlen Neth', 'Brannis lordu', 'generated'], ['garran-veyl', 'Ser Garran Veyl', 'Dranthol kale komutanı', 'generated'], ['mera-sorn', 'Mera Sorn', 'Ternhaven Ocak Meclisi sözcüsü', 'generated'], ['vessa-thol', 'Vessa Thol', 'Marhalden baş lonca üyesi', 'generated'], ['odran-vehl', 'Odran Vehl', 'Frostbay garnizon komutanı', 'generated'],
  ['vardek', 'Sir Vardek', 'ÇelikKalkan Büyük Üstadı', 'author'], ['kaelen', 'Yüzbaşı Kaelen', 'ÇelikKalkan’ın sert eğitmeni', 'author'], ['ellyn', 'Ellyn Marowen', 'Baş arşivci', 'author'], ['ghorin', 'Tek-Göz Ghorin', 'Lirendil demirhane ustası', 'author'], ['zylara', 'Hekim Zylara', 'Lonca hekimi ve simyacı', 'author'], ['mrog', 'Sessiz Mrog', 'Lonca muhafızı', 'author'], ['gil', 'Gil', 'Dorvenhallli ÇelikKalkan üyesi', 'author'], ['jeremiah', 'Jeremiah', 'Zeki ve umursamaz lonca maceracısı', 'author'], ['volomiyr', 'Volomiyr', 'Elorwynli paladin', 'author'], ['vaelcor', 'Magister Vaelcor', 'Lirendil Büyü Akademisi ustası', 'author'], ['rickon', 'Sir Rickon Thornhall', 'Başkentin kıdemli muhafızı', 'author'], ['varric', 'Varric Draven', 'Dravenspireli kıdemli lonca mensubu', 'adapted'], ['corvan', 'Sir Corvan Solara', 'ÇelikKalkan’da bulunan şövalye', 'author'], ['rina', 'Rina Ironvale', 'Ser Valerius’un yaveri', 'author'], ['valerius', 'Ser Valerius', 'Elorwyn iktidarının rakibi', 'adapted'], ['seraphinia', 'Seraphinia', 'Kethra’dan bir yüz', 'author'], ['tarb', 'Tarb', 'Hardlane’den gelen gezgin', 'author'], ['grathor', 'Grathor', 'Gurbinli savaşçı', 'author'], ['varoxh', 'Varoxh', 'Gurbinli barbar · Varokh adıyla da anılır', 'author'], ['roddic', 'Kaptan Roddic', 'Denizci kaptan', 'author'], ['yasli-kaelen', 'Yaşlı Kaelen', 'Honudlu mülteci', 'author'], ['ashara', 'Ashara', 'Valdareth’ten bir portre', 'author'], ['lysandra', 'Lysandra', 'Karakter portresi', 'author'],
]
export const faunaArt = [
  picture('tac-kecisi', 'Karlan Taç Keçisi', '2.500–5.200 m · otçul · kaya terasları'), picture('kar-kartali', 'Veyrakar Kar Kartalı', '3.000–6.200 m · küçük avlar ve leş'), picture('cig-kuzgunu', 'Tholkar Çığ Kuzgunu', '1.500–4.800 m · hepçil · iki parçalı ötüş'), picture('orvak', 'Sırtyünlü Orvak', '1.700–3.500 m · otçul · yün ve yük'), picture('varkul', 'Buzyeleli Varkul', '2.200–4.700 m · tek başına avlanan yırtıcı'), picture('kharven', 'Körük Sırtlı Kharven', '2.500–4.200 m · altı uzuv · sıcak çatlaklar'), picture('ulveth', 'Yarık Dinleyicisi Ulveth', '3.500 m altında · kör mağara canlısı'), picture('gumusalasi', 'Aldara Gümüşalası', 'Soğuk, temiz akarsu · çakılda üreme'),
]
const sceneArt = [
  picture('remaster-horizon', 'Taçtan Karlan’a', 'Valdareth ve Karlan’ı bir araya getiren giriş illüstrasyonu · coğrafi harita değildir'),
  picture('eryndorn-study', 'Eryndorn’un çalışma odası', 'Kraliyet kütüphanesinde hükümdar', 'adapted', true),
  picture('buyuk-kirilma', 'Büyük Kırılma', 'Ateş, ışık ve kül · eski destanların felaketi'), picture('ejderha-imparatorlugu', 'Ejderha İmparatorluğu', 'Sessiz Binyıl’dan bir hayat tasviri'), picture('halendar', 'Halendar · Ateşin Çocuğu', 'Kızıl Kral’ın destanlardaki görünümü'), picture('yarethus', 'Yarethus · Bakır Ana', 'Işığın Savaşı anlatısındaki koruyucu çember'),
  picture('tervan', 'Kırağı Boynuzlu Tervan', 'İnce donu sıyıran otlak hayvanı'), picture('norruk', 'Kütburunlu Norruk', 'Saz kökü ve yumru arayan ağır gövdeli tür'), picture('velkir', 'Saztırnaklı Velkir', 'Sıcak su çevresinin kıyı otçulu'), picture('veyralt', 'Veyralt cevheri', 'Koyu kayada ince mavimsi metal çizgileri'),

  picture('karlan', 'Karlan Dağları', 'Hardlane ile doğu toprakları arasındaki dağ eşiği'), picture('frostmere', 'Frostmere Gölü', 'Yılın yarısını buz altında geçiren su'), picture('ak-cam', 'Ak Cam Denizi', 'Ternhaven ve Dranthol önündeki açık deniz'),
  picture('kethra-map', 'Kethra yerleşim haritası', 'Rydorn Sırtı ve liman çevresi', 'author'), picture('kethra-liman', 'Kethra limanı', 'Gece yükleri ve soğuk iskeleler', 'author'), picture('denizkizi-meyhanesi', 'Denizkızı Meyhanesi', 'Liman kentinin sıcak iç mekânı', 'author'), picture('kanca-meyhanesi', 'Kanca Meyhanesi', 'Yolcuların ve liman insanlarının masaları', 'author'), picture('lirendil-map', 'Lirendil yerleşim haritası', 'Yazarın ayrıntılı şehir çizimi', 'author'), picture('celikkalkan-map', 'ÇelikKalkan yerleşkesi', 'Lonca avlusu ve savunma düzeni', 'author'), picture('celikkalkan-yemek', 'ÇelikKalkan yemekhanesi', 'Lonca yaşamının ortak masası', 'author'), picture('demirci-ocagi', 'Lirendil demirci ocağı', 'Ateş, örs ve kılıç işçiliği', 'author'), picture('lirendil-sokak', 'Lirendil sokakları', 'Dağ gölgesindeki taş cepheler', 'author'), picture('myrran-map', 'Myrran yerleşim haritası', 'İskele çevresindeki küçük yerleşim', 'author'), picture('valdareth-zindan', 'Valdareth büyük hapishanesi', 'Taş koridorlar ve şehir muhafızları', 'author'),
]
export const artworks: Record<string, Artwork> = Object.fromEntries([
  ...Object.values(countryArt), ...settlementRows.map(([id, title, caption]) => picture(id, title, caption)), ...portraits.map(([id, title, caption, origin]) => picture(id, title, caption, origin as Artwork['origin'], true)), ...faunaArt, ...sceneArt,
].map(a => [a.id, a]))
const portraitAliases: Record<string, string> = { 'bryndon-kiyi-defteri': 'bryndon' }
export const portraitFor = (id: string) => { const item = artworks[portraitAliases[id] || id]; return item?.portrait ? item : undefined }
const readingCovers: Record<string, string> = { 'danstsud-ekmek-ve-vergi':'pilorn', 'hardlane-bir-kis':'frostbay', 'karlan-iscilik-ve-gecit':'marhalden', 'danstsud-makam-ve-itiraz':'valdareth' }
export const primaryArtwork = (id: string) => countryArt[id] || artworks[readingCovers[id] || portraitAliases[id] || id]
const galleries: Record<string, string[]> = {
  'danstsud-ekmek-ve-vergi':['fevric','naeron','sera-neld','dorvenhall'], 'hardlane-bir-kis':['kaldmere','ternhaven','dranthol','tervan'], 'karlan-iscilik-ve-gecit':['veyralt','edran-korr','vessa-thol','karlan'], 'danstsud-makam-ve-itiraz':['orren-vask','lethan-orve','rickon','tharion'],
  eryndorn: ['eryndorn-study', 'valdareth'],
  'rilorn-korfezi': ['valdareth', 'doran-kest'],
  'buyuk-kirilma': ['ejderha-imparatorlugu', 'halendar', 'yarethus'], 'hardlane-otlak-hayvanlari': ['tervan', 'norruk', 'velkir'], veyralt: ['marhalden'], 'rydorn-sirti': ['ternhaven', 'rook'], 'lirendil-buyu-akademisi': ['vaelcor', 'lirendil-sokak'],
  valdareth: ['eryndorn', 'alisande', 'ilyenne', 'mirelda', 'maelis-dervan', 'rickon', 'valdareth-zindan', 'remaster-horizon'], lirendil: ['lirendil-sokak', 'lirendil-map', 'celikkalkan-map', 'celikkalkan-yemek', 'demirci-ocagi', 'vardek', 'ghorin', 'zylara', 'ellyn', 'gil', 'jeremiah', 'volomiyr'], kethra: ['kethra-liman', 'kethra-map', 'denizkizi-meyhanesi', 'kanca-meyhanesi', 'damian', 'aveline', 'rook', 'seraphinia'], myrran: ['myrran-map'], elorwyn: ['tharion', 'volomiyr', 'valerius'], marhalden: ['karlan', 'frostmere', 'edran-korr', 'vessa-thol'], frostbay: ['nera-veld', 'odran-vehl', 'bryndon'], dranthol: ['garran-veyl', 'ak-cam'], ternhaven: ['mera-sorn', 'ak-cam'], dorvenhall: ['rovan-mereth', 'gil'], theramis: ['elyas-theren', 'bryndon'], brannis: ['varlen-neth'],
  'vaeranth-hanedani': ['eryndorn', 'alisande', 'ilyenne', 'mirelda'], 'elorwynder-hanedani': ['tharion', 'damian', 'aveline', 'rook'], 'karlan-canlilari': faunaArt.map(a => a.id), 'karlan-daglari': ['karlan', 'marhalden', 'orvak', 'kar-kartali'], 'celikkalkan-loncasi': ['celikkalkan-map', 'celikkalkan-yemek', 'vardek', 'kaelen', 'varric', 'mrog'], 'valdareth-saray-makamlari': ['maelis-dervan', 'eryndorn', 'rickon'],
}
export function galleryFor(id: string, region: string, cover: string): Artwork[] {
  const primary = primaryArtwork(id) || Object.values(artworks).find(a => a.src === cover) || countryArt[region]
  const list = [primary, ...(galleries[id] || []).map(key => artworks[key])].filter((a): a is Artwork => !!a)
  return list.filter((item, i) => list.findIndex(a => a.id === item.id) === i)
}
