import type { Artwork } from './media'
import { faunaArtMetadata } from './lore/world-fauna'
import { paintedDetailArtworks, paintedDetailAliases } from './painted-details-manifest'

/** New paintings are separate exports; original source artwork stays intact. */
export const paintedSceneArtworks: Artwork[] = [
  ...paintedDetailArtworks,
  ...faunaArtMetadata.map(({ id, title, caption }): Artwork => ({ id, src: `/illustrations/${id}.webp`, title, caption, origin: 'generated', painted: true, category: 'fauna', relatedId: id })),
  { id: 'eryndorn-painted', src: '/illustrations/eryndorn-painted.webp', title: 'Eryndorn Vaeranth', caption: 'Bilginin ağırlığı · yeni el boyaması kral portresi', origin: 'generated', portrait: true, painted: true, category: 'portrait', relatedId: 'eryndorn' },
  { id: 'valdareth-painted', src: '/illustrations/valdareth-painted.webp', title: 'Valdareth · Beş surun şehri', caption: 'Mor çatılar, Kara Ayna, İlk Işık ve Rilorn · yağlı boya başkent panoraması', origin: 'generated', painted: true, category: 'landscape', relatedId: 'valdareth' },
  { id: 'eryndorn-library-painted', src: '/illustrations/eryndorn-library-painted.webp', title: 'Eryndorn · Açık kalan kitap', caption: 'Kralın çalışma odasında kararın ağırlığı · el boyaması sahne', origin: 'generated', painted: true, category: 'scene', relatedId: 'eryndorn' },
  { id: 'lakbar-painted', src: '/illustrations/lakbar-painted.webp', title: 'Lakbar · Sıcak taşın kıyısı', caption: 'Basalt evler ve sıcak denizde ustalık · boya dokulu manzara', origin: 'generated', painted: true, category: 'landscape', relatedId: 'lakbar' },
  ...[
    ['elorwyn','Elorwyn','Paladinler, dinî ocaklar ve eski hanedan surları','elorwyn'], ['marhalden','Marhalden','Aldara’nın iki kıyısındaki kaleler ve zırhlı geçit nöbeti','marhalden'], ['theramis','Theramis','Altın Yılan’ın avlusunda ruhsatlı büyü','theramis'], ['dorvenhall','Dorvenhall','Sarp sırtlarda madenci ocakları ve yüksek yollar','dorvenhall'], ['lirendil','Lirendil','ÇelikKalkan’da talim ve ortak sofra','lirendil'], ['frostbay','Frostbay','Dairetaş kalıntıları ve yeni kıyı haneleri','frostbay'],
    ['dranthol','Dranthol','Ocak Kalesi ve güvenli fakat tenhalaşmış rıhtım','dranthol'], ['ternhaven','Ternhaven','Rydorn sıcak suları çevresindeki ocaklar','ternhaven'], ['vyssgard','Vyssgard','Beş İskele’de dar sokaklar ve kırılgan anlaşmalar','vyssgard'], ['kaldmere','Kaldmere','Son Umut’un barakaları ve buzda balıkçılık','kaldmere'], ['brannis','Brannis','Lowvale pazarı ve tahıl yükleri','brannis'], ['luthen','Luthen','Kıyı yolunun küçük geçiş kenti','luthen'],
    ['myrran','Myrran','İskelede gün doğumu ve kurutulan balıklar','myrran'], ['kethra','Kethra','Elorwynder limanında akşam ışıkları','kethra'], ['karlan','Karlan Dağları','Yüksek buz dorukları ve aşağıdaki geçit','karlan-daglari'], ['frostmere','Frostmere Gölü','Buzun sınırında açık su ve kıyı haneleri','frostmere-golu'], ['ak-cam','Ak Cam Denizi','Soğuk kıyı önündeki açık deniz','ak-cam-denizi'], ['rilorn','Rilorn Körfezi','Mor Donanma’nın korunan demirleme alanı','rilorn-korfezi'],
  ].map(([id,title,caption,relatedId]): Artwork => ({ id: `${id}-painted`, src: `/illustrations/${id}-painted.webp`, title, caption: `${caption} · boya dokulu illüstrasyon`, origin: 'generated', painted: true, category: 'landscape', relatedId })),
  ...[
    ['xotar', 'Xotar', 'Kuyular, kervanlar ve Kum İpeği'], ['murgul', 'Murgul', 'Azja ocakları ve ada limanları'], ['honud', 'Honud', 'Kış vadileri ve klan haneleri'], ['garmirk', 'Garmirk', 'Taş, örs ve yemin'], ['ariki', 'Ariki', 'Serbest rüzgâr ve deniz sunakları'], ['gurbin', 'Gurbin', 'Bağımsız klanların kayalık kıyısı'],
  ].map(([id, title, caption]): Artwork => ({ id: `region-${id}-painted`, src: `/illustrations/region-${id}-painted.webp`, title, caption: `${caption} · el boyaması dünya manzarası`, origin: 'generated', painted: true, category: 'landscape', relatedId: id })),
]
export const paintedSceneAliases: Record<string, string> = { ...paintedDetailAliases, eryndorn: 'eryndorn-painted', 'eryndorn-study': 'eryndorn-library-painted', valdareth: 'valdareth-painted', 'region-danstsud': 'valdareth-painted', 'region-lakbar':'lakbar-painted', ...Object.fromEntries(['xotar','murgul','honud','garmirk','ariki','gurbin'].map(id => [`region-${id}`,`region-${id}-painted`])), ...Object.fromEntries(['elorwyn','marhalden','theramis','dorvenhall','lirendil','frostbay','dranthol','ternhaven','vyssgard','kaldmere','brannis','luthen','myrran','kethra','karlan','frostmere','ak-cam'].map(id=>[id,`${id}-painted`])), 'karlan-daglari':'karlan-painted','frostmere-golu':'frostmere-painted','ak-cam-denizi':'ak-cam-painted','rilorn-korfezi':'rilorn-painted' }
