import type { Dossier } from './presentation'

// Public worldbuilding estimates, not figures quoted from a historical census.
const note = 'Yeni dünya yazımı · yerleşim ve çevresi için tahmin; resmî sayım değil'
type Row = [string, string, string, string, string, string, string[], [number, number, number, number], string, string]
const rows: Row[] = [
  ['zarim-khet', 'Vaha meclisleri', '≈ 75.000', 'Su meclisleri · Sahira Nemesh hakemliği', 'Su hakkı ve yerel meclisler', 'Kuru sıcak · yeraltı su yolları', ['Baharat', 'Su hizmetleri', 'Kervan yükü'], [3,5,4,3], 'Bir kuyunun gölgesi, bir mahallenin ömrüdür.', 'Sahira’nın önüne gelen aynı kırık tas için iki hane farklı bir hak iddia eder. Kentin büyük hesabı, böyle küçük masalarda görülür.'],
  ['thariz', 'Kervan kapısı', '≈ 21.000', 'Kervan toplantısı · Daren Khoss yol güvenliği', 'Su ocağı ve kervan temsilcileri', 'Çöl kenarı · sert gece ayazı', ['Yük hayvanları', 'Kervan bakımı', 'Kurutulmuş erzak'], [3,4,2,3], 'Yolun bedeli kapıda ödenir.', 'Geç kalan bir kervan yalnız taciri ilgilendirmez. Ahır, yem satıcısı ve su başında bekleyen aile de aynı dönüşü hesaplar.'],
  ['sahrim', 'Şifa vahası', '≈ 34.000', 'Yerel su meclisi · Nemeh Sarun şifahanesi', 'Vaha haneleri ve Karutah ocakları', 'Kuru sıcak · korunaklı bahçeler', ['Şifalı ürünler', 'Bahçe mahsulü', 'Deri işleri'], [2,3,4,3], 'Yaraya su, sözden önce gelir.', 'Şifahanenin gölgesinde bekleyenlerin tümü aynı inançtan gelmez. Nemeh’in ilk sorusu isim değil, son kez ne zaman su içildiğidir.'],
  ['qal-nashar', 'Kum İpeği pazarı', '≈ 49.000', 'Pazar meclisi · Rahim Vekk ticaret çevresi', 'Tartı masası ve vaha temsilcileri', 'Çöl ticaret eşiği', ['Kum İpeği', 'Tahıl', 'İşlenmiş taş'], [3,5,3,3], 'İnce bir iplik, uzun bir borcu taşır.', 'Pazarda bir kumaşın değeri tartıyla bitmez. Onu yetiştiren bahçe, kozasını ayıran el ve ertelenen ücret de pazarlığın içindedir.'],
  ['morihael', 'Adaların ortak limanı', '≈ 68.000', 'Liman toplantısı · Ilvara Senn sözcülüğü', 'Ada topluluklarının liman meclisi', 'Nemli kıyı · orman adaları', ['Baharat', 'Gemi işleri', 'Deniz ürünleri'], [3,5,4,4], 'Aynı rıhtımda farklı diller tutunur.', 'Ilvara’nın toplantısında gemi kerestesini Kevar, ocağın kaygısını Torren anlatır. Bir liman kararı, üç ayrı hayatın ortak sözünü ister.'],
  ['skjornhvaldr', 'Kış kıyısı', '≈ 23.000', 'Klan ocakları · Sigrun Nel av rehberliği', 'Klan haneleri ve ortak kış payı', 'Uzun kış · sert kıyı rüzgârı', ['Post', 'Tütsülenmiş balık', 'Av araçları'], [3,2,3,3], 'Ocak payı tükenmeden komşunun adı sorulur.', 'Sigrun’un getirdiği av tek bir eve girmez. Bir paylaştırma kararı, önümüzdeki fırtınada kimin kapısını açacağını da belirler.'],
  ['frostheimr', 'Kış ambarları', '≈ 16.000', 'Klan ambarları · Eyrik Voss paylaştırıcılığı', 'Klanlar arasında erzak paylaşımı', 'Buz vadisi · kısa yaz', ['Kışlık erzak', 'Kemik işçiliği', 'Deri'], [3,2,3,4], 'Dolu ambar, açık kapı ister.', 'Eyrik bir çuvalı kime verdiğini unutmamak için düğüm atar. O düğümün tuttuğu borç, bir sonraki kışın güvenidir.'],
  ['norrvar', 'Sözlü kule çevresi', '≈ 12.000', 'Klan ocakları · Haldrun Ylse öğretmenliği', 'Ocaklar ve sözlü öğretim çevreleri', 'Soğuk vadi · donmuş yollar', ['Av ürünleri', 'Sözlü eğitim', 'Yün işleri'], [2,2,4,3], 'Bir söz unutulursa bir yol kapanır.', 'Haldrun’un öğrencileri bir geçidi önce adlarıyla öğrenir. Yazın taşta duran bilgi, kışın beyaz örtünün altında hafızayla bulunur.'],
  ['kaldryss', 'Soğuk kıyı haneleri', '≈ 8.000', 'Kıyı ocakları · Veyna Korr kayıkçılığı', 'Yerel klan haneleri', 'Uzun buz mevsimi · kıyı yarıkları', ['Balık', 'Kıyı taşımacılığı', 'Post'], [2,2,2,2], 'Buz her sabah aynı kıyıyı geri vermez.', 'Veyna kayığını suya indirmeden önce kıyının sesini dinler. Önceki gün açık olan dar yarık, bugün başka bir yol ister.'],
  ['baldrek', 'Örslerin şehri', '≈ 28.000', 'Ocak meclisi · Borrak Tahr temsili', 'Klan ve zanaat ocakları', 'Dağ vadisi · değişken fırtına', ['Dövme çelik', 'Taş işçiliği', 'Maden aletleri'], [4,4,3,4], 'Örsün sesi, sözün ağırlığını ölçer.', 'Thena’nın sınadığı bir çelik Borrak’ın masasına gelir. Ustalığın hatasını kabul etmek, bir klanın onurunu incitmek kadar zor olabilir.'],
  ['stoneclans', 'Taş yeminleri', '≈ 31.000', 'Klan meclisleri · Mirga Senn arabuluculuğu', 'Klan yeminleri ve ortak geçit nöbeti', 'Sarp geçit · yağışlı dağ', ['Çelik', 'Taş', 'Geçit hizmetleri'], [4,3,3,4], 'Geçidi tutan taş, iki halkın sözünü duyar.', 'Keldan’ın nöbetiyle Mirga’nın şarkısı aynı sınırı korur. Biri kapıyı kapatır; öteki ertesi gün yeniden açılabilmesini sağlar.'],
  ['twinclans', 'Ortak yük masası', '≈ 18.000', 'Ada toplantısı · Ossan Tavren hakemliği', 'Klanların seçtiği yerel temsilciler', 'Ada kıyısı · değişken rüzgâr', ['Tuz', 'Deniz yükü', 'Gemi bakımı'], [3,4,3,3], 'İki klan, tek tartı.', 'Ossan’ın masasında ölçülen şey yalnız yük değildir. Yanlış tartılan bir sandık, iki adanın bir sonraki seferini de geciktirir.'],
  ['northpact', 'Kuzey liman nöbeti', '≈ 20.000', 'Ada toplantısı · Yaren Morrik liman nöbeti', 'Seçilmiş klan temsilcileri', 'Rüzgârlı ada limanı', ['Balık', 'Nakliye', 'Tuz'], [4,3,3,4], 'Rüzgâr değişir; nöbet sözü kalır.', 'Yaren bir teknenin armasından önce suya ne kadar battığına bakar. Kimin ne taşıdığı bazen kâğıttan önce denizde görünür.'],
  ['eldrascar', 'Deniz kayıtları', '≈ 26.000', 'Ada toplantısı · Delia Eryth kayıt elçiliği', 'Klan seçimi ve yerel toplantılar', 'Kayalık kıyı · açık deniz', ['Mineral', 'Kayıt hizmeti', 'Gemicilik'], [3,4,4,3], 'Bir gemi gider; adı kıyıda kalır.', 'Delia dönüş defterine çizdiği boşluğu doldurmak için acele etmez. Denizden gelmeyen bir haberin yerine tahmin yazmak, yas tutan bir haneye borç bırakır.'],
  ['hurnreach', 'Hızlı gemiler limanı', '≈ 22.000', 'Klan toplantıları · Vraska Bralk deniz çevresi', 'Bağımsız klan otoritesi', 'Sert kayalık kıyı', ['Hızlı gemiler', 'Balık', 'Deniz ticareti'], [4,4,3,3], 'Rıhtımda verilen söz, açıkta sınanır.', 'Vraska yük sahibini limanda dinler, tayfasını açıkta. İki söz çeliştiğinde kimin risk aldığını kendisi de saklamaz.'],
  ['kraenfall', 'Kıyı borç pazarı', '≈ 19.000', 'Klan otoritesi · Nesren Tarn ikmal masası', 'Klan payları ve bağımsız pazarlar', 'Dar koylar · sürekli rüzgâr', ['İkmal', 'Deri', 'Metal araçlar'], [3,4,3,2], 'Bir sandığın gölgesinde üç borç bekler.', 'Nesren’in verdiği bir erzak avansı insanı denize çıkarabilir. Geri ödemesi ise aynı insanı istemediği bir sefere bağlayabilir.'],
  ['volriks-maw', 'Klan yemini kıyısı', '≈ 13.000', 'Klan ocakları · Morvek Kryss eğitim çevresi', 'Bağımsız klan düzeni', 'Kayalık liman · sert dalga', ['Silah', 'Av ürünleri', 'Kıyı taşımacılığı'], [4,3,3,3], 'Yemin, kıyıdan ayrılırken duyulur.', 'Morvek’in öğrencileri aynı hareketi defalarca tekrarlar. Eğitimin sonunda istenen yalnız güç değil, gücü hangi söze bağlayacaklarını seçmeleridir.'],
]

export const worldDossiers: Record<string, Dossier> = Object.fromEntries(rows.map(([id, badge, population, ruler, government, climate, exports, powers, motto, text]) => [id, { badge, population, populationNote: note, ruler, government, climate, exports, powers, motto, hooks: [{ title: 'Şehrin insanları', text }] }]))
